### ISSUE TITLE
`.with_multisampling(n)` where n is greater than 4 seems to cause window creation to fail on older versions(/implementations?) of OpenGL

### ISSUE THREAD

**Issue by daboross** [PistonDevelopers/conrod#1018]
When running any of the latest examples, I get the following error:

```
$ cargo run --example canvas --features "winit glium"
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/canvas`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(NoAvailablePixelFormat)', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

After investigation, it seems this no longer occurs if `.with_multisampling(8);` is commented out in the window constructor.

This isn't a problem for me specifically, since I already use conrod and can just not use `with_multisampling` in my apps, but might this put off future users if the examples do not work on their machine?

Alternatively - should I feel this as an issue under glium and/or glutin? I don't _think_ this is an error on their part, since the example is requesting a feature that - I guess - is not available for my graphics card.

**Comment by mitchmindtree** [comment]
@daboross thanks for the issue!

Would you mind sharing more info about your hardware, OS, OpenGL version, etc? Also, when you say the *latest* examples, do you mean the stopped working after updating to the latest `master` commit? Or did the examples never work for this particular setup?

**Comment by daboross** [comment]
@mitchmindtree Sure!

I have integrated intel graphics, according to `lspci`:
```
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
	Subsystem: Dell 2nd Generation Core Processor Family Integrated Graphics Controller
	Kernel driver in use: i915
```

Running Gentoo Linux, xorg-drivers 1.17 (I'm not even sure what that version means, I can dig further if needed).

When I say latest examples, I mean they did work sometime in the past. I'll test different changes to see exactly when it worked/didn't work. Could be completely unrelated to the glium/glutin upgrade, but I just noticed it now because I re-copied my initialization code from the examples.

**Comment by daboross** [comment]
After checking more diffs, it seems like `.with_multisampling(4)` changing to `.with_multisampling(8)` broke it for me. `.with_multisampling(8)` fails both for glium v0.17 and glium v0.16.

That would be https://github.com/PistonDevelopers/conrod/commit/ffaf573f91ca4e04204d7f387f532fbee18a958a for all_winit_glium, and https://github.com/PistonDevelopers/conrod/commit/a3b88344a71cad0fc87c0b81100d614e79cc47a1 for many of the other examples.

I guess some examples, like `file_navigator`, still have `with_multisampling(4)`, and thus still work on my computer?

**Comment by mitchmindtree** [comment]
Ahh interesting, thanks for hunting this down! It didn't even cross my mind that older GL versions might not support higher multisampling. I'd be happy for us to change all the examples to use `with_multisampling(4)` to remove the chance of folks running into this in the future :+1:

**Comment by daboross** [comment]
Ah yeah - sounds good then!

I wonder if there would be a way to "optionally" request this from glium, so as to not limit users who do have a newer card.

**Comment by jrmiller82** [comment]
Getting same error on all the examples, running on an Ubuntu 17.04 VM under virtualbox. Shows I have OpenGL 3.3 core as the max version supported.

**Comment by jrmiller82** [comment]
Confirming that commenting out `.with_multisampling(8)` and adding a semicolon to the line before allows them to run just fine.
