### ISSUE TITLE
Positionable x_y doesn't work

### ISSUE THREAD

**Issue by georgegerdin** [PistonDevelopers/conrod#1019]
I am trying to place my widget by absolute position on the window but can't get it to work. I replicated the problem using the hello_world example in conrod and did this on line 114 of hello_world.rs:

```
// "Hello World!" in the top left of the screen.
widget::Text::new("Hello World!")
                    .x_y(0.0, 0.0)
                    .color(conrod::color::YELLOW)
                    .font_size(32)
                    .set(ids.text, ui);
```
The result is the text still in the middle of the screen. 

[http://imgur.com/a/uyfIT](http://imgur.com/a/uyfIT)

Is this a bug in the positioning or am I misunderstanding the x_y function?

**Comment by mitchmindtree** [comment]
Thanks for the issue @georgegerdin!

In conrod, `(0.0, 0.0)` is the middle of screen so it sounds like this is working correctly. Have you tried changing the position to see what happens?

**Comment by georgegerdin** [comment]
Thank you for explanation @mitchmindtree, it makes sense now.
