### ISSUE TITLE
OpenGL 2.1 on Glium broken

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#1022]
When I tried to run Conrod after updating this morning, I was getting a FixedIndexRestartingNotSupported unwrap error.

Backtrace:
```
thread 'graphics' panicked at 'called `Result::unwrap()` on an `Err` value: FixedIndexRestartingNotSupported', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: sbc_tib::graphics::main_loop::<impl sbc_tib::graphics::Graphics>::start::{{closure}}::{{closure}}
  11: winit::platform::platform::EventsLoop::run_forever
  12: sbc_tib::graphics::main_loop::<impl sbc_tib::graphics::Graphics>::start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: <F as alloc::boxed::FnBox<A>>::call_box
  16: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
```

I have managed to find this commit that is causing the error. https://github.com/glium/glium/commit/055558965eee34b162e53069cde62eb48f0c46ec

**Comment by tl8roy** [comment]
I am fairly sure that changing `src/backend/glium.rs`: 292 to
`glium::DrawParameters { multisampling: true, blend: blend, primitive_restart_index: false, ..Default::default() }` will work. This probably needs to be changed depending on the OpenGL version used.

**Comment by tl8roy** [comment]
That is not the issue. The default is false and with it explicit, I still get the same error.

**Comment by tl8roy** [comment]
It looks like `sync_primitive_restart_index()` will fail even if `primitive_restart_index` is set to false.
@mitchmindtree You are more familiar with Glium. Is this a logic error or by design?

**Comment by tl8roy** [comment]
Fix is now merged on Glium master, but I guess we will need to wait for a point release before updating Conrod

**Comment by mitchmindtree** [comment]
Nice work!

If you submit a PR to glium for a new point release indicating that you require the fix downstream, tomaka will likely merge and publish for you (provided he's not waiting for something else to land).

**Comment by tl8roy** [comment]
The point release for Glium has occurred and Conrod has the update.
