### ISSUE TITLE
Unable to run any of the examples .

### ISSUE THREAD

**Issue by cloudcalvin** [PistonDevelopers/conrod#1035]
I truly apologize if the fault lies with me, but I am not successfully compiling the examples.

I am using ubuntu 16.04. 
rustc 16 nightly.
already tried: 
rustup update
cargo update
......

Here is the output to one of the examples. Please let me know if any further info is needed.

$ cargo run --release --features "winit glium" --example all_winit_glium --verbose
warning: unused manifest key: package.categories
       Fresh num-traits v0.1.40
       Fresh byteorder v0.4.2
       Fresh winapi-build v0.1.1
       Fresh scoped_threadpool v0.1.7
       Fresh find_folder v0.3.0
       Fresh bitflags v0.8.2
       Fresh color_quant v1.0.0
       Fresh bitflags v0.9.1
       Fresh num-integer v0.1.35
       Fresh stb_truetype v0.2.1
       Fresh log v0.3.8
       Fresh winapi v0.2.8
       Fresh linked-hash-map v0.0.10
       Fresh draw_state v0.7.1
       Fresh itoa v0.3.1
       Fresh scopeguard v0.3.2
       Fresh futures v0.1.14
       Fresh quote v0.3.15
       Fresh khronos_api v1.0.1
       Fresh cfg-if v0.1.2
       Fresh read_color v0.1.0
       Fresh inflate v0.2.0
       Fresh rustc-serialize v0.3.24
       Fresh num-iter v0.1.34
       Fresh piston-float v0.3.0
       Fresh adler32 v1.0.0
       Fresh byteorder v1.1.0
       Fresh pkg-config v0.3.9
       Fresh num-complex v0.1.40
       Fresh piston-texture v0.5.0
       Fresh vecmath v0.3.0
       Fresh shader_version v0.2.2
       Fresh fixedbitset v0.1.6
       Fresh serde v0.9.15
       Fresh piston-shaders_graphics2d v0.3.1
       Fresh piston-viewport v0.3.0
       Fresh siphasher v0.2.2
       Fresh petgraph v0.4.5
       Fresh gcc v0.3.51
       Fresh kernel32-sys v0.2.2
       Fresh enum_primitive v0.1.1
       Fresh rustc-demangle v0.1.4
       Fresh phf_shared v0.7.21
       Fresh daggy v0.5.0
       Fresh fnv v1.0.5
       Fresh lzw v0.10.0
       Fresh dtoa v0.4.1
       Fresh dbghelp-sys v0.2.0
       Fresh phf v0.7.21
       Fresh libc v0.2.28
       Fresh gif v0.9.2
       Fresh deflate v0.7.14
       Fresh smallvec v0.1.8
       Fresh unicode-xid v0.0.4
       Fresh pistoncore-input v0.18.0
       Fresh bitflags v0.7.0
       Fresh rand v0.3.16
       Fresh fs2 v0.2.5
       Fresh backtrace-sys v0.1.12
       Fresh lazy_static v0.2.8
       Fresh syn v0.10.8
       Fresh pistoncore-window v0.27.0
       Fresh png v0.7.0
       Fresh xml-rs v0.3.6
       Fresh tempfile v2.1.6
       Fresh backtrace v0.2.3
       Fresh num-bigint v0.1.40
       Fresh memmap v0.4.0
       Fresh pistoncore-event_loop v0.32.0
       Fresh synom v0.11.3
       Fresh wayland-scanner v0.7.8
       Fresh wayland-scanner v0.9.9
       Fresh x11-dl v2.14.0
       Fresh phf_generator v0.7.21
       Fresh num-rational v0.1.39
       Fresh num_cpus v1.6.2
       Fresh piston v0.32.0
       Fresh syn v0.11.11
       Fresh either v1.1.0
       Fresh odds v0.2.25
       Fresh num v0.1.40
       Fresh phf_codegen v0.7.21
       Fresh interpolation v0.1.0
       Fresh conrod_derive v0.1.0
       Fresh coco v0.1.1
       Fresh nodrop v0.1.9
       Fresh itertools v0.5.10
       Fresh piston2d-graphics v0.21.1
       Fresh xml-rs v0.6.1
       Fresh shared_library v0.1.7
       Fresh serde_json v0.9.10
       Fresh rayon-core v1.2.1
       Fresh arrayvec v0.3.23
       Fresh derivative v1.0.0
       Fresh gl_generator v0.5.5
       Fresh osmesa-sys v0.1.2
       Fresh rayon v0.8.2
       Fresh rusttype v0.2.1
       Fresh gfx_core v0.7.1
       Fresh target_build_utils v0.3.1
       Fresh jpeg-decoder v0.1.13
       Fresh gfx v0.15.1
       Fresh image v0.13.0
       Fresh gfx_gl v0.3.1
       Fresh gl v0.6.3
       Fresh piston-gfx_texture v0.23.0
       Fresh libloading v0.3.4
       Fresh gfx_device_gl v0.14.1
       Fresh piston2d-gfx_graphics v0.39.0
       Fresh dlib v0.3.1
       Fresh wayland-sys v0.9.9
       Fresh wayland-sys v0.7.8
   Compiling wayland-client v0.9.9
       Fresh wayland-client v0.7.8
     Running `rustc --crate-name wayland_client /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="dlopen"' --cfg 'feature="wayland-sys"' --cfg 'feature="egl"' --cfg 'feature="cursor"' --cfg 'feature="default"' -C metadata=0e825a18f51d9205 -C extra-filename=-0e825a18f51d9205 --out-dir /home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps -L dependency=/home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps --extern bitflags=/home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps/libbitflags-e290cd5819b8b8f3.rlib --extern libc=/home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps/liblibc-db939d1ced34b6a7.rlib --extern wayland_sys=/home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps/libwayland_sys-14822c8a78d96033.rlib --cap-lints allow`
       Fresh wayland-kbd v0.6.3
       Fresh wayland-window v0.4.4
       Fresh winit v0.5.11
       Fresh glutin v0.7.4
       Fresh gfx_window_glutin v0.15.0
       Fresh pistoncore-glutin_window v0.36.0
       Fresh piston_window v0.65.0
error: expected identifier, found keyword `trait`
   --> /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/event_queue.rs:473:51
    |
473 |     ($handler_struct: ident <$($tyarg:ident : [$($trait: ident $(<$($traitarg:ty),*>)*),*]),*>, $handler_trait: path, $handled_type: ty) => {
    |                                                   ^^^^^

error: expected identifier, found keyword `trait`
   --> /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/event_queue.rs:474:35
    |
474 |         unsafe impl<$($tyarg : $($trait $(<$($traitarg),*>)* +)* 'static),*> $crate::Handler<$handled_type> for $handler_struct<$($tyarg),*> {
    |                                   ^^^^^

error: expected identifier, found keyword `trait`
   --> /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/event_queue.rs:524:51
    |
524 |     ($handler_struct: ident <$($tyarg:ident : [$($trait: ident $(<$($traitarg:ty),*>)*),*]),*>, $handler_trait: path, $handled_type: ty) => {
    |                                                   ^^^^^

error: expected identifier, found keyword `trait`
   --> /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/event_queue.rs:525:63
    |
525 |         client_declare_handler!($handler_struct<$($tyarg: [$($trait $(<$($traitarg),*>)*),*]),*>, $handler_trait, $handled_type);
    |                                                               ^^^^^

error: expected identifier, found keyword `trait`
   --> /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/event_queue.rs:538:51
    |
538 |     ($handler_struct: ident <$($tyarg:ident : [$($trait: ident $(<$($traitarg:ty),*>)*),*]),*>, $($handler_field: ident).+ , $handler_trait: path, $handled_type: ty) => {
    |                                                   ^^^^^

error: expected identifier, found keyword `trait`
   --> /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/event_queue.rs:539:35
    |
539 |         unsafe impl<$($tyarg : $($trait $(<$($traitarg),*>)* +)* 'static),*> $crate::Handler<$handled_type> for $handler_struct<$($tyarg),*> {
    |                                   ^^^^^

error: expected identifier, found keyword `trait`
   --> /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/event_queue.rs:583:51
    |
583 |     ($handler_struct: ident <$($tyarg:ident : [$($trait: ident $(<$($traitarg:ty),*>)*),*]),*>, $($handler_field: ident).+ , $handler_trait: path, $handled_type: ty) => {
    |                                                   ^^^^^

error: expected identifier, found keyword `trait`
   --> /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/event_queue.rs:584:74
    |
584 |         client_declare_delegating_handler!($handler_struct<$($tyarg: [$($trait $(<$($traitarg),*>)*),*]),*>, $($handler_field).+, $handler_trait, $handled_type);
    |                                                                          ^^^^^

error: aborting due to 8 previous errors

error: Could not compile `wayland-client`.

Caused by:
  process didn't exit successfully: `rustc --crate-name wayland_client /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.9.9/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg feature="dlopen" --cfg feature="wayland-sys" --cfg feature="egl" --cfg feature="cursor" --cfg feature="default" -C metadata=0e825a18f51d9205 -C extra-filename=-0e825a18f51d9205 --out-dir /home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps -L dependency=/home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps --extern bitflags=/home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps/libbitflags-e290cd5819b8b8f3.rlib --extern libc=/home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps/liblibc-db939d1ced34b6a7.rlib --extern wayland_sys=/home/userd/Workspace/git-local-repos/rust-projects/conrod/target/release/deps/libwayland_sys-14822c8a78d96033.rlib --cap-lints allow` (exit code: 101)

**Comment by mitchmindtree** [comment]
Thanks for the issue!

It may be that one of the wayland dependencies causing the compilation error requires a newer version of rustc than 0.16 - could you possibly try with the latest version?

**Comment by shanehandley** [comment]
Closing due to age.
