### ISSUE TITLE
Handle winit's `Refresh` `WindowEvent`

### ISSUE THREAD

**Issue by Thomasdezeeuw** [PistonDevelopers/conrod#1036]
winit has a refresh event (https://docs.rs/winit/0.7.5/winit/enum.WindowEvent.html#variant.Refresh) which requires the window to be redrawn. It seems it's currently not handled by `convert_window_event` (https://github.com/PistonDevelopers/conrod/blob/fd10b27bd0aa50d4f483260d33b66657090acbc1/src/backend/winit.rs#L78-L158), probably  because the returned `Input` event doesn't have an variant for it. Would a pr for to add such an event to `Input` and handling it in `convert_window_event` be accepted?

**Comment by mitchmindtree** [comment]
Yeah I think this sounds fine :+1:
