### ISSUE TITLE
i3-gaps doesn't handle conrod applications exiting

### ISSUE THREAD

**Issue by SuperCuber** [PistonDevelopers/conrod#1044]
# Issue
Sometimes when I press Escape to exit [my application](https://github.com/SuperCuber/rmenu/tree/71852e1c311efd90ea5b8ad626250c7e77e15c17), all windows lose focus and stop reacting to keyboard events and i3 stops responding to shortcuts. (This also happens when the application is not fullscreen).

# Code
This issue has been happening in conrod 0.53 and in latest version.
I am using the event loop from `hello_world.rs` (and of  course had to upgrade it from 0.53 since it changed), in particular [this](https://github.com/PistonDevelopers/conrod/blob/1f44dc462a7e93af968efa607018c8389c6e10eb/examples/hello_world.rs#L48-L98).

# Environment
I am using Archlinux and i3-gaps.

# Reproducing
I cannot reproduce it with a 100% chance, but it happens on both my PC and my laptop (both running Arch and i3). When it happens I have to move the mouse to another window so that window receives focus and then i3 starts working again. If I don't have at least 2 windows open, my only solution is to switch to a tty and kill X.

I would love to see a solution so I can make progress on my application, thanks a lot.
Feel free to ask if I need to provide more information.

**Comment by mitchmindtree** [comment]
@SuperCuber thanks for the issue!

Does this issue occur with either the [glutin](https://github.com/tomaka/glutin) or [winit](https://github.com/tomaka/winit) examples?

**Comment by SuperCuber** [comment]
**Glutin** example opens a window however doesn't react at all to my shortcut to killing a window, `ctrl+c`ing the process left the window open once out of my ~10 tries, for the other everything closed properly.

**Winit** opens a window that doesnt clear its contents (switching back and forth between workspaces leaves the contents of the previous workspace) and behaves normally otherwise. Doesn't cause crashes in ~10 tries.

I think I cannot reproduce it because in my application, the issue happens only when I press Esc to exit and not when I use the window killing shortcut, however in those 2 examples I didnt use a key but the killing shortcut.

I couldn't figure how to modify winit example to also include Esc as an exit method. In the glutin example I made the following changes:
```diff
diff --git a/examples/window.rs b/examples/window.rs       
index eb5d02c6..75f5e4d7 100644                            
--- a/examples/window.rs                                   
+++ b/examples/window.rs                                   
@@ -20,7 +20,13 @@ fn main() {                             
         println!("{:?}", event);                          
         match event {                                     
             glutin::Event::WindowEvent { event, .. } => match event {                                                 
-                glutin::WindowEvent::Closed => return glutin::ControlFlow::Break,                                     
+                glutin::WindowEvent::Closed |             
+                glutin::WindowEvent::KeyboardInput {      
+                    input: glutin::KeyboardInput {        
+                        virtual_keycode: Some(glutin::VirtualKeyCode::Escape), ..                                     
+                    },                                    
+                    ..                                    
+                } => return glutin::ControlFlow::Break,   
                 glutin::WindowEvent::Resized(w, h) => gl_window.resize(w, h),                                         
                 _ => (),                                  
             },
```

And tried, escape key had no effect.

**Comment by daboross** [comment]
This is interesting, I can try and install i3-gaps on my computer to come up with a solution. I currently run plain i3 on Xorg and all glutin/conrod applications have always exited correctly both from within the application and with shift+alt+q.

**Comment by SuperCuber** [comment]
@daboross If you are running Arch you should be able to install i3-gaps and use it right away as a drop-in replacement.

**Comment by daboross** [comment]
Unfortunately not on arch at the moment, but I'll try to get it working.

**Comment by SuperCuber** [comment]
@daboross , You can overwrite i3-gaps system-wide (it should conflict with i3 and it takes the same config and puts the binary in the same place [at least on arch], so the transition should be as simple as installing it) and then install i3 in order to revert the problem

**Comment by SuperCuber** [comment]
Any progress on this?
