### ISSUE TITLE
Centered text in hello_world example lags behind window size

### ISSUE THREAD

**Issue by wkunkel** [PistonDevelopers/conrod#1046]
When resizing the window for the `hello_world` example, the position of the text lags noticeably behind where it should be for the window's current dimensions. In some cases, it takes several seconds for the text to make it to the center of the window after resizing. [Here's a video of the problem.](https://gfycat.com/responsiblefirsthandbat)

This was initially reported as part of #1042, but since this issue seems to exist even when the scaling is not broken, I've split it into its own issue.

**Comment by wkunkel** [comment]
I used `git bisect` to find that this regression was introduced in e2684251ff0afd8795db2837e8ed630c0b9720fe.

**Comment by wkunkel** [comment]
The problem is that `Resize` events are getting queued up faster than they can be processed, so they continue to be processed after the user stops resizing the window. I'm not sure exactly what the right fix is here: some sort of event debouncing?

**Comment by wkunkel** [comment]
Actually, it looks like the debouncing I was suggesting is essentially what the code was doing before it was replaced in e2684251ff0afd8795db2837e8ed630c0b9720fe. Maybe we should just revert this commit, since it seems like using `EventsLoop::run_forever()` to update the UI is always going to be broken (except maybe for unresizable windows).

**Comment by daboross** [comment]
Unfortunately, that commit also updated it from the old `glutin`/`glium` event handling to the new one, and the old example is not compatible with the latest version of `conrod`.

I'd definitely be for re-introducing a way to not do updates when lots of consecutive events happen though. Here's something I'm using in one of my `conrod` projects which somewhat mirrors the old hello world structure, but in the new version: https://github.com/daboross/screeps-rs/blob/master/conrod-ui/src/rust/events.rs. I can try and make a PR to include this or a modified version with the examples if that would fix this.

**Comment by SuperCuber** [comment]
@daboross the link is broken

**Comment by daboross** [comment]
@supercuber ah yep, my apologies - recent refactor of the crate. Updated link & pinned to specific commit to keep it alive in the future.

I'll see what I can do about merging what I have there into conrod - it ends up with the same runtime behavior of events the buffering has, but without allocating the events Vec.
