### ISSUE TITLE
Is a vulkano backend planned?

### ISSUE THREAD

**Issue by pedrocr** [PistonDevelopers/conrod#1052]
With glium development being mostly abandoned for vulkano and with hardware catching up fast it would seem the best backend going forward would be a vulkan one. Is a vulkano backend planned?

**Comment by mitchmindtree** [comment]
I'll probably get around to this eventually but don't have any immediate plans. Would be more than happy to review and help if someone beats me to it!

**Comment by Kurble** [comment]
I've been working on one for most of the day actually.. If it ends up working properly I can probably submit a pull request?
