### ISSUE TITLE
Mouse Cursor Support

### ISSUE THREAD

**Issue by elrnv** [PistonDevelopers/conrod#1063]
This is more of a question than an issue.
If I want to change the cursor based on which element is being hovered over (say the text box or divider in the file navigator). Is the caller responsible for creating custom wrapper widgets to handle these or is the plan to handle these through the windowing backends at some point?

Thanks!

**Comment by mitchmindtree** [comment]
@elrnv thanks for the issue!

I don't have any plans for this or any other backend-specific stuff (other than stuff that is essential or unambiguously removes the need for loads of boilerplate like event conversions or graphics interop) as I'm struggling to keep up with conrod maintenance as is atm! Hopefully it should be easy enough to switch mouse cursors with whatever backend users happen to be using though? I agree it would be nice if there was some way this could be done at the widget level. Let me know if you have any ideas for a backend-agnostic way of doing this nicely (e.g. perhaps some standard way of indicating a grab/drag/normal etc).

**Comment by elrnv** [comment]
Thank you for all your efforts developing and maintaining this library! I think conrod has an awesome core architecture and I'd love to see it being developed further.

## Some Justification
I think supporting mouse cursors or at least facilitate its support for user defined widgets is important. Cursors often provide a useful contextual hint to the user, allowing developers to simplify the UI sometimes. For example for the text box it's not always clear in a larger application if text is editable unless the cursor changes. Additionally for the file navigator (or any widget with sliding panes for that matter), it may be desirable to reduce the width of the divider, but to allow the user to still be able to slide the divider, we would need to change the cursor or provide a button to indicate that it's possible.

## Implementation
Unfortunately I couldn't figure out how to set the cursors easily without modifying widget code (even then I'm not sure if it's possible): Is it required for widgets to be `Copy`, `Clone` and `Debug`? The only way I can see to add setting mouse cursors is by adding a reference to a window struct (e.g. `winit::Window`) or a callback (e.g. `FnOnce(bool)`) into a widget struct. Is this possible with the current architecture?

Alternatively we could add a trait and enum like:
```rust
/// This enum specifies cursor types used by internal widgets. For custom widgets using custom
/// cursor types, you can still use this enum specifying a custom variant.
#[derive(Copy, Clone, Debug)]
pub enum MouseCursor<T: Copy + Clone + Debug> {
    Default,
    Text,
    Grab,
    Grabbing,
    ResizeVertical,
    ResizeHorizontal,
    TopLeftDownRight,
    TopRightDownLeft,
    Custom(T),
}

/// Trait implemented by the user to set the cursor appropriately.
pub trait MouseCursorSetter: Sized {

    /// Set the cursor to the specified type
    fn set_mouse_cursor(&self, cursor: MouseCursor);

    /// Resets the cursor to the default.
    fn clear_mouse_cursor(&self) {
        self.set_mouse_cursor(MouseCursor::Default);
    }
}
```

which can be implemented on the user side or in one of conrod backends to avoid the boilerplate like so:

```rust
    struct Window(winit::Window);

    impl MouseCursorSetter for Window {
        fn set_mouse_cursor(&self, cursor: MouseCursor) {
            match cursor {
                Text => self.0.set_cursor(winit::MouseCursor::EwResize),
                Grab => self.0.set_cursor(winit::MouseCursor::Grab),
                Grabbing => self.0.set_cursor(winit::MouseCursor::Grabbing),
                ResizeVertical => self.0.set_cursor(winit::MouseCursor::NsResize),
                ResizeHorizontal => self.0.set_cursor(winit::MouseCursor::EwResize),
                TopLeftDownRight => self.0.set_cursor(winit::MouseCursor::NwseResize),
                TopRightDownLeft => self.0.set_cursor(winit::MouseCursor::NeswResize),
                _ => self.0.set_cursor(winit::MouseCursor::Default),
            }
        }
    }
```

At this point I think we would need to add a reference or pointer to MouseCursorSetter in Ui or something in order to call set_mouse_cursor from within widgets.

Alternatively, in the same fashion we call `draw_if_changed` on Ui to draw primitives, we could add a call like `poll_window_state_events` or something to allow the user to handle any global window state events (like setting the mouse cursor).

Also I would be happy to implement support for mouse cursors in conrod if you are interested.

**Comment by elrnv** [comment]
Done in #1064
