### ISSUE TITLE
use of unstable library feature

### ISSUE THREAD

**Issue by rishflab** [PistonDevelopers/conrod#1070]
I followed the instructions to run the examples (git clone, cargo build ..) and cargo build is failing. It seems to be an issue with rusttype-0.2.3. I am mac osx. 

`cargo build
   Compiling num-bigint v0.1.40
   Compiling rusttype v0.2.3
   Compiling conrod_derive v0.1.0
   Compiling serde_derive_internals v0.16.0
error: use of unstable library feature 'sort_unstable' (see issue #40585)
   --> /Users/rishabintern/.cargo/registry/src/github.com-1ecc6299db9ec823/rusttype-0.2.3/src/gpu_cache.rs:270:20
    |
270 |         self.queue.sort_unstable_by_key(|&(_, ref glyph)| {
    |                    ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error(s)

error: Could not compile `rusttype`.
Build failed, waiting for other jobs to finish...
error: build failed`

**Comment by mitchmindtree** [comment]
Hey @rishflab thanks for the issue!

I just tried `cargo update` and `rustup update` to make sure my toolchain and dependencies are up to date and I was unable to reproduce this. I wonder if maybe you have an older version of rustc? Could you try `cargo update` and `rustup update` and let me know if you still have issues?

**Comment by rishflab** [comment]
Hi @mitchmindtree 

updating to rust 1.20 fixed the issue. I was on rust 1.19 earlier. 

Thanks for the quick response.

**Comment by lesebrille** [comment]
I had the same problem. And updating solved it.
