### ISSUE TITLE
How to get location of widget in list

### ISSUE THREAD

**Issue by lukors** [PistonDevelopers/conrod#1079]
I want to draw lines between widgets in two different lists to show some relationship between them. How can I get the absolute location of widgets in lists so I can draw these lines?

Been trying to figure this out, but haven't been able to. :(

**Comment by mitchmindtree** [comment]
Thanks for the issue!

You can get the absolute location of any widget using [`Ui::rect_of`](https://docs.rs/conrod/0.55.1/conrod/struct.Ui.html#method.rect_of) provided you have the `widget::Id` for that widget. When using `List` or `ListSelect`, the list item's `widget::Id` can be accessed via the yielded [`Item` type](https://docs.rs/conrod/0.55.1/conrod/widget/list/struct.Item.html#structfield.widget_id).

Hope this solves your problem! Feel free to re-open the issue if I've missed the mark :)
