### ISSUE TITLE
Unable to return `draw::Context`

### ISSUE THREAD

**Issue by simon-whitehead** [PistonDevelopers/conrod#1081]
Hi - sorry if this is not the right place.

I'm trying to add some UI elements to an existing Piston project and trying Conrod. The lack of a basic guide to explain things has really held me back.

Anyway, I'm trying to piece together the basic Piston examples in my own code and I'm currently hitting this compiler error:

```
c,
^ expected struct `conrod::backend::piston::draw::Context`, found struct `piston_window::Context`
```

This happens during this call:

```
        window.draw_2d(&e, |c, g| {
 ..........

                // Draw the conrod `render::Primitives`.
                conrod::backend::piston::draw::primitives(primitives,
                                                          c, // <------ here
                                                          g,
                                                          &mut text_texture_cache,
                                                          &mut glyph_cache,
                                                          &image_map,
                                                          cache_queued_glyphs,
                                                          texture_from_image);
```

I have been _trying_ to get this going for hours now and I simply can't see how I'm supposed to have a Conrod `Context` be the argument in this closure. Any advice would be appreciated.

Cheers,

Simon

**Comment by mitchmindtree** [comment]
Hey @simon-whitehead, thanks for the issue!

Sorry for the lack of a guide on this and integration with piston, we could definitely use some help in this area! I personally use conrod with the `winit` and `glium` features and as a result the `piston` feature tends to get a little less attention apart from what is contributed from the rest of the community.

The error you're getting sounds like it could possibly be related to mismatched versions of piston2d_graphics? If you're using you try to pass a `Context` from a version of piston_window that uses a different version of piston2d_graphics, this will cause the kind of error you're seeinng.

There's an open PR for updating piston dependencies at #1080 but I believe it's blocked on an upstream crate.

Hope this helps a bit!

**Comment by simon-whitehead** [comment]
Hi @mitchmindtree ! Thanks so much for getting back to me!

This sounds like it could be the culprit - I'll give it a shot tonight and let you know how I go. My dependencies are a bit of a mess at the moment so I'll start pinning them to specific versions and see if that helps.

You'll hear from me soon! Thanks again! 😄 

Simon

**Comment by simon-whitehead** [comment]
Hi @mitchmindtree - thanks so much, I've managed to get it working. Your suggestion of `piston2d_graphics` being a different version than what Conrod was using was correct.

I've managed to struggle through and get a clickable button happening in my existing Piston window. I just need alot more now! Thanks alot :)
