### ISSUE TITLE
Image set to widget::List's Item, will auto reset when scrolling scrollbar

### ISSUE THREAD

**Issue by alanpoon** [PistonDevelopers/conrod#1092]
![screenshot from 2017-11-12 23-58-59](https://user-images.githubusercontent.com/8205468/32700834-afe9470e-c805-11e7-8140-de3bf42bd695.png)
![screenshot from 2017-11-12 23-59-31](https://user-images.githubusercontent.com/8205468/32700838-b739b908-c805-11e7-8c44-3799169d6d51.png)
I have images from A to I listed in a row using widget::List::flow_right. I still get A to D when scrolled to the end.
When the images are smaller, almost all can be seen, but still scrolled to the end, the images will reset.
![screenshot from 2017-11-13 00-05-30](https://user-images.githubusercontent.com/8205468/32700884-82616aae-c806-11e7-9c22-a7395078edff.png)

**Comment by mitchmindtree** [comment]
Hey there @alanpoon, thanks for the issue!

By default, `List` only returns `Item`s for those items that are currently visible - it sounds like maybe you're attempting to manually track the index of each yielded `Item` to select an associated image, however this won't work as the index of each *visible* `Item` will change as the list is scrolled as you have discovered. This is the default for efficiency reasons, e.g. you often don't want to instantiate all items if working with lists of 1000s of items, like a file navigator for example.

If this is the case, there are two options that might help:

1. Use the *actual* index of the `Item` - that is, the `i` field on the `Item` type e.g. `item.i`. This should represent the item's index within the entire list, regardless of visibility.
2.  If you don't have a massive number of items in your list (which seems to be the case) this setting can be changed by calling the [`List::instantiate_all_items`](https://docs.rs/conrod/0.56.0/conrod/widget/list/struct.List.html#method.instantiate_all_items) builder method.

I hope this helps!

**Comment by alanpoon** [comment]
Thanks, I added instantiate_all_items. It works.
