### ISSUE TITLE
node graph editor,

### ISSUE THREAD

**Issue by dobkeratops** [PistonDevelopers/conrod#1117]
so I googled "conrod rust node graph editor" and find this, https://github.com/michaeljones/mango;

Would this sort of thing be within the scope of core widgets in conrod (see my other post on 'drag-drop' #1116 and context menus/(floating palettes?) which would be stages in implementing this sort of thing i.e. the drag operations in making links)

can anyone envisage a nice enough interface such that a node editor could be general purpose, or does this sound too 'domain specific' / far too complex (what are the nodes? functions? N inputs -> M outputs? what shape? how do rules for potential connections work? how do you describe the potential nodes? expansion of nodes ? would we make a trait that we literally implement for rust shared objects as a vtable ... or do we just make something which is just visual which the application will interpret and interact with in some other way?

Again, the NIH/roll-my-own urge surfaces, but I can see many of conrods existing features being useful: slider bars & other gadgets *within* the node boxes

**Comment by mitchmindtree** [comment]
Hey @dobkeratops, thanks for all these posts! I'm out of town on tour for new years but will reply to these properly when I get back. Just thought I'd quickly mention that I just recently started on a very general node-graph widget implementation that should allow for custom styling, layouts (e.g. using custom widgets for each node). You can see a little demo of this in the `graph` example. It's still missing quite a bit of functionality, but I'll be getting back to work on it within the next couple weeks as it will be an essential component in some upcoming commercial work I'm doing using conrod. There's a few more details and plans at the graph widget PR #1104.

**Comment by lf94** [comment]
This issue should be closed, since https://github.com/PistonDevelopers/conrod/pull/1104 has been merged.
