### ISSUE TITLE
Offset rendering and weird scaling on Linux

### ISSUE THREAD

**Issue by FauxFaux** [PistonDevelopers/conrod#1120]
Since 339b0c658801e02f44d3be59c24d70560e762488 ("update glium and winit"), on Ubuntu Artful (16.10) with `nvidia-384`, things render off-centre and generally pretty messed up. Here's the `image` and `file_navigator` examples:

![image](https://user-images.githubusercontent.com/328180/34652679-8149f16e-f3d9-11e7-94f4-96059acc4300.png)

Note the huge black bar, as well as the text and hover highlight not being aligned.

I assume, based on the commit, that it's a problem with `glium`, but I'm as yet unable to pin it down. I only started playing with the graphics ecosystem a few hours ago.

**Comment by daboross** [comment]
Are you using wayland or xorg? I've had different linux rendering issues with each of them in glium. I don't know anything about the issue you're having, but more information on how to reproduce it could possibly help.

**Comment by FauxFaux** [comment]
I've tried Gnome and i3; both do the same. The binary nvidia driver means no wayland, as it's blacklisted due to being crap.

As it's graphics, I don't really have a good way to narrow it down; VMs probably won't help? Not a problem with the GPU as it happens in Windows. Maybe I should dig through the `winit` commits. :(

**Comment by daboross** [comment]
Darn, ok. I've been trying out different DPI settings on my linux machine with both wayland and xorg, but to no avail - I haven't found any configuration on my machine to caused this. I'm also running Ubuntu 16.10, but with Intel integrated graphics.

**Comment by FauxFaux** [comment]
There's some progress on the gluim issue, which might be the same bug. Linked above, but clearer:

https://github.com/glium/glium/issues/1657
