### ISSUE TITLE
scroll_widget and draw_if_changed

### ISSUE THREAD

**Issue by elbaro** [PistonDevelopers/conrod#1122]
My program calls `scroll_widget` every frame, but it moves only when I move a mouse or press a key.
Shouldn't it be considered 'changed'?

```
ui.scroll_widget(ids.canvas, [1.0, 0.0]);
..
if let Some(primitives) = ui.draw_if_changed() {
..
}
```

**Comment by Kurble** [comment]
according to the docs:
`The produced Scroll event will be applied upon the next call to Ui::set_widgets`

Are you rebuilding your UI after scrolling?

**Comment by elbaro** [comment]
Yes. It was because the main loop is not running. Maybe `support::EventLoop` is a problem? (the code is modified from image_button example)

```
let mut event_loop = support::EventLoop::new();
'main: loop {
    cnt += 1;
    println!("{}", cnt); // not called
    ....
}
```

I will try without support module.

**Comment by elbaro** [comment]
The only documentation about how to set up conrod is examples, but they all use the `support` module and I still don't know the alternative.
Closing the issue because this is not a bug.
