### ISSUE TITLE
Compile Error when updating conrod_derive

### ISSUE THREAD

**Issue by callym** [PistonDevelopers/conrod#1152]
I tried to update to `conrod_derive` (using `cargo update`, and I get around 150 of the following errors.
I've tried reproducing it in an empty repo and it doesn't produce these errors, going back to 0.1.0 works fine too. I tried deleting all the cargo caches etc. and that also didn't work.

```
error[E0433]: failed to resolve. Could not find `widget` in `{{root}}`
  --> C:\Users\cally\.cargo\registry\src\github.com-1ecc6299db9ec823\conrod-0.58.0\./src\widget\xy_pad.rs:23:10
   |
23 | #[derive(WidgetCommon_)]
   |          ^^^^^^^^^^^^^ Could not find `widget` in `{{root}}`

error[E0412]: cannot find type `Theme` in the crate root
  --> C:\Users\cally\.cargo\registry\src\github.com-1ecc6299db9ec823\conrod-0.58.0\./src\widget\primitive\image.rs:35:50
   |
35 | #[derive(Copy, Clone, Debug, Default, PartialEq, WidgetStyle_)]
   |                                                  ^^^^^^^^^^^^ not found in the crate root
help: possible candidate is found in another module, you can import it into scope
   |
3  | use theme::Theme;
   |

error[E0412]: cannot find type `Theme` in the crate root
  --> C:\Users\cally\.cargo\registry\src\github.com-1ecc6299db9ec823\conrod-0.58.0\./src\widget\primitive\text.rs:29:50
   |
29 | #[derive(Copy, Clone, Debug, Default, PartialEq, WidgetStyle_)]
   |                                                  ^^^^^^^^^^^^ not found in the crate root
help: possible candidate is found in another module, you can import it into scope
   |
3  | use theme::Theme;
   |

error[E0425]: cannot find value `theme` in this scope
  --> C:\Users\cally\.cargo\registry\src\github.com-1ecc6299db9ec823\conrod-0.58.0\./src\widget\primitive\text.rs:32:24
   |
32 |     #[conrod(default = "theme.font_size_medium")]
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

**Comment by mitchmindtree** [comment]
Hey thanks for the issue!

I just tried `git clone`ing conrod and building it from scratch and I was unable to re-produce this using the latest rust nightly. Is there any chance you're finding these errors when a local clone of the conrod repo? Does the repo need to pull the latest changes from master?

**Comment by callym** [comment]
I also can't reproduce it on a fresh project, and pinning `conrod_derive = "=0.1.0"` stops the errors, so I'm not really sure what's causing it.
I've tried `cargo clean`, manually deleting my `target` folder, and the folders under `User/.cargo` in case it was a cache issue. I'm not sure how a dependency could be causing these issues either, as they're all pointing to Conrod's sources instead of anywhere in my code.
I'm not sure how to reproduce or fix it, but I'm sure it's not an issue on your end, just thought I'd bring it up here in case it was a known conflict or anything.
