### ISSUE TITLE
Image Blending

### ISSUE THREAD

**Issue by Y-o-p** [PistonDevelopers/conrod#1153]
I'm able to render textures to the screen, but is there some way to have color blending? I also want to be able to change the alpha value of the image. I tried using the `color` method implemented for `Image` in the `builder_methods!` macro which changes the `maybe_color` variable but it seems to have no effect. Is this a feature that has not yet been implemented? What exactly does `maybe_color` do?

I'm using glium to get the image data and tried searching for a function that changes the image's overall color and alpha but couldn't come up with anything.

The reason I need this is because I'm trying to create an onion skinning effect to animate with.

Any help would be appreciated.

**Comment by Y-o-p** [comment]
I'm afraid not @terhechte I switched to Qt with c++.

**Comment by terhechte** [comment]
@Y-o-p You're probably not interested anymore, I just forked conrod to add support for blend modes. Given the number of open PRs on conrod (and the subpar quality of my implementation) I doubt that this will ever make it into the codebase, but in case you do need it for whatever reason, here it is:

https://github.com/terhechte/conrod/tree/feature/blendmodes
