### ISSUE TITLE
Weird Text Rendering Issues

### ISSUE THREAD

**Issue by callym** [PistonDevelopers/conrod#1159]
I'm trying to add conrod text rendering to my gfx-based toy game engine, and it all seemed to work okay until I added some text that changed. 

At first the glyphs work fine, but after they've changed a bit, I start to get artifacts around them (https://imgur.com/a/OWJCx - top image is after it's been running for a bit, bottom is showing that it works okay when I start the exe).

My code is basically an almost-direct copy from the backend code for gfx in the repo, but for the current master branch of gfx.
I could upload it if it'd be useful, but it looks like the glyph cache is somehow not clearing space around the glyphs before updating the texture?

If I increase the glyph cache size or decrease the size of the text, the issue seems to go away, but I'm not sure if I'm just delaying the problem.

**Comment by mitchmindtree** [comment]
Hey @callym thanks for the issue!

It sounds like the glyph cache may not be large enough for the amount of different text that gets drawn in your game - perhaps you could try in creasing the dimensions and see if that works? By default the dimensions of the glyph cache are the size of the window's framebuffer at the moment at which the glyph cache is created. This is often enough, however I have exceeded it twice in my own projects so it could be worth a shot.

**Comment by callym** [comment]
I've got the size set at 512x512 for now (my window is 1024x768, and the font size is 32), the only text I'm rendering that shows the issue is coordinates, ranging from (0, 0, 0) to (15, 0, 15), the first iteration counting up works fine, when it starts counting down again is when the graphical issues appear.

It seems like somehow it's trying to redraw cached glyphs even though the data has been overwritten on the cache?

I can set the size bigger, but if it's acting strange on such a small amount of text, I'm a bit wary that it's an actual issue with my code?

**Comment by callym** [comment]
I managed to save out the cache to an image, and my code wasn't offsetting the y-coordinate of the glyphs, so it'd fill up one line of the texture then start overwriting itself again. I fixed this and everything's working properly now! Thanks for your help :)
