### ISSUE TITLE
window creation fails with `.with_multisampling(4)`

### ISSUE THREAD

**Issue by majewsky** [PistonDevelopers/conrod#1180]
This is very similar to #1018, but for me, it also occurs `.with_multisampling(4)` and even `.with_multisampling(2)`.

```
$ export WINIT_UNIX_BACKEND=x11
$ cargo run --features='winit glium' --example hello_world                 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/hello_world`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(NoAvailablePixelFormat)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm forcing winit to use x11 because of an unrelated bug in its Wayland backend.

* Conrod code is current master (49174305).
* OS is Arch Linux (i.e. latest everything).
* Desktop is Sway 0.15.2 and Xwayland 1.20.0.
* GPU is integrated in Intel Core i5-3317U (Ivy Bridge, notebook model)
* glxinfo output: https://gist.github.com/majewsky/5abe5108e28db66e05216e9f34a781c7

The example works when I comment out the `.with_multisampling(4)` call entirely.

**Comment by mitchmindtree** [comment]
Thanks for the issue!

Does the same issue occur for you when you attempt to enable multisampling in any of the glium examples? E.g. if you attempt wo add `.with_multisampling(4)` to [this part of the triangle.rs example](https://github.com/glium/glium/blob/master/examples/triangle.rs#L12)? If so, this issue might be better off there. If not, we might be doing something odd in the `glium` backend that is causing this for you. FWIW I'm also on Arch using X11 (though via Gnome) and have not ran into this.

**Comment by majewsky** [comment]
That's a good hint. The triangle example from Glium produces the same panic with multisampling. A search of the Glium issue tracker brings up https://github.com/glium/glium/issues/1677 which looks like the same issue. Closing in favor of that one.
