### ISSUE TITLE
[QUESTION] Have 3 canvas in a column, top and bottom fixed size, middle fill rest + background image behind all canvases

### ISSUE THREAD

**Issue by Abendstolz** [PistonDevelopers/conrod#1186]
First off: Sorry if I should've written in the issue I referenced. It was closed, so I felt like it would be more appropriate to add a new one:

So, I read the following issue: https://github.com/PistonDevelopers/conrod/issues/1175#issuecomment-388890332

Interestingly I am trying to create a layout like the second example (with a background image, behind all canvases) and am failing, even though there is a "guide" in there, to simply use `length` on the first and last canvas.

```
widget_ids! {
        pub struct ids {
            wrapper, top_menu_canvas, main_canvas, bottom_menu_canvas,
            background,
        }
    }
```
and then:

```
 widget::Canvas::new()
            .set(ids.wrapper, ui);

        widget::Image::new(image)
            .w_h(1920.0, 1200.0)
            .middle_of(ids.wrapper)
            .set(ids.background, ui);

        widget::Canvas::new()
            .color(conrod::color::RED)
            .mid_top_of(ids.wrapper)
            .length(200.0)
            .parent(ids.wrapper)
            .set(ids.top_menu_canvas, ui);

        widget::Canvas::new()
            .color(conrod::color::GREEN)
            .middle_of(ids.wrapper)
            .parent(ids.wrapper)
            .set(ids.main_canvas, ui);

        widget::Canvas::new()
            .color(conrod::color::BLUE)
            .mid_bottom_of(ids.wrapper)
            .length(200.0)
            .parent(ids.wrapper)
            .set(ids.bottom_menu_canvas, ui);
```

Leads to: 

![screenshot_20180708_123805](https://user-images.githubusercontent.com/26351327/42418982-0f56b85a-82ac-11e8-80c3-44c1acd75be4.png)

(So, the `bottom_menu_canvas` overlaying all the others - actually, if I use some `.alpha < 1.0` one can see that the second and third one overlay.

If I try with `h` instead of `length` I get this:

![screenshot_20180708_131357](https://user-images.githubusercontent.com/26351327/42419238-e11a2e40-82b0-11e8-86e0-c17bc3960236.png)

So, `bottom` and `top` canvases have height as I would like, but sadly the `main`-canvas doesn't fill the remainder :(

Of course if I set the `h` of the middle (green) canvas manually, like so:

```
 widget::Canvas::new()
            .set(ids.wrapper, ui);

        widget::Image::new(image)
            .w_h(1920.0, 1200.0)
            .middle_of(ids.wrapper)
            .set(ids.background, ui);

        widget::Canvas::new()
            .color(conrod::color::RED)
            .mid_top_of(ids.wrapper)
            .h(200.0)
            .parent(ids.wrapper)
            .set(ids.top_menu_canvas, ui);

        widget::Canvas::new()
            .color(conrod::color::GREEN.alpha(0.5))
            .middle_of(ids.wrapper)
            .h(800.0)
            .parent(ids.wrapper)
            .set(ids.main_canvas, ui);

        widget::Canvas::new()
            .color(conrod::color::BLUE)
            .mid_bottom_of(ids.wrapper)
            .h(200.0)
            .parent(ids.wrapper)
            .set(ids.bottom_menu_canvas, ui);
```

it looks like I want:

![screenshot_20180708_131550](https://user-images.githubusercontent.com/26351327/42419251-22d9e58c-82b1-11e8-9bd6-0152f52ac72f.png)

The downside here is, that all the heights are hardcoded, while I would like to only specify the height of the top and bottom canvas.

Funnily enough, if I use the `flow_down`-method, I can nearly get what I want:

```
  let top = widget::Canvas::new()
            .color(conrod::color::RED.alpha(1.0))
            .mid_top_of(ids.wrapper)
            .length(200.0);

        let main = widget::Canvas::new()
            .color(conrod::color::GREEN.alpha(0.5))
            .middle_of(ids.wrapper);

        let bottom = widget::Canvas::new()
            .color(conrod::color::BLUE.alpha(1.0))
            .mid_bottom_of(ids.wrapper)
            .length(200.0);

        widget::Canvas::new()
            .flow_down(&[
                (ids.top_menu_canvas, top),
                (ids.main_canvas, main),
                (ids.bottom_menu_canvas, bottom),
            ])
            .set(ids.wrapper, ui);
```

Which leads to: 

![screenshot_20180708_131836](https://user-images.githubusercontent.com/26351327/42419263-859e2ca0-82b1-11e8-9200-c6a2a2cc419c.png)

**But then** I didn't find a way to add the `background_image` in again, because:
1) I can't define it, before the `wrapper` is defined (creates a cycle) and 
2) if I add it afterwards, it overlays all the canvases, so they can't be seen.
3) if I change the `depth`, it can't be seen :(

In this example-code, the image overlays everything (so no canvases can be seen!).
Trying to set the `depth` didn't help. Either the image isn't seen at all, or it overlays everything.
```
        let top = widget::Canvas::new()
            .color(conrod::color::RED.alpha(1.0))
            .mid_top_of(ids.wrapper)
            .length(200.0);

        let main = widget::Canvas::new()
            .color(conrod::color::GREEN.alpha(0.5))
            .middle_of(ids.wrapper);

        let bottom = widget::Canvas::new()
            .color(conrod::color::BLUE.alpha(1.0))
            .mid_bottom_of(ids.wrapper)
            .length(200.0);

        widget::Canvas::new()
            .flow_down(&[
                (ids.top_menu_canvas, top),
                (ids.main_canvas, main),
                (ids.bottom_menu_canvas, bottom),
            ])
            .set(ids.wrapper, ui);

        widget::Image::new(image)
            .w_h(1920.0, 1200.0)
            .middle_of(ids.wrapper)
            //.depth(2.0) // FIXME doesn't help
            .set(ids.background, ui);
```

I am obviously missing something.

**Comment by mitchmindtree** [comment]
Thanks for the issue and providing code and lots of details!

If I understand correctly

- the background image is the size of the window and should be behind the three coloured canvases.
- the green, middle section should be semi-transparent so that the background image may be seen through it.

I think you're on the right track with using `flow_down` in order to get the "flexible height" behaviour for the green canvas.

Is it possible to position the image via `middle_of(ids.background)` instead of the wrapper canvas? Or if using the `background` widget is not suitable, perhaps another intermediary canvas could be created with the necessary size?

Another option you might be interested in is using the [crop_kids builder method](https://docs.rs/conrod/0.60.0/conrod/widget/trait.Widget.html#method.crop_kids) - this crops the view of any child widgets to the bounding rect of the widget on which the method is called. This would probably be more useful if you wanted the image *on top* of the green canvas though rather than behind it.

**Comment by DancingBard** [comment]
Thanks for the feedback @mitchmindtree !
I am not sure I can follow: In the `flow_down` example I don't have any `background`-canvas, but instead the image itself is the/called `background`.

**Comment by Finnerale** [comment]
This gave me a bit of a hard time but I managed to find the problem :)

As you want the background and your layout (`Wrapper`) in the same area I would use a `root` which hosts both.

But this alone isn't enough: by default, the `Canvas` widget has a BLACK background which is over your background image and hides it...

```rust
widget::Canvas::new()
    .set(ids.root, ui);

widget::Image::new(rust_logo)
    .parent(ids.root)
    .w_h(w as f64, h as f64)
    .middle_of(ids.root)
    .set(ids.background, ui);

let top = widget::Canvas::new()
    .color(conrod::color::RED)
    .length(200.0);

let main = widget::Canvas::new()
    .color(conrod::color::GREEN.alpha(0.5));

let bottom = widget::Canvas::new()
    .color(conrod::color::BLUE)
    .length(200.0);

widget::Canvas::new()
    .flow_down(&[
        (ids.top_menu_canvas, top),
        (ids.main_canvas, main),
        (ids.bottom_menu_canvas, bottom),
    ])
    .parent(ids.root)
    .wh_of(ids.root)
    .color(conrod::color::TRANSPARENT)
    .set(ids.wrapper, ui);
```

note the penultimate line which sets its background to transparent

**Comment by DancingBard** [comment]
@Finnerale wow, thanks a lot!
