### ISSUE TITLE
[QUESTION] Overlay/Popup -> hide until button is pressed/toggle visibility

### ISSUE THREAD

**Issue by DancingBard** [PistonDevelopers/conrod#1188]
Hey there!

What I want to achieve (In one "ui", without switching to another "screen"):

If the user clicks a button, I want to present them an overlay with additional options (so a fancy canvas with additional childs etc.)

Is it possible to hide a (floating) canvas and then show it, once the button is pressed?
It seems there is no `hide` method for a canvas and all its children.

What I tried instead was setting the position like so `.x_position(conrod::position::Position::Absolute(-screen_w_h[0]))`.
That "hides" the "overlay" canvas.

But sadly if I click the button, I can't seem to update the position of it.

Here is the code in question:
```

let top = widget::Canvas::new()
    .color(conrod::color::RED.alpha(1.0))
    .mid_top_of(ids.wrapper)
    .length(100.0);

let main = widget::Canvas::new()
    .color(conrod::color::GREEN.alpha(0.5))
    .middle_of(ids.wrapper);

let bottom = widget::Canvas::new()
    .color(conrod::color::BLUE.alpha(1.0))
    .mid_bottom_of(ids.wrapper)
    .length(100.0);

widget::Canvas::new()
    .flow_down(&[
        (ids.top_menu_canvas, top),
        (ids.main_canvas, main),
        (ids.bottom_menu_canvas, bottom),
    ])
    .color(conrod::color::WHITE)
    .set(ids.wrapper, ui);
    
let overlay_button = widget::button::Button::new()
    .label("Overlay")
    .middle_of(ids.bottom_menu_canvas)
    .w_h(100.0, 100.0)
    .set(ids.button_overlay, ui);

let overlay_wrapper = widget::Canvas::new();
    
for _click in overlay_button {
    println!("A wild overlay magically appears!");
    overlay_wrapper.x_position(conrod::position::Position::Absolute(100.0));
}
    
// Overlay
overlay_wrapper
    .color(conrod::color::BLACK)
    .floating(true)
    .x_position(conrod::position::Position::Absolute(-screen_w_h[0]))
    .set(ids.overlay_wrapper, ui);

widget::Text::new("Overlaying things since 2018")
    .color(conrod::color::LIGHT_ORANGE)
    .font_size(48)
    .mid_top_of(ids.overlay_wrapper)
    .set(ids.overlay_label, ui);
```

Any other way to achieve what I want?

**Comment by Finnerale** [comment]
Simply wrap the widgets you want to hide in an `if` statement

```rust
if overlay_visible {
    overlay_wrapper
        .color(conrod::color::BLACK)
        .floating(true)
        .set(ids.overlay_wrapper, ui);

    widget::Text::new("Overlaying things since 2018")
        .color(conrod::color::LIGHT_ORANGE)
        .font_size(48)
        .mid_top_of(ids.overlay_wrapper)
        .set(ids.overlay_label, ui);
}
```

And toggle the `overlay_visible` variable (or whatever you want to call it) to control it.
This is one of the things where Conrod shines, it will only render things as long as you tell it to do so.

**Comment by DancingBard** [comment]
@Finnerale Thanks a bunch. Totally different to what I am used to, but unless I have a few dozens `bool`s, totally managable (and then I have another problem, I guess ;))
