### ISSUE TITLE
Where is the macro hiding? (image_map!)

### ISSUE THREAD

**Issue by Abendstolz** [PistonDevelopers/conrod#1192]
Hello!

On this page: https://docs.rs/conrod/0.61.1/conrod/image/struct.Map.html it says there is a macro called `image_map!`

I couldn't find it in all of conrods source code. Am I searching wrong or is the doc outdated and misleading?

**Comment by Finnerale** [comment]
It was removed in https://github.com/PistonDevelopers/conrod/commit/17ca3b40a3349af72f9e1fea6499ea5c190066b7 
so this shoud be removed from the documentation.

Now you use it like this:
```rust
let mut image_map = conrod::image::Map::new();
let your_image_id = image_map.insert(your_image);
```

**Comment by DancingBard** [comment]
@Finnerale Thanks, I saw that in every example, was just diving through the docs and thought: "Oh, thats cool, that way I can save one lookup!"
