### ISSUE TITLE
Dial / Knob widget?

### ISSUE THREAD

**Issue by kjcole** [PistonDevelopers/conrod#1193]
I was reading your docs and didn't see an image of "number dialer". So, maybe that's the same thing as what I'm looking for.  I want something like Qt's QDial. Does such a widget exist?

Rust VERY noobie, considering whether or not I want to invest lots of time quickly, or ease slowly into learning it. Such a widget (and anything else Qt-ish) would encourage me to go with option #1 above: Learn quicker (or die trying). ;-)

**Comment by shanehandley** [comment]
Ah it is not the same as QDial. Here's a screenshot:

<img width="558" alt="dialer" src="https://user-images.githubusercontent.com/1322294/66711099-4fcf4c00-edc0-11e9-9cdb-0077ad461887.png">
