### ISSUE TITLE
Examples crash with "validate_hidpi_factor"

### ISSUE THREAD

**Issue by winks** [PistonDevelopers/conrod#1194]
Just checked out master a few minutes ago, running on Windows 7:
```
λ rustc.exe --version
rustc 1.26.0 (a77568041 2018-05-07)

λ cargo run --release --features "winit glium" --example canvas
   Compiling conrod v0.61.1 (file:///C:/Users/Flo/code/winks/inevitable/conrod)
    Finished release [optimized] target(s) in 14.83 secs
     Running `target\release\examples\canvas.exe`
thread 'main' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', C:\Users\Flo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.16.2\src\dpi.rs:273:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\release\examples\canvas.exe` (exit code: 101)

λ cargo run --release --features "winit glium" --example canvas
    Finished release [optimized] target(s) in 0.0 secs
     Running `target\release\examples\canvas.exe`
Bong!
thread '<unnamed>' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', C:\Users\Flo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.16.2\src\dpi.rs:153:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
^C
```

**Comment by mitchmindtree** [comment]
Thanks a lot for the issue @winks!

Conrod is a version behind the current version of `winit` so this could be simply a matter of updating the deps. If you're interested, you could possibly confirm this by running the [winit](https://github.com/tomaka/winit) or [glutin](https://github.com/tomaka/glutin).

**Comment by Lycowolf** [comment]
This really is an issue with winit, but it can't be fixed just in your project, because glium (another dependency) pulls the old version in, resulting in conflict. I cerated a PR https://github.com/glium/glium/pull/1711 that should hopefully fix it.

Meanwhile, you can download new version of glium, edit glium's Cargo.toml:

```
...
[dependencies.glutin]
version = "0.18"
features = []
optional = true
...
```

and your Cargo.toml:

```
winit = { version = "0.17", optional = true }
...
[dependencies.glium]
path = "src/glium"
version = "0.23.0"
optional = true
```

edit `path` to point to glutin sources.

**Comment by shanehandley** [comment]
Closing: I believe the upstream issue has been resolved.
