### ISSUE TITLE
Nothing got rendered at startup.

### ISSUE THREAD

**Issue by zengsai** [PistonDevelopers/conrod#1200]
I've tried to run example apps under examples folder, using command `cargo run --release --features="winit glium" --example counter`, but nothing got rendered at startup except a empty window.

<img width="209" alt="screen shot 2018-09-04 at 10 39 37" src="https://user-images.githubusercontent.com/163317/45007139-f6c6ad80-b02e-11e8-9b5d-8c06a263ed2a.png">

after resizing the window, every thing got rendered. I'm no sure if this is a bug,  how to fix it?

**Comment by barbeque** [comment]
I am having the same issue on the beta of Mojave (macOS 10.14) with my mid-2012 Macbook Pro (Intel/NVidia graphics switching). The `primitives`, `all_winit_glium` and `canvas` examples all experience the same symptom.

**Comment by nicmr** [comment]
Do you encounter the same issue when you try to run one of the piston backend examples instead of the winit glium ones?

**Comment by barbeque** [comment]
I don't, this example invocation worked immediately:

```bash
cargo run --release --features="piston" --example all_piston_window
```

**Comment by khanhskull** [comment]
I have the same problem as @barbeque in official release of MacOS 10.14.

**Comment by johnolos** [comment]
I can confirm that there's rendering issues with glium and Mojave, which were not present with Sierra.

**Comment by mitchmindtree** [comment]
Thanks for opening this!

I believe this has something to do with a difference in the way resize events are generated in MacOS in Mojave. This issue might be better tracked upstream [here at glutin](https://github.com/tomaka/glutin/issues/1069).

**Comment by degroote22** [comment]
Minimizing the window to the laucher and bringing it up again fixes it.

**Comment by AurevoirXavier** [comment]
If comment the code `for event in event_loop.next(&mut events_loop) { ... }` everything works well. It's a problem about **glutin event**.

**Comment by barbeque** [comment]
I can confirm on the latest version of the repo that `cargo run --release --features="winit glium" --example counter` now works properly on Mojave 10.14.3 beta.

**Comment by mitchmindtree** [comment]
Thanks @barbeque, I'll close this for now - if anyone is still hitting this after updating to the latest master feel free to re-open.
