### ISSUE TITLE
Give the possibility to easily show and hide floating canvas

### ISSUE THREAD

**Issue by LeonGGX** [PistonDevelopers/conrod#1201]
Floating canvas can be used as dialogs in a main window.
To achieve this easily, it would be interesting to have the possibility to hide and show the floating canvas after building them, with functions like _show()_ and _hide()_ and maybe with with a visual component (e.g. a "x" in the title bar)
Thanks for your great job.

**Comment by mitchmindtree** [comment]
Thanks @LeonGGX !

You're right, it would be nice to have an optional `x` for the title bar widget!

In the meantime, it should be pretty easy to show or hide the floating widgets by conditionally instantiating them in your `set_widgets` pass. E.g. if you could have a `bool` tracking whether or not to instantiate a your floating window, then you could use a button (or whatever) to set the bool to true or false depending on what you want, then only set the floating widget if your `bool` is set to true.

Hope this helps!

**Comment by LeonGGX** [comment]
It works !
Many thanks ...
