### ISSUE TITLE
Performance of ingame ui when rebuilding every frame 

### ISSUE THREAD

**Issue by ghost** [PistonDevelopers/conrod#1211]
Hey!

If I create my ui once and for every frame just do this:

```
events_loop.poll_events(|event| {
// Handle player movement etc.
            if let Some(event) = convert_event(event, window) {
                self.ui.handle_event(event);
            }
        });
```

If on the other hand I also do

```
if self.ui.global_input().events().next().is_some() {
    return self::rebuild_widgets(&mut self.ui.set_widgets(), &self.widget_ids);
}
```

every frame, my fps fall into an abyss, which somehow makes sense, being called more than 60 times per second.

If I remove that snippet, everything runs just perfect, but the ui is not responsive to anything anymore.

What is the correct way to handle this in a real world example? I understand the examples in conrod themselves just show the GUI capabilities and obviously I am doing something very wrong.

I've played around with conrod so far for menus and there it shines, but ingame my knowledge derived from the docs and examples doesn't suffice.

**So how would I go on using conrod for an ingame, performant ui, that needs to incorporate user actions and be responsive doing just that?**

(I got the basic idea from e.g. https://github.com/PistonDevelopers/conrod/blob/master/examples/all_winit_gfx.rs)

**Comment by shanehandley** [comment]
Closing: User account removed.
