### ISSUE TITLE
Need guide update.

### ISSUE THREAD

**Issue by AurevoirXavier** [PistonDevelopers/conrod#1227]
I love this GUI crate, but it's hard to learn. And the lastest guide is **conrod_hw**. 

I'm looking forward to the coming of _**Setup a Basic Window (using piston_window)**_  : )

**Comment by mitchmindtree** [comment]
Agreed!

Unfortunately I'm not going to have time for this in the foreseeable future. This awaits a champion's PR!

#505 has some related discussion.

**Comment by AurevoirXavier** [comment]
Hey~ I wrote a [simple app](https://github.com/AurevoirXavier/xmly-exporter). Could it be the demonstration app?

**Comment by shanehandley** [comment]
Duplicate #505 where some work has been done (albeit a little old)
