### ISSUE TITLE
unable to get packages from source

### ISSUE THREAD

**Issue by ghost** [PistonDevelopers/conrod#1231]
D:\Rust\conrod-master>cargo build
error: unable to get packages from source

Caused by:
  failed to download replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to parse manifest at `D:\Rust\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\stb_truetype-0.2.5\Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature

**Comment by AurevoirXavier** [comment]
试试不用 USTC 吧，我以前用那个出各种问题。

**Comment by mitchmindtree** [comment]
@lghlevel0 thanks for the issue!

It looks like we might be running into tomaka/winit#743.

Can you post the output of `cargo --version` and `rustc --version`?

Have you tried running `rustup update`?

**Comment by shanehandley** [comment]
Closing due to no reply from issue reporter.
