### ISSUE TITLE
Can't capture modifiers.

### ISSUE THREAD

**Issue by AurevoirXavier** [PistonDevelopers/conrod#1233]
I try to implement the copy/paste for the `text_box` and I found it can't capture the modifiers.
At the beginning, I think there is something wrong with my code. So I check the **select all** which was implemented for `text_edit`. And it doesn't work too.

![https://i.imgur.com/MAlRu7j.png](https://i.imgur.com/MAlRu7j.png)

**Comment by shanehandley** [comment]
I'm unable to reproduce this, so will close unless there are further reports.

Worth noting that on OSX this deviates from the usual behaviour, i.e. this requires using CTRL key as the modifier when OSX users would natively use the Command key.
