### ISSUE TITLE
How to get familiar with conrod?

### ISSUE THREAD

**Issue by Gymmasssorla** [PistonDevelopers/conrod#1246]
I am looking forward to writing GUI applications with conrod, but since I do not have any experience in computer graphics, I just can't understand the basic conrod examples (why we explicitly use renderers in ordinary GUI code, omg).

Where I should start to learn conrod? It might be some basic concepts of creating a window, instantiating the widgets, etc?

**Comment by SirTates** [comment]
The documentation doesn't appear to be at a useful state.

**Comment by 0e4ef622** [comment]
The examples, the API docs, the incomplete guide, and the source code are the only resources I know of. Although more would be nice, they provide enough information to enable a determined individual to piece together how everything works.

**Comment by Gymmasssorla** [comment]
Thanks. This issue can be closed:)
