### ISSUE TITLE
Example url seem to be broke in docs

### ISSUE THREAD

**Issue by trsh** [PistonDevelopers/conrod#1257]
https://github.com/PistonDevelopers/conrod/blob/master/examples/all_piston_window.rs

Are examples moved or removed?

**Comment by nek0gask1** [comment]
I think new all_piston_window.rs url is 
https://github.com/PistonDevelopers/conrod/blob/master/backends/conrod_piston/examples/all_piston_window.rs
(and canvas.rs is  https://github.com/PistonDevelopers/conrod/blob/master/backends/conrod_glium/examples/canvas.rs)

But I can't find all_widgets.rs

**Comment by trsh** [comment]
Thanks. But somebody should fix the links in docs https://docs.rs/conrod/latest/conrod/guide/chapter_1/index.html

**Comment by nek0gask1** [comment]
I sent pull request #1259 .
