### ISSUE TITLE
Improve algorithm to detect widget under mouse

### ISSUE THREAD

**Issue by emigr2k1** [PistonDevelopers/conrod#1293]
Right now, when having +[150;200] widgets, there's a lot of delay before the widget is highlighted when the mouse is over it. This can be seen in the canvas.rs example, at least on my machine. The result is worse when the ROWS and COLS constants are increased.

One way to optimize it, would be to divide the screen in a grid and each cell stores the widgets that are in it. Then just test the mouse point against each widget in the cell.

I might be able to do this, but would like to discuss it before.

**Comment by mitchmindtree** [comment]
Thanks for the issue!

Yes if you were to take this approach, I might recommend looking into using a [quadtree](https://en.wikipedia.org/wiki/Quadtree). Also, it might be worth doing some profiling to make sure this is indeed the bottleneck - I wouldn't be surprised if the delay was caused by something else.

**Comment by emigr2k1** [comment]
Sure. A quadtree would be good.

I'll check if where the bottleneck is.

**Comment by emigr2k1** [comment]
You're right. It looks like creating the matrix with a lot elements is what is making it slow. Sorry, it was the first time I decided to create a lot of widgets on a immediate gui.
As for the mouse cursor, it's actually pretty fast, so this can be closed. It takes
It takes ~72 ms to create a matrix with 700 cells (7*100) in debug mode. It (according to Instruments time profiler) takes 65% of total time of the app.

When I compile with release mode, it takes ~50 ms to create a matrix with 14,000 cells (7*2000) and it's usuable.

So that's it. I don't think most people need to create a lot of elements but for tables or similar, it's better to test in release mode (or maybe increase the -O level but I don't know) if there are thousands of elements. This on a macbook air 2015.

Do you have any idea on how to make it faster on user side?

**Comment by mitchmindtree** [comment]
@emigr2k1 thanks for the update!

By the way, often if I require a sufficiently complicated widget (e.g. 14000 cells), I'll implement my own `Widget` that behaves a more efficiently for my specific purpose. There's a very simple example in the glium examples I believe, but you can also see the implementations of the widgets in core to get an idea about how to go about this if you are interested enough.
