### ISSUE TITLE
broken links in docs

### ISSUE THREAD

**Issue by maxbla** [PistonDevelopers/conrod#1298]
I was reading docs here https://docs.rs/conrod/0.61.1/conrod/guide/chapter_1/index.html and noticed there are broken links in the document. They all link to examples. I'll list all the ones I find.

| (source) Line Number | Text |
|------|------|
|26|`[all_widgets.rs example](https://github.com/PistonDevelopers/conrod/blob/master/examples/all_widgets.rs).`|
|34|`**The [all_piston_window.rs example](https://github.com/PistonDevelopers/conrod/blob/master/examples/all_piston_window.rs).**`|
|38|`**The [canvas.rs example](https://github.com/PistonDevelopers/conrod/blob/master/examples/canvas.rs).**`|

It seems like these example projects all still exist. `all_piston_window.rs` for example seems to have been moved to
https://github.com/PistonDevelopers/conrod/blob/master/backends/conrod_piston/examples/all_piston_window.rs

It seems like a similar thing has happened before (https://github.com/PistonDevelopers/conrod/issues/1257) I wonder if there's some CI thing that could easily be done to make sure issues like this are brought to light immediately.

I would be happy to submit a PR.

**Comment by mitchmindtree** [comment]
Thanks for opening this, I'd be happy to merge a PR for this!

**Comment by maxbla** [comment]
It seems like the links are correct in the master branch of this repo, but not on that website that I looked at. This problem might be fixed by publishing a new version.

**Comment by ChiefMilesEdgeworth** [comment]
The examples folder does not exist on master anymore. Should these links be removed, or should they point somewhere else?

**Comment by mitchmindtree** [comment]
Thanks for the heads up @ChiefMilesEdgeworth! They now live within their associated backends. E.g. `backends/conrod_glium/examples`. From memory, the glium backend has the most examples, but each backend should have at least one reference example. Unfortunately the guide has not received any love in quite a while, I'd be happy to merge a PR with addressing these broken links.

**Comment by ChiefMilesEdgeworth** [comment]
Sure, I'll try to put something together. Anything I can do to help push forward Rust GUIs

**Comment by ChiefMilesEdgeworth** [comment]
I'm having trouble finding where I can edit the docs. Is it in the repository code, or somewhere else?

**Comment by ChiefMilesEdgeworth** [comment]
Ok, so I found it, but I'm not sure which example I should link to. Should I make a couple of links to each backend folder? Or is there a particular example that we should use?

**Comment by alvinhochun** [comment]
The now correctly-linked guide has the proper links to the examples.
