### ISSUE TITLE
Allow querying if redraw_count is above 0 in Ui

### ISSUE THREAD

**Issue by worktycho** [PistonDevelopers/conrod#1320]
It would be useful to allow applications to query if draw_if_changed would return Some, to allow integration with winit's request redraw function. For some applications this allows a blocking event loop rather than continuous polling more effectively.

**Comment by worktycho** [comment]
I would be happy to submit a PR for this.

**Comment by mitchmindtree** [comment]
Sure, I'd be happy to accept a PR for this!
