### ISSUE TITLE
SFML

### ISSUE THREAD

**Issue by DoctorVWA** [PistonDevelopers/conrod#1322]
Is it possible to use conrod with SFML?

If yes, how? 

If not, do you have plans for a SFML backend?

**Comment by theRippedPug** [comment]
If you want something with the simplicity of sfml, use ggez or the actual bindings. (If that’s what you’re asking for)

**Comment by DoctorVWA** [comment]
Actually not, I need to implement a GUI system in SFML, and I was looking for some crates to see if there's compatibility with sfml rendering, I have looked into imgui too, but nothing, I asked there too and no response actually, belive I gonna close both issues and do my own class for creating the GUIs, thanks for an answer. :)
