### ISSUE TITLE
features is not allowed in the root of a virtual workspace

### ISSUE THREAD

**Issue by JulienPerrin** [PistonDevelopers/conrod#1330]
In the doc (https://docs.rs/conrod/0.61.1/conrod/guide/chapter_2/index.html#running-the-conrod-examples) it is said that we should use the argument --features to run the example, but it does not work : 

```
PS C:\Programmation\conrod> cargo run --release --features "winit glium" --example text

error: --features is not allowed in the root of a virtual workspace
```
edit : wrong error

Removing `--feature "winit glium"` allow me to run the example text without issues. 
The doc is not clear about how to solve this issue though.

**Comment by mitchmindtree** [comment]
Thanks @JulienPerrin, the guide is long overdue for an update. PR #1223 is responsible for removing features in favour of a dedicated crate for each backend. A PR to update the guide for these changes would be greatly appreciated!

**Comment by JulienPerrin** [comment]
It seems somebody already fixed this issue : 
https://github.com/PistonDevelopers/conrod/commit/79125676036f54154dd354ffc9da1d764b309ca4#diff-f08a79558e4d4c63cc224a71a14237c6

I will close this issue. 
Thanks for your answer.
