### ISSUE TITLE
Q: What do "Scalar"s represent?

### ISSUE THREAD

**Issue by frabert** [PistonDevelopers/conrod#1342]
I'm implementing a new backend, and I'm confused by the meaning of this paragraph (https://docs.rs/conrod/0.61.1/conrod/event/enum.Input.html):

> All co-ordinates and dimensions must be given as `Scalar` (DPI agnostic) values.

What does this mean? Do scalar coordinates go from -1 to 1? If I have a windows 800x600 pixels wide (assuming no hi-dpi), what are its extreme coordinates? (-400, -300) (400, 300), or (-1, -1) (1,1)?

**Comment by mitchmindtree** [comment]
Thanks for the issue!

A `Scalar` in conrod refers to the logical (DPI-agnostic) pixel coordinates of the window, where the minimum bounds are in the bottom left, and the upper bounds are in the top right. So regarding your example with an 800x600 window, the bottom left corner would be `[-400, -300]` and the top right would be `[400, 300]`.

**Comment by mitchmindtree** [comment]
Also I'm very sorry for the lack of documentation on implementing custom backends (and in general)! Hopefully the existing collection of backends and the `all_widgets_*.rs` example is enough to get by for now.

**Comment by frabert** [comment]
Thanks! Yes I've found that browsing through the "reference" implementation is quite sufficient.
