### ISSUE TITLE
"Getting Started" website doc issue running examples

### ISSUE THREAD

**Issue by louhy** [PistonDevelopers/conrod#1345]
Looks like probably some outdated website documentation here: 
https://docs.rs/conrod/0.61.1/conrod/guide/chapter_2/index.html

> cargo run --release --features "winit glium" --example all_winit_glium
> cargo run --release --features "winit glium" --example canvas
> cargo run --release --features "winit glium" --example primitives
> cargo run --release --features "winit glium" --example text

```
~/git/conrod$ cargo run --release --features "winit glium" --example all_winit_glium
error: --features is not allowed in the root of a virtual workspace
note: while this was previously accepted, it didn't actually do anything
```

Removing the --features "winit glium" prevents the error. 

Note - on Linux Mint I also had to install three packages: 
libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

**Comment by saoirse-zee** [comment]
I hit what I believe to be the same issue. 

This command:
```
cargo run --release --features "winit glium" --example all_winit_glium
```

Results in this error:
```
error: --features is not allowed in the root of a virtual workspace
note: while this was previously accepted, it didn't actually do anything
```

I ran it without `--features` and it worked (with some warnings):
```
cargo run --release --example all_winit_glium 
```

**Comment by alvinhochun** [comment]
The now correctly-linked guide does not have this issue anymore.
