### ISSUE TITLE
cargo run examples failed

### ISSUE THREAD

**Issue by llbook** [PistonDevelopers/conrod#1356]
>cargo run --release "winit glium" --example all_winit_glium
error: a bin target must be available for `cargo run`

I'm running win8.1

Also, you should point out upfront out that you need cmake, ninja and python3.
(I'm 100% new to rust, but conrod seems very promising to me.)

Thanks!

**Comment by Tauheed-Elahee** [comment]
It is also a problem on Debian testing GNU/Linux.

**Comment by alvinhochun** [comment]
You don't need any of cmake, ninja or python to just run the `glium` examples.

Anyway, the now correctly-linked guide has the right command `cargo run --release --example all_winit_glium`, so I believe this can be closed.
