### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by pedrohex** [PistonDevelopers/conrod#1357]
@iMac conrod % cargo run --release --features "winit glium" --example all_winit_glium
error: --features is not allowed in the root of a virtual workspace
note: while this was previously accepted, it didn't actually do anything

**Comment by josh65536** [comment]
Just remove the `--features "winit glium"` flag. As the note says, it didn't do anything.

**Comment by mitchmindtree** [comment]
Thanks for the issue! For better or worse, the examples have since been moved into the specific backends, and the `features` flag should no longer be required. To run the an example associated with one of the backends, you should be able to do so with something like:
```
cargo run --release -p conrod_<backend> --example <example_name>
```
E.g.
```
cargo run --release -p conrod_glium --example all_winit_glium
```
Also, I'd be more than happy to merge a PR that updates the guide for this!

**Comment by smallB007** [comment]
Hi, I've tried to run the example: cargo run --release -p conrod_glium --example all_winit_glium
I'm getting:
/usr/bin/ld: cannot find -lxcb-shape
 /usr/bin/ld: cannot find -lxcb-render
/usr/bin/ld: cannot find -lxcb-xfixes
Any ideas what to do about it?
Thanks

**Comment by seerickcode** [comment]
> /usr/bin/ld: cannot find -lxcb-shape
> /usr/bin/ld: cannot find -lxcb-render
> /usr/bin/ld: cannot find -lxcb-xfixes
> Any ideas what to do about it?

Same problem, google got me here.  
Linux (Ubuntu 20.04) solution
`sudo apt-get install libx11-xcb-dev libxcb-xfixes0-dev libxcb-render0-dev libxcb-shape0-dev`

Should be fairly equivalent for other distros/package systems.  You need the related development versions of the C libraries on the system.   Only tried with conrod_glium for the all_winit_glium and text examples.

**Comment by smallB007** [comment]
> > /usr/bin/ld: cannot find -lxcb-shape
> > /usr/bin/ld: cannot find -lxcb-render
> > /usr/bin/ld: cannot find -lxcb-xfixes
> > Any ideas what to do about it?
> 
> Same problem, google got me here.
> Linux (Ubuntu 20.04) solution
> `sudo apt-get install libx11-xcb-dev libxcb-xfixes0-dev libxcb-render0-dev libxcb-shape0-dev`
> 
> Should be fairly equivalent for other distros/package systems. You need the related development versions of the C libraries on the system. Only tried with conrod_glium for the all_winit_glium and text examples.

Sorry for the late reply and thanks.
Best regards

**Comment by gnusiva** [comment]
This command runs the application for me
```cargo run --example all_winit_glium```

**Comment by alvinhochun** [comment]
The now correctly-linked guide does not mention the `--features` flag, so I believe this can be closed.
