### ISSUE TITLE
Consider dealing with `conrod` crate on crates.io and docs.rs

### ISSUE THREAD

**Issue by alvinhochun** [PistonDevelopers/conrod#1364]
https://crates.io/crates/conrod shows the latest version as "0.61.1" last updated "2 years ago", which is obviously not right. Nothing in there indicates that it has been moved to `conrod_core` and other crates and has been updated beyond that, yet it is the very first item that's shown when searching for "conrod" on crates.io. Same for docs.rs - when using a search engine, one or more of the old docs.rs pages is bound to show up.

Something needs to be done about these leftover crates. It would've been fine if the core kept the name `conrod`, but now would be too late to rename `conrod_core` back to `conrod`. Can you at least push a dummy crate to redirect people to `conrod_core`?

**Comment by mitchmindtree** [comment]
Thanks for the reminder to address this!

I've [pushed a branch](https://github.com/mitchmindtree/conrod/tree/conrod_redirect) containing a [dummy `conrod` crate](https://github.com/mitchmindtree/conrod/tree/conrod_redirect/conrod). The crate is an empty library with redirect links to the `conrod-core` crate in the description, readme and crate root docs. Unfortunately I no longer appear to be able to `cargo publish` the crate:

```
[mindtree@mindtree conrod]$ cargo publish
    Updating crates.io index
   Packaging conrod v0.62.0 (/home/mindtree/programming/rust/conrod/conrod)
   Verifying conrod v0.62.0 (/home/mindtree/programming/rust/conrod/conrod)
   Compiling conrod v0.62.0 (/home/mindtree/programming/rust/conrod/target/package/conrod-0.62.0)
    Finished dev [unoptimized + debuginfo] target(s) in 3.80s
   Uploading conrod v0.62.0 (/home/mindtree/programming/rust/conrod/conrod)
error: api errors (status 200 OK): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

I'm not sure why I've lost publish access to the crate, I think it might be related to the recent event where crates.io was required to invalidate a lot of existing tokens so perhaps the pistondevelopers:publish team token is no longer valid or something along these lines?

@bvssvni would you mind fetching my `conrod_redirect` branch linked above, `cd` into the `conrod` sub-directory containing the dummy conrod crate and running `cargo publish`? It would be a great help!

**Comment by bvssvni** [comment]
@mitchmindtree I've sent you an invite to the `conrod` crate.

**Comment by bvssvni** [comment]
@mitchmindtree I also added you to `pistondevelopers:publish`. If I remember correctly, then we changed the permissions to minimum number of people with publish access. However, since the image-rs organization took over the image crates, there have been no security incidents and this organization seems much a less target.

A side note: The `conrod_crate` is currently only owned by you, which blocks potential backups. Can you add `pistondevelopers:publish`?

**Comment by mitchmindtree** [comment]
Thanks @bvssvni!

`conrod` 0.62.1 has now been published and the crates.io and docs.rs entries now refer to `conrod_core`.

> A side note: The conrod_crate is currently only owned by you, which blocks potential backups. Can you add pistondevelopers:publish?

Of course! I have now added `github:pistondevelopers:publish` as cargo owners to each of the crates within the conrod repo :+1:
