### ISSUE TITLE
cargo build fails '(failed to run custom build command for 'shaderc-sys v0.6.2)

### ISSUE THREAD

**Issue by RogerPickering** [PistonDevelopers/conrod#1392]
This occurs on running cargo build --release
Prior to the error, there was also a warning: System installed library not found. Falling back to build from source

**Comment by alvinhochun** [comment]
If you are trying to run the examples, use the following steps instead of the ones in the linked guide (it is currently outdated).


> ## Running the Conrod Examples
> You can view the examples by cloning the github repository and running the examples.
> First, open up the command line on your system and follow these steps:
> 1. Clone the repo
>   ```txt
>   git clone https://github.com/PistonDevelopers/conrod.git
>   ```
> 2. Change to the `conrod` directory that we just cloned
>   ```txt
>   cd conrod
>   ```
> 3. Build and run an example (with --release optimisations turned on)!
>   ```txt
>   cargo run --release --example all_winit_glium
>   cargo run --release --example canvas
>   cargo run --release --example primitives
>   cargo run --release --example text
>   ```
>   Hint: You can get a list of all available examples by running:
>   ```txt
>   cargo run --example
>   ```

Next time when opening an issue, please at least mention what OS you are on and provide the full build output.

**Comment by RogerPickering** [comment]
Thanks very much for this quick response Alvin. I have to confess that this is all entirely new to me. My initial goal was to learn Rust, but I released almost immediately that a lot of work is needed to produce any kind of GUI output. 
That's the reason I started looking at conrod and found myself in a world of cargo, crates and github without knowing anything about them at all.
But at least now the hello_world program compiles and produces very acceptable output.
So, thank you for the excellent support.

By the way, I'm not in general a complete amateur, having worked for 40 years in IT in jobs ranging from programmer to IT director, but things have moved on a bit since the 1970's.
Regards,Roger
    On Saturday, 3 October 2020, 12:02:56 CEST, alvinhochun <notifications@github.com> wrote:  
 
 


If you are trying to run the examples, use the following steps instead of the ones in the linked guide (it is currently outdated).


Running the Conrod Examples

You can view the examples by cloning the github repository and running the examples.
First, open up the command line on your system and follow these steps:
   
   - Clone the repo
git clone https://github.com/PistonDevelopers/conrod.git
   
   - Change to the conrod directory that we just cloned
cd conrod
   
   - Build and run an example (with --release optimisations turned on)!
cargo run --release --example all_winit_glium
cargo run --release --example canvas
cargo run --release --example primitives
cargo run --release --example text

Hint: You can get a list of all available examples by running:
cargo run --example


Next time when opening an issue, please at least mention what OS you are on and provide the full build output.

**Comment by alvinhochun** [comment]
> Thanks very much for this quick response Alvin. I have to confess that this is all entirely new to me. My initial goal was to learn Rust, but I released almost immediately that a lot of work is needed to produce any kind of GUI output.  That's the reason I started looking at conrod and found myself in a world of cargo, crates and github without knowing anything about them at all. But at least now the hello_world program compiles and produces very acceptable output. So, thank you for the excellent support.
> 
> By the way, I'm not in general a complete amateur, having worked for 40 years in IT in jobs ranging from programmer to IT director, but things have moved on a bit since the 1970's.

I understand. The `shaderc-sys` issue is quite common because it does not build on Windows without some manual preparation. It is not required at all to run most of the examples, yet the guide called for `cargo build` which needlessly builds everything. The guide in the latest source has been updated to remove that, but it is not in the published guide since a new release has not yet been made. So it's not really your fault when you are just following the published docs.

However, in general you should provide a bit more of the basic information when creating issues. Not providing them usually results in others having to ask for them before being able to really start to diagnose the issue. This wastes time and can sometimes agitate people. Not every issues are as straightforward as this one.

Anyway, good luck for your journey through Rust. I would like to advice you that the Rust GUI situation is really immature and there are lots of rough edges, but don't be discouraged when you hit any obstacles.

**Comment by RogerPickering** [comment]
Thanks Alvin. I understood that there is quite some way to go for GUI functions, but not how far that really means.Anyway, that's a good step forward for me.Will try to do better if I have to request help again.
    On Saturday, 3 October 2020, 14:57:45 CEST, alvinhochun <notifications@github.com> wrote:  
 
 



Thanks very much for this quick response Alvin. I have to confess that this is all entirely new to me. My initial goal was to learn Rust, but I released almost immediately that a lot of work is needed to produce any kind of GUI output. That's the reason I started looking at conrod and found myself in a world of cargo, crates and github without knowing anything about them at all. But at least now the hello_world program compiles and produces very acceptable output. So, thank you for the excellent support.

By the way, I'm not in general a complete amateur, having worked for 40 years in IT in jobs ranging from programmer to IT director, but things have moved on a bit since the 1970's.


I understand. The shaderc-sys issue is quite common because it does not build on Windows without some manual preparation. It is not required at all to run most of the examples, yet the guide called for cargo build which needlessly builds everything. The guide in the latest source has been updated to remove that, but it is not in the published guide since a new release has not yet been made. So it's not really your fault when you are just following the published docs.

However, in general you should provide a bit more of the basic information when creating issues. Not providing them usually results in others having to ask for them before being able to really start to diagnose the issue. This wastes time and can sometimes agitate people. Not every issues are as straightforward as this one.

Anyway, good luck for your journey through Rust. I would like to advice you that the Rust GUI situation is really immature and there are lots of rough edges, but don't be discouraged when you hit any obstacles.
