### ISSUE TITLE
widget::id::List` is not an iterator    also widget::id::ListWalk is not an iterator

### ISSUE THREAD

**Issue by MrGibus** [PistonDevelopers/conrod#1396]
Trying to create ids for a variable number of items for the circles 7guis benchmark [here](https://eugenkiss.github.io/7guis/tasks/)
I've come across [this example](https://docs.rs/conrod_core/0.71.0/conrod_core/macro.widget_ids.html) and [this issue](https://github.com/PistonDevelopers/conrod/issues/826). Both indicate using list ids. But its throwing and error telling me that it's not an iterator.

`    ids.toggles.resize(5, &mut ui.widget_id_generator());  
    for id in ids.toggles {  
        widget::Toggle::new(true).set(id, ui);  
    }
`

I've also tried 

`    ids.toggles.resize(5, &mut ui.widget_id_generator());  
    for id in ids.toggles.walk() {  
        widget::Toggle::new(true).set(id, ui);  
    }
`

Is this not meant to be an iterator?

**Comment by alvinhochun** [comment]
It is probably outdated. The widget id lists are [`conrod_core::widget::id::List`](https://docs.rs/conrod_core/0.71.0/conrod_core/widget/id/struct.List.html), which derefs to a slice, so you would probably need:

```rust
for id in ids.toggles.iter() {
    // ...
}
```

**Comment by MrGibus** [comment]
Thank you.
using `.iter()` and `.set(*id, ui)`, works as i'd expect.
