### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by Raj2032** [PistonDevelopers/conrod#1453]
Is the project still alive?

**Comment by acz2022** [comment]
I highly doubt it. Just look at the last commit date. It was over one month ago... That may not seem like a long time, but for project in active development a month without a commit is a very, very long time.

**Comment by Raj2032** [comment]
@acz2022 Yeah its a shame, thought it I would use it.

**Comment by mitchmindtree** [comment]
Thanks for the issue - I just opened #1454 with some info and alternative recommendations.
