### ISSUE TITLE
Work with arbitrary contexts

### ISSUE THREAD

**Issue by aepsil0n** [PistonDevelopers/conrod#150]
I've been toying around with conrod to label moving graphics objects (I would like to extend that to interactive UI elements, too). A major problem that I find with the current API is, that conrod creates its own absolute contexts rather than accepting them as an argument. This way I end up duplicating the transformation logic for the UI elements, which in my current use case is doable, but may end up messy, once the transformation hierarchy becomes a bit more complicated.

I am not sure whether doing something like this is an intended use case of conrod. However, I guess that with some refactoring, it would be possible to achieve this kind of flexibility. Although I am not familiar enough with conrod's internals to really judge that.

**Comment by mitchmindtree** [comment]
I'm pretty sure this can be done now, as `Ui::draw` now takes a `&Context`. Gonna close :+1:
