### ISSUE TITLE
Support for multiple fonts

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#182]
How should we support multiple fonts?

**Comment by cybergeek94** [comment]
What about a call on `UiContext` that sets a temporary font to use on next text draw only? And then it goes back to the old font after that draw. Something like `.next_draw_font(&mut GlyphCache)` or `.temp_font(&mut GlyphCache).`

Or only store the font in `UiContext` as the default font, and then all the widget builders that draw text borrow `GlyphCache` from the context. Then you could replace the borrowed reference with a separate `&mut GlyphCache` with a setter. And when you finally call `.draw()` the builder passes the font back into `UiContext::draw_text()` to tell it which font to use.

**Comment by bvssvni** [comment]
What about `Rc<GlyphCache>` and call `.make_unique()` when using it? It will only have one reference so it will be mutable...

Then, one could swap out the `Rc` with another temporary and put it back afterwards.

**Comment by cybergeek94** [comment]
`Rc::make_unique()` requires an impl of `Clone` which `GlyphCache` does not currently have. Creating a whole separate `FT_Face` instance plus all its buffers would increase memory usage drastically, unless `Clone` would make both instances of `GlyphCache` refer to the same `FT_Face` object underneath, at which point you're inviting potential race conditions without a mutex. And all that is wasted if you drop the modified instance when you swap it out.

Passing an `&mut GlyphCache` to the widget builder seems most sane to me. If the user chains or nests their draw calls properly, they should be able to use the same `GlyphCache` instance in every widget within their render loop.

**Comment by mitchmindtree** [comment]
This has been implemented for a while now, closing.
