### ISSUE TITLE
doesn't build on windows.

### ISSUE THREAD

**Issue by blairn** [PistonDevelopers/conrod#189]
using the latest nightly.

C:\Users\blair\conrod>cargo build --verbose
       Fresh read_color v0.0.1 (https://github.com/PistonDevelopers/read_color#c563f9f0)
       Fresh shader_version v0.0.0 (https://github.com/pistondevelopers/shader_version#32364088)
       Fresh gl_common v0.0.1 (https://github.com/bjz/gl-rs#41fa9cb1)
   Compiling time v0.1.0 (https://github.com/rust-lang/time#afab521f)
       Fresh khronos_api v0.0.2 (https://github.com/bjz/gl-rs#41fa9cb1)
       Fresh rust-xml v0.1.2-pre (https://github.com/netvl/rust-xml#2d9df326)
       Fresh image v0.2.0-alpha.2 (https://github.com/pistondevelopers/image#a48cd66d)
       Fresh freetype-rs v0.0.0 (https://github.com/PistonDevelopers/freetype-rs.git#3f014f4a)
       Fresh current v0.0.0 (https://github.com/PistonDevelopers/current#ad63ba6a)
       Fresh vecmath v0.0.0 (https://github.com/PistonDevelopers/vecmath.git#f6fc0102)
       Fresh texture v0.0.0 (https://github.com/pistondevelopers/texture#65e7bbd5)
       Fresh input v0.0.0 (https://github.com/PistonDevelopers/input/#fb351501)
     Running build.rs
       Fresh gl_generator v0.0.1 (https://github.com/bjz/gl-rs#41fa9cb1)
       Fresh graphics v0.0.0 (https://github.com/PistonDevelopers/graphics.git#3434c661)
   Compiling gl v0.0.1 (https://github.com/bjz/gl-rs#41fa9cb1)
     Running `rustc src\gl\lib.rs --crate-name gl --crate-type lib -g -C metadata=bb78cdc3bae0f4e0 -C extra-filename=-bb
78cdc3bae0f4e0 --out-dir C:\Users\blair\conrod\target\deps --dep-info C:\Users\blair\conrod\target\.fingerprint\gl-bb78c
dc3bae0f4e0\dep-lib-gl -L C:\Users\blair\conrod\target\deps -L C:\Users\blair\conrod\target\deps --extern gl_generator=C
:\Users\blair\conrod\target\deps/gl_generator-14b70861eb330221.dll`
Build failed, waiting for other jobs to finish...
Failed to run custom build command for `time v0.1.0 (https://github.com/rust-lang/time#afab521f)`
Could not execute process `build.rs` (status=never executed)

Caused by:
  file not found (OS Error 2: The system cannot find the file specified.
)

**Comment by mitchmindtree** [comment]
Closing as this is about 1.5yrs old and probably solved long ago.
