### ISSUE TITLE
Add "disabled" state for widgets that accept input

### ISSUE THREAD

**Issue by cybergeek94** [PistonDevelopers/conrod#205]
Proposition: `.disabled()` modifier or an `.enabled(bool)` setter that makes the widget ignore all input when disabled. Additional modifiers for making the disabled state clear to the user (e.g. greyed out and permanently-depressed state of disabled buttons) might be a good idea, though that can be set manually by the caller.

Chiefly useful for:

* Button
    * When the action that the button is supposed to do is not available, e.g. disabling "Previous Page" button for a paginated element when on page one.
* Slider
    * Can double as a progress-bar if the user can't modify it. Works currently if the slider is updated quickly enough but it really should just be able to reject user input.
* TextBox
    * Sometimes better than a Label: looks better in some contexts, can also have UI elements positioned relative to it
* Toggle
    * When toggling the element would leave the program in an invalid state.

The ability to disable elements that accept input is ubiquitous amongst UI libraries. On the upside, the most basic functionality seems trivial to implement. I might issue a PR for this shortly myself.

**Comment by mitchmindtree** [comment]
This is addressed by #429.
