### ISSUE TITLE
Make `widget_matrix` scrollable

### ISSUE THREAD

**Issue by cybergeek94** [PistonDevelopers/conrod#207]
I'm having a hard time thinking of how to describe it, but I think `widget_matrix` could be made scrollable by having two sets of dimensions and then moving it under a static mask:

 ![](http://imgur.com/WEAfHZl.png)

It could save processing power by culling items that don't fall at least partially within the visible area, and then mask the edges so they don't bleed over. A separate UI element (slider, perhaps?) could control the scroll, setting the scroll amount on the matrix in terms of % or current out of maximum. This method could also trivially be implemented for horizontal scrolling.

**Comment by mitchmindtree** [comment]
This should be possible now as all conrod widgets support scrolling their children widgets. I think the neatest way to do this might be to instantiate a scrollable `Canvas` widget as the parent (aka "container") of a `WidgetMatrix`.
