### ISSUE TITLE
Positioning relative to window edges

### ISSUE THREAD

**Issue by cybergeek94** [PistonDevelopers/conrod#208]
The ability to position elements relative to each other is useful, but it would also be nice to be able to position elements relative to the window edges, with padding. Initially I thought that's what these methods did:

```rust
fn down(self, padding: f64) -> Self;
fn up(self, padding: f64) -> Self;
fn left(self, padding: f64) -> Self;
fn right(self, padding: f64) -> Self;
```

But they position elements relative to the last created element instead.

Being able to center elements horizontally/vertically within the window would be nice as well. It should take the elements' size into account so it's not just their origin point that's centered.

**Comment by mitchmindtree** [comment]
This has been implemented as of #385, see the [`Positionable` trait](https://github.com/PistonDevelopers/conrod/blob/master/src/position.rs#L97) for all of the new options for widget and canvas layout.
