### ISSUE TITLE
data flow and gui

### ISSUE THREAD

**Issue by gedw99** [PistonDevelopers/conrod#216]
wondering if there anyone knows of a data flow rust crate ?

for GUI aspects it makes it much easier to have data flow. 
Makes responsive layout easier
Allows rapid development

**Comment by bvssvni** [comment]
I think this falls out of the scope of the project for the moment.

**Comment by cybergeek94** [comment]
RIP the inbox of anyone watching this repo tonight.

**Comment by bvssvni** [comment]
:laughing:
