### ISSUE TITLE
Using borderless windows for drop down lists

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#217]
This is an alternative to defer the rendering or do some kind of clipping.

**Comment by mitchmindtree** [comment]
The `DropDownList` has been doing something similar to this for a little while now: It creates a small floating `Rectangle` widget which becomes a cropped, scrolling parent surface for each button in the list.

Going to close this for now as clipping and depth ordering have both been solved for a while :+1:
