### ISSUE TITLE
Get default font size for labelled widgets from `Theme`

### ISSUE THREAD

**Issue by cybergeek94** [PistonDevelopers/conrod#218]
All the labelable widgets are created with a magical font size of 24. This default should be configurable, perhaps `Theme::medium_font_size`.

However, this kind of throws a spanner in the works for #212 since we need access to the `Theme` instance.

Most widgets could use `Option<FontSize>` instead, so if one's not explicitly set then we grab the default from `Theme` on-draw, where I assume we would pass `UiContext` after #212.

Alternately, we could separate `Theme` from `UiContext` and use *it* to bootstrap the builders instead. Could pull a lot of useful data from there for defaults, e.g. font size, color schemes, etc. `GlyphCache` could be tied to the `Theme` as well, so we can have different fonts for each widget. :)

CC @bvssvni

**Comment by mitchmindtree** [comment]
Closed by #385
