### ISSUE TITLE
Add `prelude` module for easy bootstraping with glob imports

### ISSUE THREAD

**Issue by cybergeek94** [PistonDevelopers/conrod#226]
Conrod currently requires some ugly boilerplate code to bootstrap even the simplest window. The first 46 lines of the `all_widgets` demo is *imports alone*:

```rust
extern crate shader_version;
extern crate event;
extern crate conrod;
extern crate graphics;
extern crate sdl2_window;
extern crate opengl_graphics;
extern crate vecmath;
extern crate current;
use conrod::{
    Background,
    Button,
    Callable,
    Color,
    Colorable,
    Drawable,
    DropDownList,
    EnvelopeEditor,
    Frameable,
    Label,
    Labelable,
    NumberDialer,
    Point,
    Positionable,
    Slider,
    Shapeable,
    TextBox,
    Theme,
    Toggle,
    UiContext,
    WidgetMatrix,
    XYPad,
};
use opengl_graphics::Gl;
use opengl_graphics::glyph_cache::GlyphCache;
use event::{
    WindowSettings,
    Events,
    Event,
    Ups,
    MaxFps,
};
use sdl2_window::Sdl2Window;
use vecmath::vec2_add;
use std::cell::RefCell;
use current::Set;
```
Only a few of these imports are specific to the demo (required by its logic). That is a lot of boilerplate, and appears quite daunting.

I propose we boil this down to something like:

```rust
#![feature(glob)]
extern crate conrod;
extern crate sdl2_window;
extern crate vecmath;

use conrod::prelude::*;

use sdl2_window::Sdl2Window;
use vecmath::vec2_add;
use std::cell::RefCell;
```

Where `pub mod prelude` defines the following re-exports:
```rust
pub use super::*;

pub use opengl_graphics::Gl; // `as GlBackend`
pub use opengl_graphics::OpenGL; // Already reexported from `shader_version`.
pub use opengl_graphics::glyph_cache::GlyphCache; // `as Font`?

pub use event::{
    WindowSettings,
    Events,
    Event,
    Ups,
    MaxFps,
};

pub use current::Set;
```

I'm already glob-importing `conrod` in my code to start with all the widget traits; it might be slightly polluting but it saves me from having to add an import for each widget as I decide what to add to my UI, which I only remember to do after getting a compiler error due to the missing import.

This, combined with a builder-pattern for creating windows based on some useful defaults, could cut bootstrapping a UI down from several dozen LOC to just a handful. Which is great, especially for when you might have to bootstrap a UI in multiple modules within a crate.

See the UI prelude I created for my GUI branch of `img-dup`: https://github.com/cybergeek94/img_dup/blob/gui/src/ui/mod.rs#L28

**Comment by bvssvni** [comment]
A few improvements has been made:

* The "piston" repo now reexports the core libraries, thereby getting rid of `extern crate event;`, `extern crate window;`, `extern crate input;` and `extern crate quack;`
* `opengl_graphics` reexports `shader_version::OpenGL`, thereby getting rid of `extern crate shader_version`

**Comment by bvssvni** [comment]
This is outdated. I think we should improve the imports but this needs new investigation.
