### ISSUE TITLE
Started new design - label example

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#254]
I created a branch "newdesign" because I figured out it will be easier to make it back-end agnostic by redesigning it first. The new design uses the "quack" library.

```Rust
    // Current design
    uic.label("Widget Demonstration")
        .position(demo.title_padding, 30.0)
        .size(48u32)
        .color(demo.bg_color.plain_contrast())
        .draw(gl);

    // New design
    Label::new("Widget Demonstration")
        .set(Position([demo.title_padding, 30.0]))
        .set(FontSize(48u32))
        .set(demo.bg_color.plain_contrast())
        .draw(uic, gl);
```

Notice that `UiContext` is moved to the `draw` method. This makes it easier to maintain the code because the generic parameters of `UiContext` doesn't have to be tracked through the entire API.

**Comment by bvssvni** [comment]
An idea is to also put the id in the `draw` method for other widgets. Perhaps the callback too?

The formal semantics is does not include `id` or `callback` as part of the function of the widget. See https://github.com/PistonDevelopers/conrod/issues/223

**Comment by bvssvni** [comment]
I think that `UiContext` could have a `graphics::Context` passed in to its constructor to support arbitrary transformations, but keep widgets in the same space. It would use the view transform to translate input into the widget coordinates.

The widgets could have an optional relative or absolute `graphics::Context`. Perhaps a `draw_transformed` method?

**Comment by mitchmindtree** [comment]
@bvssvni exciting to see a start on this :) Looking forward to how it rolls out! I just have a few thoughts that have sprung to mind:

Out of curiosity, is the "quack" library needed for this? It seems almost like one extra layer of indirection. For example, perhaps we could do this instead:

```Rust
Label::new("Widget Demonstration")
        .position(demo.title_padding, 30.0)
        .size(48u32)
        .color(demo.bg_color.plain_contrast())
        .draw(uic, gl);
```

which would be less code for the user, less changes to make to the library and less names to import for the user. Though perhaps there are other benefits of the modifier design that I do not yet understand?

> Notice that UiContext is moved to the draw method. This makes it easier to maintain the code because the generic parameters of UiContext doesn't have to be tracked through the entire API.

Would tracking the generic parameters still be an issue using associated types?

> The widgets could have an optional relative or absolute graphics::Context. Perhaps a draw_transformed method? I think only a matrix is necessary, since UiContext knows the view transform.

Perhaps another optional builder method before draw is called? Something like `.transform(..)` (perhaps that's what you meant when you mentioned `draw_transformed` :)

> An idea is to also put the id in the draw method for other widgets. Perhaps the callback too?

At the moment the callback itself doesn't get evaluated until `.draw` is called (primarily because both callback and draw require many of the same calculations) so I *think* I think it should be fine to just pass the ID and uic to `draw` exclusively.

I have to go now for a bit but I have some more ideas for handling widget overlap etc that I most post as another issue later :)

**Comment by bvssvni** [comment]
The quack library gives you both `.get`, `.set` and `.set_mut` and it makes it possible to auto implement traits based on the properties alone. For example, by using `Transform` from piston-graphics you can use the `RelativeTransform` trait. We could lift the existing traits over the properties to get the same interface as before.

**Comment by bvssvni** [comment]
@mitchmindtree I've written an explanation of duck typing here https://github.com/PistonDevelopers/quack/issues/10

**Comment by bvssvni** [comment]
@mitchmindtree Associated types does not make it easier to track generic constraints for concrete types, and for more than one trait you have to write extra code to make the constraints match each other. For example, you have to make the associated `Texture` type of `CharacterCache` match the associated `Texture` type of `BackEnd`. Eventually it got too complicated for the compiler. This might be solved in the future with equality constraints.

**Comment by mitchmindtree** [comment]
@bvssvni

re associated types: ahhh yes, that makes sense :)

re quack library: thanks for the link! I've read through the benefits of quack (somehow I hadn't made the connection between duck-typing and quack previously haha) and I've also been keeping track of your changes on the new-design branch. I really like the idea behind the quack library, but I have to say I'm still unsure whether I see the benefits of its usage within conrod. I'll list some of my thoughts alongside each of the advantages you mentioned in your link below: 

> Imported types have the same name as way methods are called

This is certainly nice for explicitness, though it does also require extra names compared to traits who may encompass several methods (i.e. `Positionable` might have `.xy(x, y)`, `.down(pixels)` `.right(pixels)`, etc).

> Extra type safety

I'm not sure I understand how it is more type safe?

> Traits can be auto implemented on top of it

Can you give me an example of this? It sounds useful, but I don't understand how it works differently from normal trait implementations?

> It requires less naming

Similarly to your first point, I'm not sure this has been the case for the `all_widgets` example so far?

> It reduces the number of traits in the library

Certainly, however the trade-off seems to be having a type instead for every method?
 
> It gives a consistent API across libraries

I can understand this is the case for those using all-piston libraries, however all of the additional `.set`s and the duck-typing style in general seems like a slightly strange, unnecessary addition next to libraries and code that do not use it or are not related (though this is just my experience).

> Improvement to the "quack" library leads to overall improvement across libraries

Sure, but only if it adds utility in the first place.

> Renaming causes less breaking changes

How? If one renames a type, that seems as much work as renaming the name of a method?

> Adding new methods is possible without breaking the library interface

This is the same with trait methods, no?

> It gives you builder methods through by value set or mutable reference set_mut.

This is a clever benefit, though mutable reference seems a little redundant in our case where we already use by-value (as in conrod)? 
```Rust
x.set_mut(Setting(y));
x = x.set(Setting(y));
x = x.setting(y);
```

Overall re quack, my current concerns are that the extra crate and additional code for users (i.e. there are 10 extra `.set()`s in the new dropdownlist example) may outweigh the benefits of the added genericness that in most cases will likely go unused?

Btw I like the change of moving the uic to the draw method! I'm curious as to why you moved the callback into an argument as well? It seems strange that all other optional widget attributes would use the builder pattern but not the callback?

**Comment by bvssvni** [comment]
@mitchmindtree Are you IRC?

**Comment by bvssvni** [comment]
I'll close this since we'll use both quack and traits for now.
