### ISSUE TITLE
Issue using XY pad

### ISSUE THREAD

**Issue by maurizi** [PistonDevelopers/conrod#278]
I tried stripping down the `all_widgets.rs` example into just an XY pad and the circle it controls, and the XY pad does not show up.

Code is here https://github.com/maurizi/monito-rs/blob/bf3d5862c430b5d235dd6e27a8b2c5bc791d246c/src/main.rs

**Comment by cakecatz** [comment]
`down()` is add padding between self and before widgets, but you don't have other widgets before XY pad.
So if you want show XY pad , should remove `.down(225.0)`.

**Comment by maurizi** [comment]
That did it, thank you!
