### ISSUE TITLE
Unbox the callback closures

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#301]
As far as I can tell, it seems the callback closures were boxed as a sort of quick-fix during rustc's transition from boxed to unboxed closures. Please let me know if this is wrong and there's some other reason they are boxed, otherwise I'll start the change-over now :)

**Comment by mitchmindtree** [comment]
It might be best to wait for [the `quack!` macro to support where clauses](https://github.com/PistonDevelopers/quack/issues/30) otherwise we'll require code that will just be removed once it is implemented anyway, and this isn't immediately important.

**Comment by bvssvni** [comment]
The `quack!` macro now supports where clauses.
