### ISSUE TITLE
Upgrade to latest Rust

### ISSUE THREAD

**Issue by zummenix** [PistonDevelopers/conrod#310]
Upgrade `conrod` and `all_widgets.rs` to latest Rust.

**Comment by zummenix** [comment]
I'm stuck with this error:
```
src/envelope_editor.rs:402:32: 402:45 error: type annotations required: cannot resolve
`<<E as envelope_editor::EnvelopePoint>::X as core::ops::Sub>::Output == <E as
envelope_editor::EnvelopePoint>::X` [E0284]
```
I don't know maybe https://github.com/rust-lang/rust/issues/22036 is relevant.

**Comment by zummenix** [comment]
Possible solution is to add dummy function:
```rust
fn dummy_sub<T: Float>(max: T, min: T) -> T {
    max - min
}
```

**Comment by mitchmindtree** [comment]
Thanks for this, I've been running into a few strange errors with assoc types like this, hopefully things will clear up over the next couple weeks :)

I've added your suggestion as a temp fix with a note in src, will PR and merge it in a minute.
