### ISSUE TITLE
Change example over to glutin/glium backend

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#312]
@bvssvni @tomaka  is this doable at the moment? It would be nice to drop the SDL2 installation requirement :)

**Comment by alexchandel** [comment]
Conrod is a good place to showcase glutin.

**Comment by bvssvni** [comment]
Good idea. Should be doable!

**Comment by mitchmindtree** [comment]
Ok, I've got glutin compiling with the all_widgets example however the window is completely unresponsive and starts beach-balling after about a second or two. All the widgets and everything seem to render fine (for at least a frame) before it hangs. I'll try with a basic-as-possible example and see if it still occurs.

**Comment by mitchmindtree** [comment]
Hmmm, I'm getting the same behaviour even with just the following code:

```Rust

extern crate conrod;
extern crate glutin_window;
extern crate opengl_graphics;
extern crate piston;

use conrod::{
    Theme,
    UiContext,
};
use glutin_window::GlutinWindow;
use opengl_graphics::{Gl, OpenGL};
use opengl_graphics::glyph_cache::GlyphCache;
use piston::event::{
    Event,
    Events,
    Ups,
    MaxFps,
};
use piston::Set;
use piston::window::WindowSettings;
use std::cell::RefCell;

fn main () {

    let opengl = OpenGL::_3_2;
    let window = GlutinWindow::new(
        opengl,
        WindowSettings {
            title: "Hello Conrod".to_string(),
            size: [1180, 580],
            fullscreen: false,
            exit_on_esc: true,
            samples: 4,
        }
    );
    let window_ref = RefCell::new(window);
    let event_iter = Events::new(&window_ref).set(Ups(180)).set(MaxFps(60));
    let mut gl = Gl::new(opengl);
    let font_path = Path::new("./assets/NotoSans/NotoSans-Regular.ttf");
    let theme = Theme::default();
    let glyph_cache = GlyphCache::new(&font_path).unwrap();
    let uic = &mut UiContext::new(glyph_cache, theme);

    for event in event_iter {
        if let Event::Render(_) = event { println!("test") }
    }

    println!("Exited successfully!");
}

```

If I remove the event iterator and loop, then the app exits successfully, so it must occur when polling the events of glutin. I'm on OS X 10.10.2, with the latest nightly build `rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-19)`

**Comment by mitchmindtree** [comment]
All conrod's example now use glutin - closing this.
