### ISSUE TITLE
Create a generic UiEvent trait

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#322]
This would allow users who don't happen to be using piston to easily use conrod with different game engines - they would only need to implement `UiEvent` for their game event type. [This line](https://github.com/PistonDevelopers/conrod/blob/master/src/ui_context.rs#L72) would then take a `E: UiEvent` instead.

**Comment by bvssvni** [comment]
Piston is supposed to be the abstraction layer toward back-ends.

I recommend one of the two options:

* Implement `GenericEvent` from piston-event
* Map the events to `piston::event::Event`

**Comment by bvssvni** [comment]
One idea is to add `UiEvent`, but auto implement `GenericEvent` over it, and continue use `E: GenericEvent`. Since Conrod is only reading events, it can ignore the construction of events from arguments.

**Comment by bvssvni** [comment]
I don't think we should go this route now. Closing.
