### ISSUE TITLE
Backspace returns wrong code?

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/conrod#327]
When I press backspace:
![backspace](https://cloud.githubusercontent.com/assets/1174908/6318925/173f3e06-baba-11e4-97c3-ce6c370fc39b.png)
On sdl2_window all works.

**Comment by mitchmindtree** [comment]
Hmmm glutin must return a different char for backspace for different operating systems. I had to add [this](https://github.com/PistonDevelopers/glutin_window/blob/master/src/lib.rs#L88) to glutin_window to stop that from happening on osx for backspace and return. Perhaps you can find out what the char is and filter it out as well?

**Comment by mitchmindtree** [comment]
If you can, maybe it is worth testing all your other keys to see if they behave normally while you're at it :)
