### ISSUE TITLE
Enter shifts input box.

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/conrod#328]
If I press enter in end of line, then all ok.
But if I press enter in beginning of line or middle of line, then input box shifted to here, editing still work, but cursor can't move in beginning of line. Removing and returning focus on this input field restores normal position.
I tested on linux.

**Comment by mitchmindtree** [comment]
Wweeeiiirrddd. Does enter emit a `char` that we might have missed when filtering them out? Not sure how it would happen otherwise

**Comment by Potpourri** [comment]
You can reproduce it?
I have the same behavior on sdl2_window

**Comment by mitchmindtree** [comment]
Ahh yes I can, nice job on spotting that, definitely a textbox bug :+1:

**Comment by Potpourri** [comment]
This is fixed by #345
