### ISSUE TITLE
TextBox wishlist

### ISSUE THREAD

**Issue by dcampbell24** [PistonDevelopers/conrod#342]
The textbox widget is currently very simple and would be a lot more useful if it supported a set of features that would allow it to be used in a basic chat server. Major features that would be nice to have include:
- multi-line
- read only
- highlight / copy and paste
- Input Method Editor support

I am guessing adding support for the first two should be fairly straight-forward, but the last two may not be. The read only feature is related to #341 since it means updating the text box programatically is an error.

**Comment by mitchmindtree** [comment]
Related #71, #62

**Comment by mitchmindtree** [comment]
Agreed on this, TextBox is certainly a WIP and could use some love :smile: 

Highlight copy/paste would be a great next feature (once the bugs are addressed heh)! As for multi-line functionality, perhaps we could separate that into a `TextArea` widget? I remember thinking this might be a good idea, but I've forgotten why.

Anyway, I'm planning on starting a synth editor repo soon that will have me diving back into conrod, so I should be able to help out soon :+1:

**Comment by davekong** [comment]
OK, great! I'm working on a networked Hearts game and building out the client GUI right now. I am going to spend a little putting together the table display, then come back to these issues to get chat working.

**Comment by davekong** [comment]
Related #205

**Comment by LaylConway** [comment]
When I get to adding copypaste functionality to phosphorus, I'll make the cross platform functions for interaction with the clipboard available as a crate so it can be used in conrod.

**Comment by bvssvni** [comment]
@LaylConway That would be useful!

**Comment by jdm** [comment]
With regards to the clipboard, please see https://github.com/aweinstock314/rust-clipboard/ .

**Comment by mitchmindtree** [comment]
@jdm thanks, looks good!

**Comment by psFried** [comment]
I'd like to add another feature to this discussion. What about the ability to tab between TextBoxes? 

@mitchmindtree to your earlier point about having a separate TextArea widget, I think this is one of the differences. A TextBox would be suited for quickly entering small amounts of text into many small TextBoxes, so you would want to be able to quickly tab between them. A TextArea would be more like a mini text editor. IMO, you wouldn't want tab/enter to automatically move you to the next input field when you're in a TextArea, you'd want it to insert a literal tab/newline character.

**Comment by andresv** [comment]
What about setting text color, there are `color` and `frame_color` : http://docs.piston.rs/conrod/conrod/struct.TextBox.html, but nothing for `text_color`.
I can see that there is also [TextBoxStyle](http://docs.piston.rs/conrod/conrod/struct.TextBoxStyle.html), however `TextBox` does not have public constructor that takes `style`. Some other widgets has `styled` method that can be used for this. For example `rectangle` has it: http://docs.piston.rs/conrod/conrod/struct.Rectangle.html

**Comment by mitchmindtree** [comment]
I'm going to close this as most of this has since been implemented:

The `Text` widget allows for multi-line, read-only text supporting left, centre and right justification along with options for wrapping by word, character or not at all.

`TextEdit` is basically a wrapper around `Text` that allows for mutation and text selection.

`TextBox` has been updated to use `TextEdit` internally, and is basically a constrained version of the `TextEdit` on top of a `BorderedRectangle`.

Remaining features discussed here that are not yet satisfied can be added to the pre-existing #71.

**Comment by io12** [comment]
Copy/paste support is still unimplemented.
