### ISSUE TITLE
elm-lang's Element / Form UI Framework.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#344]
In my spare time I've been working on a small game using elm-lang and one thing I've noticed is how incredibly easy it is to "collage" together graphical elements to create complex shapes or widgets - it has me thinking a lot about how we could improve Conrod's widget-building foundations.

I'm going to have a go at porting Elm's Graphics.Collage and Graphics.Form modules into Rust to see what I learn and perhaps even come up with something handy in the end.

**Comment by bvssvni** [comment]
That's exciting!

**Comment by mitchmindtree** [comment]
I've started [the crate here](https://github.com/mitchmindtree/elmesque) (still needs lots of work before experimenting).

**Comment by mitchmindtree** [comment]
Closed by #385
