### ISSUE TITLE
re-use more of graphics

### ISSUE THREAD

**Issue by dcampbell24** [PistonDevelopers/conrod#347]
I was looking over the piston graphics library and it seems like conrod overlaps with it a fair amount and might be able to reuse or wrap more types from graphics than it currently does. I am wondering if there plans to tie conrod closer together with graphics?

Some thoughts:
* Make better use of graphics::Rectangle so conrod can draw round and bezel corners.
* Unify Dimensions / Point with  graphics::internal::rectangle and consolidate bounding box / rectangle math
* Replace Shapeable with AddRectangle and RelRectangle.
* Unify color handling logic and the concept of something having a color.
* Look for other traits that exist in the two libraries that express basically the same thing and see if they can be unified.

The goal is to have less types and more functions so conrod can be simpler and get more for free from graphics.

**Comment by bvssvni** [comment]
`RelRectangle` is now called `Rectangled` in piston-graphics.

**Comment by bvssvni** [comment]
Maybe we even can move some of text logic into piston-graphics, since that's useful outside Conrod.

**Comment by mitchmindtree** [comment]
This sounds great!

I think the idea behind Shapeable was to handle both elliptic and rectangular widgets (for widgets like buttons, toggles, etc), but I never got around to implementing any elliptic options.

More generally, conrod still doesn't offer a good solution for allowing users to define their own kinds of widgets at all. I'm hoping to do some experiments on this over the next couple days inspired by Elm's approach to graphics and UI. I'm picturing their being some `Widget` type that can either be some `BasicWidget` or a collection of other `Widget`s (similar to Elm's compose-able `Form` concept, though I'm still unsure of how this will interact with dynamic user interaction).

Oh and speaking of colouring - during porting across some of Elm's functionality, I noticed they have an excellent colour module that also supports [HSLA](http://en.wikipedia.org/wiki/HSL_and_HSV) (kind of like a colour-wheel for cycling through colours) and gradients. Here's the [ported module](https://github.com/mitchmindtree/elmesque/blob/master/src/color.rs).

@bvssvni I love the idea of moving the text logic into it's own crate :+1:

I'll report back on my elmesque UI experiments soon (#344 is related).

**Comment by davekong** [comment]
This issue is related to https://github.com/PistonDevelopers/graphics/issues/882.

**Comment by mitchmindtree** [comment]
Closed by #385
