### ISSUE TITLE
Make `Positionable` inherit `Shapeable`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#354]
The only widget that has position but no size is `Label`.

**Comment by bvssvni** [comment]
I see some alternatives:

1. Assume that the size of the label is zero
2. Compute the size it uses
3. Add a size to the label
4. Add an optional size the label, which becomes either 1) or 2) when not specified

**Comment by davekong** [comment]
I think having the size of the label is pretty useful. For example, I have a table (WidgetMatrix) and want to place a label above it. Based on #219 it sounds like 4 is a desirable choice with fallback to 2.

**Comment by mitchmindtree** [comment]
Closed by #385
