### ISSUE TITLE
Something strange with position and size of a drawable area of a window.

### ISSUE THREAD

**Issue by zummenix** [PistonDevelopers/conrod#363]
Current `all_widgets.rs` looks like:
![untitled](https://cloud.githubusercontent.com/assets/3009258/7051842/74da5944-de44-11e4-8bff-904c04f00656.png)

**Comment by Potpourri** [comment]
Weird... For me works fine. It was works for you before, you something change in latest time?

**Comment by zummenix** [comment]
I think it was broken after `glutin_window` dependency.

**Comment by zummenix** [comment]
Issue related to Retina display because on non Retina mac examples look fine.

**Comment by bvssvni** [comment]
It could be that draw size should be used when computing the absolute transform in `Context`.

**Comment by bvssvni** [comment]
The `draw` method needs both the viewport settings and draw size settings.

**Comment by bvssvni** [comment]
In order to keep the window and graphics API decoupled, we could add a `viewport` library that was shared between the window and graphics back-ends, so you could do:

```Rust
gl.draw(args.viewport, |c, g| { ... });
```

**Comment by bvssvni** [comment]
@zummenix Try `cargo update` and see if it's right or wrong now.

**Comment by zummenix** [comment]
@bvssvni Now it looks like:
![untitled](https://cloud.githubusercontent.com/assets/3009258/7101652/c8548c54-e07c-11e4-9012-98fdc5859870.png)

**Comment by zummenix** [comment]
I also noticed artefacts around glyphs.

**Comment by bvssvni** [comment]
@zummenix Can you try override piston-graphics with `~/.cargo/config` and change this https://github.com/PistonDevelopers/graphics/blob/master/src/context.rs#L56-L59

It might be working by swapping the order of multiplication.

**Comment by bvssvni** [comment]
Here is how you override a dependency locally https://github.com/PistonDevelopers/piston/issues/482

**Comment by zummenix** [comment]
Ok, I will try now.

**Comment by zummenix** [comment]
mat = `[[0.000847, 0, -1], [0, -0.001724, 1]]`
I've changed to this:
```rust
let mat = multiply(
    scale(sx, sy),
    abs_transform(viewport.draw_size[0] as f64, viewport.draw_size[1] as f64)
);
```
mat = `[[0.000847, 0, -0.5], [0, -0.001724, 0.5]]`

Nothing changed in all_widgets.rs.

**Comment by bvssvni** [comment]
@zummenix Can you try invert the `sx` and `sy` and see what happens?

**Comment by bvssvni** [comment]
Ah. The reason it has no effect might be that Conrod doesn't use the transform from `Context` in many places.

**Comment by zummenix** [comment]
@bvssvni Nothing happens.

**Comment by bvssvni** [comment]
@zummenix I suspect the reason is that Conrod calls `Context::abs` instead of using the context provided from the graphics back-end.

**Comment by bvssvni** [comment]
I did some testing on my computer and nothing happens when I try to simulate the problem.

**Comment by bvssvni** [comment]
@zummenix Can you try running the "user_input" example in the piston-examples repo? It should show a red rectangle and a blue rectangle. A black dot should show the cursor position within the red rectangle. In your case, the blue rectangle should be greater than the red one.

**Comment by zummenix** [comment]
@bvssvni That is what I see:
![untitled](https://cloud.githubusercontent.com/assets/3009258/7102153/536c3e90-e091-11e4-8707-010a2fa5f0ab.png)
Cursor position only matches in one place – where dot is on screenshot.

**Comment by zummenix** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3009258/7102224/1337ba6e-e093-11e4-9d51-99053452bc24.png)
On this screenshot cursor position is upper left corner of the window.

**Comment by bvssvni** [comment]
@zummenix I figured "user_input" doesn't call `Context::new_viewport`. Need to update the example.

**Comment by bvssvni** [comment]
@zummenix I've updated the "user_input" example. Can you try again?

**Comment by zummenix** [comment]
@bvssvni That is what I see:
![untitled](https://cloud.githubusercontent.com/assets/3009258/7102674/2ba084b0-e0a1-11e4-8449-f1d0514b5373.png)
If I change this line:
https://github.com/PistonDevelopers/opengl_graphics/blob/29317965a88bfa4e70794076d6a84f5462947b75/src/gl_back_end.rs#L262 to:
```rust
self.viewport(x, y + h, w + w, -h);
```
I can place squares at upper left corner of the window but cursor position doesn't match

**Comment by bvssvni** [comment]
The rectangles should be much larger.

**Comment by zummenix** [comment]
@bvssvni https://github.com/PistonDevelopers/graphics/blob/c4d8ac644817b6a0853f594cbf0df6e276853843/src/context.rs#L54-L55
Currently sx, sy are 0.5 for me. I think need to swap operands to get 2.0

I will be online tomorrow.

**Comment by bvssvni** [comment]
@zummenix I've updated piston-graphics.

**Comment by zummenix** [comment]
@bvssvni Now the size of squares seems right, but position is wrong.

**Comment by mitchmindtree** [comment]
I also run into the same issue on my mbp retina, it definitely looks like there's been an improvement since last time I tested though! Originally I used to get the exact same issue as in @zummenix's [first comment](https://github.com/PistonDevelopers/conrod/issues/363#issue-67186809), however now I get this:

![screen shot 2015-04-12 at 6 17 00 pm](https://cloud.githubusercontent.com/assets/4587373/7104874/2a39be08-e140-11e4-9230-1c73cbf3af8e.png)

Also, I get slightly different behaviour again if I drag the window from my regular display onto my retina display. This is what it looks like after being dragged onto the retina display:

![screen shot 2015-04-12 at 6 07 52 pm](https://cloud.githubusercontent.com/assets/4587373/7104863/ea10d622-e13f-11e4-8020-f7d8cd941953.png)

Hopefully these help to hint towards the issue slightly - would love to see this fixed :)

**Comment by bvssvni** [comment]
It might be an issue with Glutin on OSX. Perhaps worth changing example to use piston_window and test with SDL2/GLFW/Glutin.

**Comment by zummenix** [comment]
Sprite example uses SDL2 – looks ok on retina.

**Comment by mitchmindtree** [comment]
Back when conrod used to use SDL2 in the all_widgets example it used to work fine for me on my retina display also.

**Comment by bvssvni** [comment]
I've made the piston_window back-end agnostic with respect to the window back-end. It is hard for me to know what the exact problem is because I can't test it here. Conrod still needs to setup the absolute transform correctly, so we'll work through the issues one by one and post more information on https://github.com/tomaka/glutin/issues/287 when we know more.

**Comment by mitchmindtree** [comment]
@zummenix this should now be fixed by [this PR](https://github.com/PistonDevelopers/glutin_window/pull/29) to glutin_window.

I'm going to close this now but feel free to reopen and let me know if you continue to run into issues

**Comment by zummenix** [comment]
@mitchmindtree Yes this is fixed now :thumbsup:
