### ISSUE TITLE
Use `Context` from top level to solve Retina problem

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#367]
See https://github.com/PistonDevelopers/conrod/issues/363

Currently the code sets up a `Context` with `Context::abs`. It should be using `Context::new_viewport` which is normally computed from `RenderArgs::viewport`. This new setup of context should ensure the coordinates is in the upper left corner in points (this might need some fixing).

Anyway, we should not call `Context::abs` but pass the transform around in some way, perhaps using `Ui`.

**Comment by mitchmindtree** [comment]
An alternative would be to pass it in via the `.draw` methods, but I guess this would be more boilerplate for the user.

**Comment by mitchmindtree** [comment]
Turns out we just had to apply the hidpi to the `draw_size` method instead of `size` (and in turn also apply it tot he cursor position). Closing this for now, if anyone still has issues feel free to reopen.

Closed by [this PR](https://github.com/PistonDevelopers/glutin_window/pull/29).
