### ISSUE TITLE
Add some anchoring helper functions

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#370]
Anchoring edges to edges of a parent widget. This means you can make one widget stick to the lower right corner, or resize it horizontally but not vertically. Each edge has an anchor `bool`:

```Rust
pub struct Anchor {
    pub left: bool,
    pub right: bool,
    pub up: bool,
    pub down: bool
}
```

**Comment by bvssvni** [comment]
This could be bitflags.

**Comment by bvssvni** [comment]
Might not be needed if elmesque does anchoring.

**Comment by zummenix** [comment]
In my practice always simpler to arrange components manually by changing `frame` property.

**Comment by mitchmindtree** [comment]
This is now handled amongst conrod's various [Positionable trait](http://docs.piston.rs/conrod/conrod/trait.Positionable.html) methods.
