### ISSUE TITLE
Mix immediate mode/retained mode/custom widgets

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#371]
We need to make sure that you can use custom widgets or retained ones together with immediate mode. Thoughts?

**Comment by mitchmindtree** [comment]
Perhaps we could expose a `Custom(Box<CustomWidget>)` variant of the Widget enum, where `CustomWidget` is a trait with all methods necessary to implement for a widget? I've been thinking about this also.

**Comment by mitchmindtree** [comment]
A year on, and this is now the case for conrod. We use an immediate-mode API wrapping a retained widget graph :smile_cat:  See [this section](http://docs.piston.rs/conrod/conrod/guide/chapter_1/index.html#is-conrod-immediate-or-retained) of the guide.
