### ISSUE TITLE
Defer "draw" until end of the render cycle

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#372]
At the moment the "draw" stage is heavily intertwined with the "input -> callback" stage. The benefits of untangling them into two distinct stages are as follows:
- Draw only needs to be called on the `Ui` at the end of the cycle (after widget construction), i.e. `ui.draw(graphics, glyph_cache)`
- As a result we could properly handle draw ordering (i.e. we'll be able to draw open DropDownList's last).

Rather than calling `.draw(graphics)` at the end of each widget's construction, the `.callback(..)` method would indicate that the widget construction is complete and store the necessary drawing information in the `Ui` (In the case that the widget doesn't have a callback, we could include a `.set()` method which would indicate the same thing).

The necessary drawing information to store for each widget would simply be a graphics Context (just a collection of Lines/Rectangles in most cases).

**Comment by bvssvni** [comment]
A graphics `Context` can't store shapes. We need a separate library for that. Perhaps we should start a `graphics_scene` library?

**Comment by mitchmindtree** [comment]
My [`elmesque` library](https://github.com/mitchmindtree/elmesque/blob/master/examples/test.rs#L74) does this - perhaps it could be starting point? Maybe have a look and see what you think? (it renders using the piston::graphics crate under the hood).

**Comment by bvssvni** [comment]
Looks interesting.

**Comment by mitchmindtree** [comment]
I think the elmesque lib could re-use more of the graphics lib stuff actually (like transform2d, etc) - for a lot of it, I just implemented as a direct port from elm-lang's std library.

Anyway, I'll have a go at addressing this issue under an "experiment" branch.

**Comment by mitchmindtree** [comment]
It looks like this will make it easy to solve #367 as there will only be one `.draw` call and it will be easy to pass the top-level context.
