### ISSUE TITLE
Move `color.rs` module into its own crate?

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#373]
It's just a thought - I realise crates often need their own versions of the `Color` type depending on the context, however as there isn't currently a `PistonDevelopers/color` crate at all, perhaps conrod's color.rs would make a handy, general-use color crate? Perhaps we could merge the `read_color` and `select_color` crates into it also?

**Comment by bvssvni** [comment]
`select_color` depends on the image library, but `read_color` could be merged into it.

**Comment by mitchmindtree** [comment]
Closed by #385
