### ISSUE TITLE
Change to using a Cartesian plane for Conrod's positioning with (0, 0) at centre.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#374]
As we'll likely use elmesque (which uses the Cartesian plane with centred (0, 0)) for graphics layout and positioning, Conrod should too. It is arguably a more generally intuitive co-ordinate system, and it also makes it easier to reason about elements' relative positioning.

**Comment by bvssvni** [comment]
The upper left corner with y axis down is very common, also used by Window forms. This is what piston-graphics uses. Centered coordinate system is more common for 3D.

**Comment by mitchmindtree** [comment]
Indeed, it is quite common, however using a cartesian plane and treating the origin as (0, 0) can offer some really nice properties for grouping elements and layout - Elm is a language designed for web GUI that also uses the cartesian plane, they describe these nice properties in [this post](http://elm-lang.org/blog/announce/0.8.elm) (under the "Better 2D Graphics" section). I'm halfway into #372 (I'm addressing this at the same time as #372 requires elmesque) and it's proving to be quite useful, but we can change it back if it causes any issues. The user will most likely just be using relative positioning (I'm fixing that atm also) most of the time so it probably won't make a huge difference from an API standpoint.

**Comment by bvssvni** [comment]
Keeping a consistent absolute coordinate system is more important than using the same axis that people learn in math classes. This is because the majority of programmers will expect the coordinate system to start in the upper left corner, and it is important to make libraries work together.

**Comment by bvssvni** [comment]
There are reasons why 2D graphics usually starts a coordinate systems from a corner. In relative coordinates, you need to know the size of the parent rectangle. If you start from the upper left corner, then you don't need that extra information. It also fits how you store data in a raw image format, with the first byte corresponding to the upper left pixel. There is a historical reason of how computer screens worked that is the origin of this coordinate system.

Cartesian coordinates does not specify that the y axis should point up, they are general for all choices of axis directions. When working with rotations, it is common to use y-axis up, but in widget programming rotations are less common and the fact that you don't have to know the parent rectangle or window size makes it practical. Some GUI systems use the lower left corner as origin.

I agree with the argument that it is easy to do mistakes when working with polar coordinates, but the other arguments seems fishy.

**Comment by bvssvni** [comment]
@mitchmindtree Sorry for disrupting you while working! I am concerned that using a centered coordinate system is not a good idea, and there is little reason to choose another corner that is less common. This is something I want to get right now than later, and hope it is not too much work for you to use the upper left corner.

**Comment by mitchmindtree** [comment]
@bvssvni No problem! I definitely understand your concerns and am thinking hard about them.

Here are some of my own thoughts/concerns:
- Using elmesque for it's `Element` composition and layout system, there will no longer be any calls to graphics::Shape, etc or any other direct calls to the graphics api at all within conrod (all of those calls happen under the hood in elmesque).
- The whole elmesque library is based on the centred origin coordinates. As a result it has nice support for rotations and it would be useful for adding rotary sliders, dialers, menus, etc which are all yet to be implemented. This would also be useful for nodal ui layout (which will be much more doable once #372 lands).
- Now that elmesque is becoming conrod's interface to graphics and layout, either the elmesque library needs to entirely change or conrod does. The idea of elmesque was to provide a direct port of elm-lang's standard graphics modules and I'd like to keep it as close to the original as possible.
- As conrod is a GL gui library, I imagined a common use as a 2D UI overlay within games (not just pages of rects).

Possible solutions:
1. Change elmesque library to use top-left y-down coords (I'm not too keen on this for the reason stated above).
2. Change conrod to use centred coords (this would contrast the piston::graphics crate).
3. Support both sets of coordinates in conrod. i.e. `Ui::new().origin_centred_y_up()` or `.origin_top_left_y_down()`

It's getting late here so I think I'll sleep on this - option 3 is the most appealing to me but I'm not sure how do-able it is - going to put a lot of thought in before going any further.

Also, this isn't particularly related to this topic, but perhaps it could be useful to provide a `Context::origin_centred_y_up` constructor (+ [w/2, h/2], flip y) in the graphics crate? I'm not sure how practical this would be. I think it's safe to assume that people are going to have different preferences depending on their application and maybe it would be useful to support it if possible?

Anyways, I'm off to bed, talk to you more tomorrow!

**Comment by mitchmindtree** [comment]
Ok, after a lot of thought, I think I might have an alternative solution to those above:

Really, conrod's API for layout and positioning should mean that a user *never* has to consider the coordinate system at all. I think if conrod leaves any use case where a user finds they do have to specify specific coordinates, then we can treat that as a serious problem in conrod's layout/positioning API and something we need to address.

For initial positions, we should use some kind of canvas system (like eddyb's vbox/hbox idea) where the user just has to specify which canvas and where on the canvas they want to position their widgets (i.e. `.top_left(header_canvas)` or `.centre(first_column)`, etc). All other positioning should just be relative (i.e. `.down(30.0)`, `.right_from(other_ui_id, 50.0)`, etc).

This way, conrod can just use `elmesque's` layout internally as is and we never have to worry about coordinate interactions from an API standpoint (though we can still expose methods for the *very* rare case that someone might need it).

I'll add an issue with a draft for a layout system that can achieve this - I don't think it should be too tricky at all. @bvssvni let me know your thoughts, hopefully this can be a nice solution!

**Comment by bvssvni** [comment]
@mitchmindtree That's a good idea!

**Comment by mitchmindtree** [comment]
Closed by #385
