### ISSUE TITLE
Port the examples to piston_window or all back_ends

### ISSUE THREAD

**Issue by dcampbell24** [PistonDevelopers/conrod#383]
In The PR #379 @bvssvni mentioned porting the example (s?) to piston_window so that we can use scissoring from gfx_graphics. I am wondering if this is the best idea or maybe we should add runtime or compile time flags so that the examples can be tested with different back ends.

Not only can we test functionality, but also performance. Right now the main thread for all_widgets consumes ~ 20% of a CPU on my desktop, which seems like a lot for drawing something that is not changing very much.

Regarding porting to piston_window, I have done so [here](https://github.com/dcampbell24/conrod/tree/examples-piston_window), but it currently panics at runtime and requires changing the Ui API to make the character_cache public so that update can be called on it. It also requires removing the Debug constraint from handle_event since PistonWindow does not impl Debug.

```
     Running `target/debug/examples/all_widgets`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid data size provided to update the texture, expected size 4', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:768
stack backtrace:
   1:     0x7fd3c362feb9 - sys::backtrace::write::he1173a406c2335a83JC
   2:     0x7fd3c3633209 - panicking::on_panic::hfd4f10113591c07f9aJ
   3:     0x7fd3c3627212 - rt::unwind::begin_unwind_inner::h5dd2f870d997f851hQI
   4:     0x7fd3c36274df - rt::unwind::begin_unwind_fmt::h3268b3e4add9e5a1VOI
   5:     0x7fd3c3632b77 - rust_begin_unwind
   6:     0x7fd3c365e794 - panicking::panic_fmt::haaabf6c9124a6ae6qEC
   7:     0x7fd3c34ac166 - result::Result<T, E>::unwrap::h7826657395073998968
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:27
   8:     0x7fd3c3516b2e - texture::Texture<R>::from_memory_alpha::h6282597683239701255
                        at /home/david/.multirust/toolchains/nightly/cargo/git/checkouts/gfx_texture-77e24d624e559a68/master/src/texture.rs:110
   9:     0x7fd3c3513f93 - glyph::GlyphCache<'a, R>::update::h5844291922568715264
                        at /home/david/.multirust/toolchains/nightly/cargo/git/checkouts/gfx_graphics-ca3f282b513b7e77/master/src/glyph.rs:83
  10:     0x7fd3c347ce76 - main::h79bfc8f0887192b2bfa
                        at examples/all_widgets.rs:145
  11:     0x7fd3c3636b28 - rust_try_inner
  12:     0x7fd3c3636b15 - rust_try
  13:     0x7fd3c36348ab - rt::lang_start::h8d3ab7a0483b5e96C5I
  14:     0x7fd3c3517154 - main
  15:     0x7fd3c1ff1ec4 - __libc_start_main
  16:     0x7fd3c3473438 - <unknown>
  17:                0x0 - <unknown>
An unknown error occurred
```

**Comment by Potpourri** [comment]
Panic I already fixed(later do PR), but gfx_graphics still have one problem with texture(if try draw the same texture two or more, then will be drawn only first).

**Comment by mitchmindtree** [comment]
@dcampbell24 This is a tricky one because it would be nice to keep the example as clean as possible without flags all over the place (so that it can be a nice example), but at the same time it would be excellent to be able to test each backend.

I like the idea of leaving the examples as examples, and perhaps adding a `tests` directory in which we can test and bench conrod (maybe with flags like you mentioned, or in individual modules - I don't mind either way).

It would be interesting to test the performance between different window apis too (sdl2, glfw).

**Comment by dcampbell24** [comment]
@Potpourri thanks! The example is now compiling and appears to be working OK, but is using a lot of CPU around 50% at start with a --release build.

I also noticed with either backend the the CPU usage goes up a noticeable amount as the text gets longer in the TextBox widget (looks linear), but the constant factor is much larger for the piston_window  / gfx_graphics backend.

```
| backend                         | 0 Char | 10 Char  | 40 Char|
|---------------------------------|--------|----------|--------|
| gfx_graphics / pison_window     | ~ 11%  | ~ 12%    | ~ 14%  |
| opengl_graphics / glutin_window | ~ 47%  | ~ 52%    | ~ 60%  |
```

At 40 Char there is also a second thread that gets up to around 40% CPU usage.

**Comment by dcampbell24** [comment]
I don't think with this poor of performance we want to encourage people to use the gfx_graphics / piston_window back end right now or switch the example over to it. @mitchmindtree a tests directory sounds good to me as well.

**Comment by mitchmindtree** [comment]
@dcampbell24 interesting results! I think that's a good call on leaving the example until we can solve the performance difference (hopefully not too tricky). I'm guessing the 50% spike is the CharacterCache constructing the textures for each glyph the first time that all the widgets are called (not sure if there's a faster way to do this, perhaps could be discussed in the graphics crate).

Also, I just want to let you know that I've been doing a pretty large reform of conrod's innards related to #372 that will probably affect these results, though I've no idea whether we'll be better or worse off yet (PR should be within 24 hrs, probably sooner than later).

**Comment by bvssvni** [comment]
@dcampbell24 There should be no spawning threads as I know of, I can't explain why that happens. 

gfx_graphics has consistently outperformed opengl_graphics when tested with https://github.com/bvssvni/rust-snake .

**Comment by mitchmindtree** [comment]
Going to close this as @dcampbell24 has added the benchmarks and the new canvas example is successfully using the piston_window crate.
