### ISSUE TITLE
Change `.callback` method name to something more suitable.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#388]
The term "callback" is more commonly associated with the more retained approach to Ui, while conrod's approach is much more reactive/inlined/functional. Some better names might be:
- `.react(||...)`
- `.event(||...)`
- `.do(||...)` (actually, `do` is reserved)
- `.trigger(||...)`

I'm leaning towards `react`, any suggestions welcome though!

Also, `callback` might be better saved in case we want to offer support for callback events in the future, i.e. `.callback(event_sender)` where the triggered event could be sent over some `Sender<UiEvent>`.

**Comment by bvssvni** [comment]
`react` is nice!
