### ISSUE TITLE
Use a virtual unit instead of pixels for dimensions, coords, etc?

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#395]
It would probably be beneficial to use a virtual unit instead of pixels in order to remain more independent of different dpis. Perhaps `points` as in viewport? I guess that's the whole idea behind viewport in the first place!

**Comment by bvssvni** [comment]
Yes, that's the idea behind viewport. With piston-graphics, you use a matrix transformation to transform all the coordinates. This matrix transform is relative to pixels, so there is no need to know the units as long as you know which coordinate system (matrix transform) is used. The difference between pixels and points is that `Context` stores an additional matrix transform, called `view_transform`, which equal the original matrix transformation, the one you start with after calling `Context::new_viewport`. This is now equivalent to points, where it before was pixels. It is the same coordinate system but zoomed out with the dpi factor, so 2D graphics looks the same size on all devices. The view transform can be changed and modified by the user. Matrix transforms are more flexible than virtual units.
