### ISSUE TITLE
Example all_widgets doesn't build on beta compiler

### ISSUE THREAD

**Issue by cehawkins** [PistonDevelopers/conrod#418]
First off, I'm new to rust so anything said below could be utter nonsense.

The problem is that when building all_widgets, some of the gfx libraries don't build on the beta channel due to use of unstable features "alloc" and "core."  The build for all_widgets should require the nightly build rust compiler or it should require stable (or older?) versions of the gfx libraries.  If the former, the main page should state it (and I'll switch myself), if the latter, point me in the right direction and I'll try to figure out how to do it.

**Comment by mitchmindtree** [comment]
@cehawkins ahhh I'm sorry about this, I was unaware that the gfx libs are using unstable - I'm definitely interested in keeping conrod building on the stable channels. I'd recommend leaving an issue (if there isn't one already) at the gfx lib that was producing the error and inquiring about the possibility building for the stable channel (i.e. they might have a stable branch we can use, or they might be planning to go stable soon).

In the mean time I'll add a change to our .travis.yml to make sure travis tests on beta so that I can be notified if something goes wrong.

**Comment by cehawkins** [comment]
They said there is a rust-1.0 branch for gfx-rs but gfx_macros was totally dependent on the nightly build and they closed the ticket which I took to mean that's the final answer.  I'm swamped the rest of the week but I'll check back in a few days.

**Comment by mitchmindtree** [comment]
@cehawkins no prob! If I get a chance I'll see what I can do about this, though I'm quite busy atm. Going leave the [related ticket here](https://github.com/gfx-rs/gfx-rs/issues/712) so I can come back to it.

**Comment by mitchmindtree** [comment]
@cehawkins, just thought I'd let you know conrod and all the examples should now build on beta thanks to some awesome work by the gfx guys on reaching stability :) going to close this now

**Comment by cehawkins** [comment]
Thanks!  I ended up deleting everything and reinstalling just to make sure everything was fresh.  all_widgets does compile but now I get (using --verbose):
     Running `target/debug/examples/all_widgets`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("glx::ChooseFBConfig failed")', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:729
Process didn't exit successfully: `target/debug/examples/all_widgets` (exit code: 101)

**Comment by zeroows** [comment]
any update on this error ```Running `target/debug/examples/all_widgets`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("glx::ChooseFBConfig failed")', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:729```

**Comment by cehawkins** [comment]
Well, to be blunt, I've punted.  I was mainly trying out rust and have decided it isn't for me.

**Comment by zeroows** [comment]
Same, I liked D more. More stable and better  tools. 

Good luck guys.

**Comment by mitchmindtree** [comment]
No prob folks, certainly still early days for Rust, perhaps not yet ready for the faint-hearted! Thanks for contributing :)

**Comment by cehawkins** [comment]
Well, for me it's nothing to do with heart or rough edges, but language design and synergy.  I've been a programmer for a very long time by anyone's definition and have done major projects in at least a dozen different languages.  I don't know why some languages "feel right" and others don't, but I do know the feeling and I'm sure it varies from one programmer to another which is one of the reasons there are so many languages out there.  Hmm, not unlike women and ice cream flavors. ;)  To each his own.

Anyway, thanks for your help with this problem.  Keep up the good work.
