### ISSUE TITLE
Host documentation, keep it up to date using travis and add link to README.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#425]
It would be sweet if we could do something like [this](http://hoverbear.org/2015/03/07/rust-travis-github-pages/) for conrod. The documentation is looking good, but at the moment a user has to clone the repo and `cargo doc` to get it.

@bvssvni do you already have some preferred way of hosting documentation for piston projects?

**Comment by bvssvni** [comment]
There is a way to do this already. http://docs.piston.rs/

Just add the line to .travis.yml https://github.com/PistonDevelopers/piston/blob/master/.travis.yml#L6
