### ISSUE TITLE
Interop with graphics crate

### ISSUE THREAD

**Issue by dcampbell24** [PistonDevelopers/conrod#438]
Suppose I want to draw a box with rounded corners using graphics::Rectangle and place some conrod::Label's inside of it. How do I align them properly? Is there a way to place a Label so that it's top left coordinate will be (x, y) in absolute coordinates?

**Comment by mitchmindtree** [comment]
@dcampbell24 conrod uses the same coordinate system as elmesque ((0, 0) origin, y-up), but it shouldn't be hard to add another variant to the `Position` enum for positioning using graphics' coord system instead. What should the `Positionable` method name be called? `.screen_xy(x, y)`? all the names already taken are [here](https://github.com/PistonDevelopers/conrod/blob/master/src/position.rs#L97). Personally, I'd use elmesque for doing basic 2D graphics designed to work alongside conrod, but I understand that elmesque doesn't quite expose all of graphics' functionality yet.

**Comment by dcampbell24** [comment]
Hmm... `.screen_xy( x, y)` sounds good. Also, could we make the alignment functions more general so that they will also affect `screen_xy` (maybe also `xy` and all the other placement functions)?

**Comment by mitchmindtree** [comment]
Going to close this as conrod no longer explicitly depends on piston2d-graphics, rather conrod provides a `piston` feature with some helper items for using conrod alongside piston events and graphics implementations.
