### ISSUE TITLE
Pane

### ISSUE THREAD

**Issue by Woolworths** [PistonDevelopers/conrod#443]
We need Panes (containers for widgets). 
I suggest the basics:
Horizontal Pane
Vertical Pane
Grid Pane

**Comment by mitchmindtree** [comment]
@Woolworths Please see the `canvas.rs` example - I think the `Split` canvas type might achieve what you're after? You construct horizontal and vertical "pane"s with it by constructing a tree of splits. There is now also a `Floating` canvas type which provides similar behaviour, but floats on top and is draggable (kind of like a popup window).

**Comment by Woolworths** [comment]
I apologise :)

**Comment by mitchmindtree** [comment]
No problem :smile: is it ok to close this now?

**Comment by Woolworths** [comment]
Yes!
