### ISSUE TITLE
Macro for generating Widget and Canvas Ids

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#451]
I imagine invocation would look something like this:
```Rust
widget_ids! {
    FOO,
    BAR,
    MATRIX <- 64,
    BAZ,
}
```

Which would expand into
```Rust
const FOO: WidgetId = 0;
const BAR: WidgetId = 1;
const MATRIX: WidgetId = 2;
const BAZ: WidgetId = 66;
```

This would save the user from doing something like:
```Rust
const FOO: WidgetId = 0;
const BAR: WidgetId = FOO + 1;
const MATRIX: WidgetId = BAR + 1;
const BAZ: WidgetId = MATRIX + 64;
```

I believe this should be possible with a [recursive macro](https://doc.rust-lang.org/book/macros.html#recursive-macros) to achieve the module level counting behaviour. I've had a go at this but kept running into the following compile error:
```
error: `$current_id:ident` is followed by a sequence repetition, which is not allowed for `ident` fragments
```

Would love it if someone would like to have a go at this :+1:

**Comment by bvssvni** [comment]
Some ideas:

- Combine `&'static str` and usize
- `.begin` and `.end` methods for nested hierarchies
- Instead of incrementing, use `0` for `+1`

**Comment by bvssvni** [comment]
What about storing nested `Ui`?

**Comment by jarrett** [comment]
[This gist](https://gist.github.com/jarrett/e330ae21b40e85753a5c) is very close to what @mitchmindtree proposed, with an alternative to the proposed `MATRIX <- 64` notation.

I'm not sure if the `MATRIX <- 64` notation will be possible with Rust's macros. I think we need repetition in the matcher. Apparently, Rust's [macro grammar](https://doc.rust-lang.org/grammar.html#macros) doesn't allow variants inside a repetition matcher. That is, it doesn't seem to support a matcher like this:

    $($tail:ident | $tail -> $offset:expr)

...which I think we might need for `MATRIX <- 64`. I could be wrong, though.

**Comment by bvssvni** [comment]
@jarrett :+1: You can use `start: X` multiple times, right?

**Comment by jarrett** [comment]
@bvssvni you can call `widget_ids` multiple times, passing in different `start` values. But I don't think you can use `start` more than once in a given call to `widget_ids`. It's the same problem as with `MATRIX <- 64`: It would require matching on multiple possibilities inside the repetition.

**Comment by mitchmindtree** [comment]
Thanks heaps for looking into this @jarrett ! You inspired me to have a closer look and see if we could stitch it all together so that we wouldn't have to have multiple invocations with different `start` values, etc :)

After getting some help from from the macro wizards in IRC I managed to get something working that's closer to the original goal! It turns out you can do some crazy magic using the `tt` aka "token tree" fragment specifier! I've submitted a PR at #533 which has docs, examples, etc.

So the above example now looks like this:

```Rust
widget_ids! {
    FOO,
    BAR,
    MATRIX with 64,
    BAZ,
}
```

If you only have a few IDs, you can also invoke it like this:
```Rust
widget_ids!(FOO, BAR, MATRIX with 64, BAZ);
```

I ended up going with `with` instead of `<-` as I thought it was a little clearer. It kind of reads like "Reserve FOO `with` 64 IDs".

**Comment by jarrett** [comment]
That's excellent news! I'm also really happy to learn that trick about
`tt`. I'd tried `tt` with `<-`, but the compiler didn't like that. I guess
`FOO with 64` is a valid `tt`, but `FOO <- 64` isn't?

**Comment by mitchmindtree** [comment]
`<-` is actually also valid (you can swap it in the macro implementation and it works just fine). I thought it wasn't when I tried at first, but almost all of my errors turned out to be that I wasn't properly handling the final case for the recursion properly! Someone mentioned the `trace_macros` feature which helped debugging the macro a *lot* - would definitely recommend using it the next time you're writing a tricky macro.

**Comment by jarrett** [comment]
Thanks! Great tip.
