### ISSUE TITLE
Trait conflict on impl custom widget

### ISSUE THREAD

**Issue by viperscape** [PistonDevelopers/conrod#469]
So this [code](https://github.com/viperscape/mush/blob/master/src/widgets/edge.rs#L71) used to compile, but after running cargo update it no longer does. I'm confused because I do not see an update in conrod that would cause this issue, so maybe someone can help me.

```rust
cargo run
   Compiling mush v0.1.0 (file:///C:/Users/chris/mush)
widgets\edge.rs:71:5: 84:6 error: the requirement `C : graphics::character::CharacterCache` appears on the impl method but not on the corresponding trait method [E0276]
widgets\edge.rs:71     fn update<'b, C>(self,
widgets\edge.rs:72                      prev_state: &WidgetState<EdgeState>,
widgets\edge.rs:73                      _xy: Point,
widgets\edge.rs:74                      _dim: Dimensions,
widgets\edge.rs:75                      _input: UserInput<'b>,
widgets\edge.rs:76                      _style: &Style,
                   ...
```
I originally based this off of [label](https://github.com/PistonDevelopers/conrod/blob/master/src/widget/label.rs#L79), but I noticed that mod.rs in widgets has a [different trait declaration](https://github.com/PistonDevelopers/conrod/blob/master/src/widget/mod.rs#L81), where the arguments are named differently. I tried and renamed everything but that did not help. Update and Draw both are erroring for me. Any help is appreciated!

**Comment by mitchmindtree** [comment]
Hmmm I'm currently out of town and don't have time to dig deeper, but it sounds like this might be a problem with conflicting crate versions? Is the version of the graphics crate you are using the same as the one that Conrod uses?

**Comment by viperscape** [comment]
Yes this fixed it! I moved from git repos to crates and this fixed it. Thanks
