### ISSUE TITLE
In the widget TextBox, crash when erase an unicode char

### ISSUE THREAD

**Issue by EleDiaz** [PistonDevelopers/conrod#479]
In introduction of unicode chars in the TextBox, this fails. This is due to use of `len` function to get length of text, but it function returns the quantity of bytes.

This error is present in some lines where is used `len` one of these is
line 444 of text_box.rs
 ```rust
                cursor.shift(text.len() as i32);
```

I have saw that the function to use, should be `width`, but it is deprecated from `collection` library
http://doc.rust-lang.org/collections/string/struct.String.html#method.width

To get an correct width from unicode chars, there are other library
http://unicode-rs.github.io/unicode-width/unicode_width/index.html

**Comment by bvssvni** [comment]
Perhaps use `text.chars().count()`.

**Comment by EleDiaz** [comment]
okey, i liked but there are other function that works with bytes is truncate
```rust
self.text.truncate(cursor.start)

// I dont like erase all self.text
let start: String = self.text.chars().take(cursor.start-1).collect();
let end: String = self.text.chars().skip(cursor.end).collect();
self.text.clear();
self.text.push_str(&start);
self.text.push_str(&end);
```

if you have any idea to improve?
[Commit solve the bug] (https://github.com/EleDiaz/conrod/commit/a8c43c2037541cc9e88c5cbc515775c6297e8088)

Other new problem is that when you press an unicode input like à -> ` + a
In TextBox is showed double àà. My keyboard have the letter ñ and don't appear twice when i press.
I think that width(text) == 2 here. I don't known how solve.
```rust 
// Check for entered text.
            for text in input.entered_text.to_vec().iter() {
 
```

**Comment by EleDiaz** [comment]
I am discover that the problem of double insertion of unicode char come from backend glutin, in sdl2 not experiment problems. 
In the sdl2 window, its behaviour is different when erase, holding the backspace key, only is remove one char. In change glutin remove until arrive to start of string.

**Comment by mitchmindtree** [comment]
Is this all fixed now?

Going to close this for now, but if its still an issue I'll reopen it :+1:
