### ISSUE TITLE
Add a `.xy` version for top left coordinates

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#488]

**Comment by mitchmindtree** [comment]
All we need for this is a name and I'll be happy to implement it!

Here are [all the names that already exist](https://github.com/PistonDevelopers/conrod/blob/master/src/position.rs#L97).

Some unused suggestions:
- `.window_xy(x, y)`
- `.screen_xy(x, y)`
- `.top_left_xy(x, y)`
- `.corner_xy(x, y)`
- `.coords(x, y)`

**Comment by bvssvni** [comment]
What about `.left_top(x, y)`?

**Comment by mitchmindtree** [comment]
@bvssvni oh yeah I like that :)

**Comment by mitchmindtree** [comment]
Going to close this as most positioning is now done with [higher level methods](http://docs.piston.rs/conrod/conrod/position/trait.Positionable.html) and we haven't had a request for this since.
