### ISSUE TITLE
Re-export `graphics::math::Scalar` from top level.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#490]
Necessary for designing custom widgets - related to [this comment](https://github.com/PistonDevelopers/conrod/issues/472#issuecomment-117357942).

**Comment by wldcordeiro** [comment]
So do you mean re-exporting it as `graphics::Scalar`?

**Comment by mitchmindtree** [comment]
@wldcordeiro I meant exporting it from Conrod's lib.rs, so that you can `use conrod::Scalar;` in projects that use conrod.
