### ISSUE TITLE
Cannot move exacutable to another folder

### ISSUE THREAD

**Issue by Halamix2** [PistonDevelopers/conrod#493]
I compiled all_examples.exe (Windows7 64bit, rust 1.1.0 64, conrod from cargo ([dependencies]/ conrod="*", it downloaded 0.4.0). 
I can run this exe. 
However, when I copy/move release folder somewhere else (with deps, examples etc. subfolders and subfiles) somewhere else I get this error:

>thread '\<main\>' panicked at 'called `Result::unwrap()` on an `Err` value: IO(Error { repr: Os(5) })', C:/bot/slave/stable-dist-rustc-win-gnu-64/build/src/libcore\result.rs:729

EDIT:
When I copied "target" folder and "assets" it worked. It looks that fonts are necessary to run this executable but error information isn't helping

**Comment by kempchee** [comment]
I am pretty sure it is because the fonts use a relative path to the project root (folder/*), not to the exe.  So when the exe is executed, there isn't a font directory where the executable is stored and it panics. Try moving the fonts folder to the same location as the executable.

**Comment by Halamix2** [comment]
Okay, it works when I have folders and files like this, and I'm closing this issue since it works after putting everything in right folders.
.
├── Assets
│  └── fonts
│      └── notoSans
│          └── font files (.ttf)
└── target
    └── release
        └── examples
            └── all_widgets.exe
