### ISSUE TITLE
Allow custom `Widget`s to be composed of other `Widget`s.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#494]
At the moment, I'm quite sure that this is not possible without the parent `Widget` reserving multiple `UiId`s for each of its child `Widget`s. This is because Conrod's `UiId` system is linear, and every `Widget` requires its own `UiId`.

If `Widget`s are to be composable from other `Widget`s, then this would imply a more tree-like system.

Perhaps each `Cached` widget could also have its own cache of widgets that it manages, rather than having the `Ui` manage *all* widgets?

This would also mean we could remove the `canvas_cache`, and consolidate the different `Canvas` kinds as `Widget`s and store everything in the `widget_cache`.

It would also make designing custom widgets *much* easier, as users would be able to use pre-existing widgets with ease.

This would be a large refactor, but definitely worth it... Going to put some thought into this.

It would be nice to have this done prior to doing the custom widgets example #472.

**Comment by mitchmindtree** [comment]
Perhaps the `.set(UI_ID, ui)` method can take some `T: WidgetCache` instead of just a `Ui`. This way, both "parent" type `Widget`s (`Canvas`ses, etc) and the `Ui` could implement `WidgetCache` and passed to the `set` method. Each may have their own widget cache and their own independent set of `UiId`s.

To make this easier, we could implement `Index` and `IndexMut` for any `WidgetCache` types, so that they might be used like this:

```Rust
.set(FOO_ID, &mut ui[FOO_PARENT_ID])

.set(FOO, &mut ui[BAR][BAZ])
```

Thus we have an easy way of talking about the `Ui` tree, where each branch has its own set of `UiId`s.

**Comment by bvssvni** [comment]
Looks good!

**Comment by mitchmindtree** [comment]
Hmmm I don't think `Index`/`IndexMut` will work here, as a few members/methods from the `Ui` will also need to be passed through for use within the `Widget::set` method.

Perhaps we'd be best to define a new method which can do this, maybe with some sort of context type containing (references to) all the necessary `Ui` stuff (i.e. `ui.kid(ID)` instead of `ui[ID]`). Alternatively, we could pass the tree indices to the parent as a slice. Here are both options for setting the widget `FOO` inside of a parent widget `BAZ` which has the parent `BAR`:
- **A**. `.set(FOO, ui.kid(BAR).kid(BAZ))`
- **B**. `.set(FOO, ui, &[BAR, BAZ])`

To work out what is the best option (and maybe find other better options) we should first explore what exactly is needed within `Widget::set`.

Things required from `Ui` in `Widget::set`
------------------------------------------------------

I've made a list of all things that the `set` method requires from the `Ui`:
- `ui.get_xy(...)`
- `ui.theme`
- `ui.get_widget_state(...)`
- `ui.get_canvas_from_position(...)`
- `ui.user_input(...)`
- `ui.glyph_cache`
- `ui.mouse/keyboard_(un)captured_by(...)`
- `ui.update_widget(...)`

Handling the requirements
-----------------------------------

I'm able to abstract out the `Ui`'s `.widget_cache` member into a `widget::Cache` type that takes care of two of the above methods:
- `get_widget_state`
- `update_widget`

Each `widget::Container` within the `widget::Cache` would have it's own `widget::Cache` for storing its own child widgets (thus creating the tree-like structure).

Seeing as canvasses would just become widgets if this change were to go ahead, this also removes the need for:
- `get_canvas_from_position`


`get_xy`
-------------

This method converts a widget's given [`Position`](https://github.com/PistonDevelopers/conrod/blob/master/src/position.rs#L20), dimensions and [alignment](https://github.com/PistonDevelopers/conrod/blob/master/src/position.rs#L51) into a single centred xy position on the screen. At the moment it requires the following from the `Ui`:
- `maybe_prev_widget_id`. This is used in the case that a position such as `Down` or `Left` was given without referring to any specific widget. This can be solved by instead moving `maybe_prev_widget_id` to the parent's `widget::Cache` type, where `Some(prev_widget_id)` will be the last widget `.set` into that cache.
- `widget_cache` (and `canvas_cache`, but that will no longer be necessary). This is used when the user 
gives some `Position` relative to some other specific `UiId`. This may cause issues with ownership if some widget outside of the parent is given as we would need access to the root of the tree (the `Ui`).
- window dimensions (easy to pass on).


`mouse/keyboard_(un)captured_by(...)`
----------------------------------------------------

These methods are related to the global capturing of input - we'd need access to the `Ui`'s `maybe_captured_mouse/keyboard` members.


Apologies for the brokenness of this comment, just trying to think this through!

**Comment by mitchmindtree** [comment]
I think the reason this is getting complex quite quickly is that I'm intertwining two issues that should be separate:

1. The API should provide a way to set any `Widget` as their `Widget`'s "parent"/"canvas" (rather than having a separate `Canvas` type).
2. Custom `Widget` designers should be able to compose a `Widget` from other `Widget`s without occupying the `UiId` space.

I might close this and post separate issues for these.
