### ISSUE TITLE
Should the `Widget::update/draw` args be combined into single `Update/DrawArgs` types?

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#507]
At the moment the args for the `Widget::update` and `Widget::draw` methods are pretty verbose and it can be a bit of a pain when writing custom `Widget` implementations. Perhaps we can do something like the following:

```Rust
    /// Update the state of the Canvas.
    fn update<'a, C>(mut self,
                     prev_state: &widget::State<State>,
                     xy: Point,
                     dim: Dimensions,
                     input: UserInput<'a>,
                     style: &Style,
                     theme: &Theme,
                     glyph_cache: &GlyphCache<C>) -> Option<State>
        where C: CharacterCache;
```

would become

```Rust
    /// Update the state of the Canvas.
    fn update<'a, 'b, C>(mut self, args: UpdateArgs<'a, 'b, C>) -> Option<State>
        where C: CharacterCache;
```

(same goes for `Widget::draw`)

This should also reduce the number of imports needed.

**Comment by mitchmindtree** [comment]
I've started implementing this now and its looking good :+1:

**Comment by bvssvni** [comment]
Notice that there is an `UpdateArgs` in the pistoncore-event library.

**Comment by mitchmindtree** [comment]
Yeah, remembering that is what made me consider using it for this :)
