### ISSUE TITLE
Error running canvas example

### ISSUE THREAD

**Issue by esn01** [PistonDevelopers/conrod#512]
Running `target/debug/examples/canvas`
[glutin] x error code=48 major=0 minor=0!
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("GL context creation failed")', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:729
Process didn't exit successfully: `target/debug/examples/canvas` (exit code: 101)

code: let opengl = settings.get_maybe_opengl().unwrap_or(OpenGL::V3_2);
file: pistoncore-glutin_window/src/lib.rs: 44
doesn't seem to work like expected on systems where OpenGL-Version < 3.2

my system: debian 8, OpenGL-Version: 3.1

**Comment by mitchmindtree** [comment]
@bvssvni the canvas example uses `piston_window` which I don't think exposes any way to set the version in the `GlutinWindow` at the moment - perhaps we can add a `opengl_version(..)` method to `PistonWindow`?

**Comment by bvssvni** [comment]
Try `WindowSettings::new("hello", size).opengl(OpenGL::V2_2)`.

**Comment by mitchmindtree** [comment]
Closing this as is old and probably solved long ago.
