### ISSUE TITLE
Another error running canvas example

### ISSUE THREAD

**Issue by esn01** [PistonDevelopers/conrod#513]
Running `target/debug/examples/canvas`
thread '<main>' panicked at 'Error after executing command BindProgram(0): InvalidEnum', /home/slawek/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.4.1/src/lib.rs:223
Process didn't exit successfully: `target/debug/examples/canvas` (exit code: 101)

**Comment by mitchmindtree** [comment]
@esn01 thank you for the issues! I'm sorry you've been running into trouble.

It looks like the [gfx_device_gl crate](https://github.com/gfx-rs/gfx_device_gl) has been deprecated and [moved into the `gfx` crate](https://github.com/gfx-rs/gfx_device_gl) itself, I think we just have to switch our dependency to gfx instead. I don't have time to do this just yet, but would be happy to merge a PR :)

@bvssvni I guess this will probably also be necessary in piston_window?

**Comment by bvssvni** [comment]
The gfx_device_gl is put in the gfx repository, but the library on crates.io is still in use. gfx_device_gl is the OpenGL back-end for Gfx.
