### ISSUE TITLE
Artifacts on edges in all_widgets example

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#516]
If you look closely in the screenshot, you can see some artifacts on the edges:

![screen shot 2015-07-22 at 19 36 03](https://cloud.githubusercontent.com/assets/1743862/8832378/f6188ace-30a8-11e5-8daf-981ef052ecf3.png)

**Comment by clicketyclack** [comment]
@bvssvni I need a hint on this one. I see some artefacts around the text, but not sure if it is due to a lossy screenshot format.

![image](https://cloud.githubusercontent.com/assets/22734483/19577661/718f4824-9718-11e6-90f6-f24474252e95.png)

**Comment by bvssvni** [comment]
RustType or FreeType?

**Comment by mitchmindtree** [comment]
@bvssvni conrod has only been using RustType for a while now. Do you still get the behaviour shown in your original comment btw? I can't seem to recreate it on OS X.

@clicketyclack I think text artifacts you're getting are probably related to #787.

**Comment by bvssvni** [comment]
It looks like colors are bleeding at the edge. If I remember correctly, it got something to do with the size of the texture when rasterizing the font.

**Comment by mitchmindtree** [comment]
Oh so your original issue was about the text too? I thought it might be about the other graphics, as the edges on some of the shapes look a little blurry as well (especially some of the edges in the toggle grid).

On my end, I do still get blurry text (though only on my retina display), but I haven't noticed blurring on the shape edges like in your pic (though maybe that's just the compression on the screenshot 😆).

As for the `Text` specifically, I explained in #787 why I think the edges are bleeding on retina displays, but I haven't had a chance to test my hypothesis just yet. Would be great to get your thoughts there if ya get a chance :)

**Comment by bvssvni** [comment]
Could export a rasterized glyph as PNG to examine the edge.

**Comment by clicketyclack** [comment]
Yeah, my picture is a cropped + zoomed piece from @bvssvni 's original screenshot. I can't see any other artifacting in it and was wondering what I am missing.

**Comment by bvssvni** [comment]
OpenGL has some settings where you clamp interpolated values to a border color. I believe there was a similar problem, but I can't remember where or when.

**Comment by zummenix** [comment]
You can take a look at https://github.com/PistonDevelopers/conrod/pull/232, though I don't know if it's relevant.

**Comment by bvssvni** [comment]
I am updating glium_graphics from FreeType to RustType by copying code from gfx_graphics, and found a similar artifact. There are no artifacts in the FreeType version, but they appear in the RustType version. PR: https://github.com/PistonDevelopers/glium_graphics/pull/135

Since RustType renders a single glyph, the artifacts are not caused by other characters in the same font.

There is no difference in how the characters are rendered as images in glium_graphics between the FreeType and the RustType version.

By looking the following screenshot, you can see artifacts consistent with the wrapping side shape of the same glyph:

![screen shot 2016-10-31 at 18 02 54](https://cloud.githubusercontent.com/assets/1743862/19863373/50664af6-9f94-11e6-9bff-bba697dad7d6.png)

- "l" has a artifact line at the end
- The second "g" has artifacts at the beginning that matches the end

**Comment by bvssvni** [comment]
I also found that character offsets are calculated differently.

**Comment by mitchmindtree** [comment]
Woops! Accidentally pressed the assign button.

@bvssvni hmmm I don't have the time to look closer just yet, but just wanted to note that the example at the rusttype crate (also uses glutin and glium) works without artifacts on both my regular and retina displays. Perhaps it could be a good reference for checking where the errors lie? I copied it to get text working in conrod/examples/glutin_glium.rs, which also renders without artifacts on both of my displays.

> The RustType version has sub pixel precision in the x-offset

Perhaps the issue might have something to do with the way that piston-graphics `Image`s are drawn (piston-graphics' `Text` is [drawn using Image](https://github.com/PistonDevelopers/graphics/blob/master/src/text.rs#L71)). As you mention, RustType uses sub pixel precision, however the `Image` restricts its `source_rectangle` to type `i32` (see [here](https://github.com/PistonDevelopers/graphics/blob/master/src/types.rs#L18) and [here](https://github.com/PistonDevelopers/graphics/blob/master/src/image.rs#L151))? Perhaps the `Image`s `SourceRectangle` should be changed to support sub-pixel offsets? This is what I suggested might be the issue in #787, which I linked to in my previous comment in this thread.

**Comment by bvssvni** [comment]
Still getting the same artifacts, but I believe source rectangle should support sub-pixel precision anyway. My current hypothesis is the problem is caused by OpenGL uv wrapping. This might require some design changes to allow different types of wrapping.

To continue I need to update the ecosystem first, because some breaking changes are making it hard to test stuff. I'll merge the RustType version in glium_graphics, even though it has artifacts, and fix it afterwards.

**Comment by bvssvni** [comment]
It was caused by uv wrapping. Also needed a one-pixel margin to avoid artifacts when animating text.

Found a peculiar minor issue in Glium https://github.com/tomaka/glium/issues/1536

Fix for glium_graphics: https://github.com/PistonDevelopers/glium_graphics/pull/136

**Comment by mitchmindtree** [comment]
Nice work on finding the issue :)

Out of curiosity, why was a one-pixel margin needed to avoid artifacts?

**Comment by bvssvni** [comment]
@mitchmindtree When animating text and the texture gets sampled at the edge, you see an artifact because the color is clamped to the edge. For example, an "H" gets thicker along the edge in some frames.

**Comment by bvssvni** [comment]
This has been fixed for a while. I updated my comment above to include the other PRs.

Closing.
