### ISSUE TITLE
When clearing the text in a text box, it panics

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#517]
Seems to be caused by https://github.com/PistonDevelopers/conrod/blob/master/src/widget/text_box.rs#L172

I haven't tested this myself (was reported on IRC), but worth checking the logic.

**Comment by stratact** [comment]
Here an example when you type in text and hit enter to clear the text, it throws the assert:
http://is.gd/jEDxzI

**Comment by mitchmindtree** [comment]
I think we just need to change it so that rather than panicing if the index is out of range (i.e. which might occur because the user has mutated the string between calls to `TextBox`, like in @stratact 's example above), we just snap the cursor index to `(.len() - 1)`.

**Comment by stratact** [comment]
Hi @mitchmindtree,

Does that mean, like from this line here: https://github.com/PistonDevelopers/conrod/blob/master/src/widget/text_box.rs#L409

that the `- 1` needs to be suffixed, as `cursor.start - 1` and `cursor.end - 1`?
