### ISSUE TITLE
Storing a reference to conrod::Ui

### ISSUE THREAD

**Issue by 6D65** [PistonDevelopers/conrod#518]
Hi,

First things first, i'm a Rust noob and i'm still fighting with the borrow checker. 

I'm trying to move the ui drawing into it's own module with a struct that holds the data.

I keep getting the borrow checker error, though it don't really see why this wouldn't work. I had a peek at the implementation for the Ui::new([link](https://github.com/PistonDevelopers/conrod/blob/65a1885e634abee684b8e318fd479458adf9c88e/src/ui.rs#L131-L152)) function and it doesn't seem to have any lifetime annotations.

Creating a value on the heap in new, and returning a reference most likely won't work, since the value will be freed when the scope for new ends. The only legit way to get a constructor working seems this.

Am I missing something?
Is this usage even possible?

Thanks

```shell
ui.rs:16:22: 16:32 error: wrong number of lifetime parameters: expected 1, found 0 [E0107]
ui.rs:16   pub ui: conrod::Ui<GlyphCache>,
                              ^~~~~~~~~~
ui.rs:16:22: 16:32 help: run `rustc --explain E0107` to see a detailed explanation
error: aborting due to previous error
```

```Rust
pub struct MainUi {
  pub gl: GlGraphics,
  pub ui: conrod::Ui<GlyphCache>,
  pub count: u16
}

impl MainUi {
  pub fn new(gl: GlGraphics) -> MainUi {
    let assets = find_folder::Search::ParentsThenKids(3, 3)
    .for_folder("assets").unwrap();

    let font_path = assets.join("FiraSans-Regular.ttf");
    let theme = Theme::default();
    let glyph_cache = GlyphCache::new(&font_path).unwrap();

    MainUi {
      ui: conrod::Ui::new(glyph_cache, theme),
      gl: gl,
      count: 0
    }
  }
}



//----- call it in the main function

let mut main_ui = ui::MainUi::new(GlGraphics::new(opengl));
```

**Comment by jarrett** [comment]
Here's a bit of background info. (Sorry if you already know all this. I found it confusing t first.) Conrod is based on Piston. Piston, being highly modular, supports multiple "backends." A backend is something like  [`opengl_graphics`](https://github.com/pistondevelopers/opengl_graphics), [`gfx_graphics`](https://github.com/pistondevelopers/gfx_graphics), or [`glium_graphics`](https://github.com/pistondevelopers/glium_graphics). The purpose of the backend is to provide a lot of low-level functionality, such as font handling.

Each backend has its own implementation of the `graphics::character::CharacterCache` trait, which is defined by Piston. The structs that implement `CharacterCache` are by convention called `GlypheCache`.

I see that you're using `opengl_graphics` as your backend. Its `GlypheCache` is defined [here](https://github.com/PistonDevelopers/opengl_graphics/blob/master/src/glyph_cache.rs). Here's the important part for your question:

    pub struct GlyphCache<'a> {
        /// The font face.
        pub face: freetype::Face<'a>,
        data: HashMap<FontSize, HashMap<char, Rc<Character>>>,
    }

Notice that the struct is defined as having a lifetime parameter named `'a`. As with type params, lifetime params must be included when you write out the type in, say, a struct definition. Thus:

    // error: wrong number of lifetime parameters: expected 1, found 0
    let cache: GlypheCache;
    
    // This is valid because it has the lifetime parameter.
    let cache: GlypheCache<'a>;

When you define a struct, any type or lifetime params you use inside the struct definition have to be included after the name of the struct and after the keyword `impl`. Thus:
    
    struct MyStruct<'a> {
        cache: GlypheCache<'a>
    }

    impl<'a> MyStruct {
    }

Putting it all together in your example, you can do something like this:

    extern crate opengl_graphics;
    extern crate conrod;

    use std::path::Path;
    use opengl_graphics::GlGraphics;
    use opengl_graphics::glyph_cache::GlyphCache;
    use conrod::{Ui, Theme};

    pub struct MainUi<'a> {
        pub gl: GlGraphics,
        pub ui: conrod::Ui<GlyphCache<'a>>,
        pub count: u16
    }

    impl<'a> MainUi<'a> {
        pub fn new(gl: GlGraphics) -> MainUi<'a> {
            let theme = Theme::default();
            let glyph_cache = GlyphCache::new(
                &Path::new("assets/FiraSans-Regular.ttf")
            ).unwrap();

            MainUi {
                ui: conrod::Ui::new(glyph_cache, theme),
                gl: gl,
                count: 0
            }
        }
    }

    fn main() {
        // ...
    }

**Comment by 6D65** [comment]
Thank you @jarrett . That's exactly what I was looking for. Went for this solution and it worked. Closing this now.
