### ISSUE TITLE
Change `Ui::draw` to only re-draw if any of the Widgets have new `Element`s.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#530]
So far Conrod has pretty poor performance as it redraws its graphics every frame!

For folks doing purely GUI applications, this is clearly not desired, and they'd almost definitely prefer to just redraw when some widget actually requires it.

I'm guessing that this would reduce conrod's --release CPU usage from around 25% right down to barely noticeable, as the vast majority of time is currently spent within the elmesque/piston-graphics draw calls.

It's very easy to add (I'm doing it now) but I just thought I'd open a discussion on what the best naming for this might be?

So far my plan is to change `Ui::draw` to only re-draw if some `Widget`'s `draw` function is called (which only gets called if it returns a new state from `update`. When a widget is updated with a new state, it calls `ui.needs_redraw` automatically which will cause the `Ui` to redraw all the `Element`s when `Ui::draw` is called. We could do something similar for the upcoming `Ui::element` method (mentioned here #527 @jarrett ) which could return `Option<Element>` - it would return `Some(Element)` if a redraw was needed, otherwise returning `None`.

The `Ui::needs_redraw` method would be public, so if for some reason a user needed conrod to redraw everything they could call this before calling `Ui::draw`.

An alternative would be to leave `Ui::draw` to behave as it does currently, and add a separate method called `Ui::draw_if_needed` which behaves as described above. Come to think of it, this is probably a better option as it has less chance of breaking people's code and is more descriptive of the behaviour. We would change all examples to use this method as they are purely GUI (there is no other graphics stuff going on other than conrod's).

Any other ideas/thoughts welcome :+1:

**Comment by bvssvni** [comment]
`draw_if_needed` sounds nice. It explains how it behaves in the same method. No need to look up something else or forcing that behavior on all applications.

**Comment by stratact** [comment]
@bvssvni, it was pointed out earlier on IRC, that the `needed` part doesn't actually describe the context what the method is doing. Changing the name to `draw_if_changed` is more accurate, since the point is for the UI to wait for something to change in order to draw again.
