### ISSUE TITLE
Add `#![deny(unsafe)]` to lib.rs

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#544]
There should really be no reason to need unsafe code in conrod due to its high level nature - adding this lint might make it clearer to contributors?

**Comment by bvssvni** [comment]
That would be nice.

**Comment by TheNeikos** [comment]
+1 Sounds like a good idea

**Comment by zummenix** [comment]
That's doesn't work for me:
```
src/lib.rs:9:9: 9:15 error: expected identifier, found keyword `unsafe`
src/lib.rs:9 #![deny(unsafe)]
                     ^~~~~~
error: aborting due to previous error
```
Am I doing something wrong?

@Gankro mentioned `#![forbid(unsafe)]` in the [presentation](https://air.mozilla.org/Alexis_Beingessner/).

**Comment by zummenix** [comment]
Looks like it called `unsafe_code`, so we can use `#![deny(unsafe_code)]`
or `#![forbid(unsafe_code)]`.

**Comment by Gankro** [comment]
Forbid should definitely be preferred if you're serious about unsafe.
