### ISSUE TITLE
Playback widget

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#56]
It would be nice to have a widget that could be used to control playback of audio/video streams.

**Comment by bvssvni** [comment]
This would probably fit better as composed of multiple widgets, and should into another library.

**Comment by jingle1000** [comment]
Is there currently a widget that can do this or has it not been implemented yet?
I've tried using gstreamer, ffmpeg and other c library bindings and the development process has been awful. It would be nice to see a rust GUI library support this feature.
