### ISSUE TITLE
Panic when drawing ui

### ISSUE THREAD

**Issue by burtonageo** [PistonDevelopers/conrod#567]
When I call `conrod::Ui.draw()`, I get a panic on launch.

* Code: [link](https://github.com/burtonageo/conrod-bug)

* Stack trace:
    
        thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:365
        stack backtrace:
        1:        0x10b5d979e - sys::backtrace::tracing::imp::write::h2a3c1b1b2302b0b0W5s
        2:        0x10b5d8ec1 - panicking::log_panic::closure.38918
        3:        0x10b5d6814 - panicking::log_panic::h9fdebde30b454fb57Uw
        4:        0x10b5d49c6 - sys_common::unwind::begin_unwind_inner::hd85c5bc2336b01e6u8r
        5:        0x10b5d5035 - sys_common::unwind::begin_unwind_fmt::h85dfaddf9453fbf9A7r
        6:        0x10b5dc1ac - panicking::panic_fmt::he7d9e7f3307a108awZK
        7:        0x10b5dbd9c - panicking::panic::h17e01eda935fc2473XK
        8:        0x10b5d3118 - element::layers::h08a3957dabd3d2825rb
        9:        0x10b5caa2e - graph::Graph::element::h491d198c877268303Xa
        10:       0x10b593e8b - screens::menuscreen::MenuScreen.Render::render::h6c679d7a12ee9d5enma
        11:       0x10b59defa - main::h6ffaab86b6ee16a2GNa
        12:       0x10b5d7b52 - sys_common::unwind::try::try_fn::h7398704419810616534
        13:       0x10b5d7758 - __rust_try
        14:       0x10b5a0e72 - main
        An unknown error occurred

* rustc version: `1.5.0-nightly (219eca11b 2015-09-27)`

* Operating system: Mac OS X 10.10.5

**Comment by burtonageo** [comment]
It seems to work if I draw another widget on top of the ui

**Comment by mitchmindtree** [comment]
This is a bug in elmesque - I fixed it last night but haven't had a chance to publish the changes yet - will do so now.
