### ISSUE TITLE
Store all input `Event`s between updates so that they can be inspected by `Widget`s

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#569]
Right now, `Widget`s can only check the present state of the `Mouse`. It would probably be more useful to store each of the input events that have occurred between each update in a single buffer along with methods for quickly filtering through it in useful ways.

This would also allow for fixing #384 .

**Comment by bvssvni** [comment]
Is it possible to store `E: GenericEvent`?

I guess this will be a problem if people are calling Conrod with two different types of events.

**Comment by bvssvni** [comment]
We could map events back to `Input` and store them in a `Vec<Input>`.

**Comment by mitchmindtree** [comment]
@bvssvni yeah I was imagining a `Vec<Input>` :)

Perhaps in a wrapper type that offers a collection of methods yielding different useful iterators over the kinds of input?

**Comment by bvssvni** [comment]
Can we do this in a loop in `set_widget`? It seems possible to call `Widget::update` multiple times.

**Comment by mitchmindtree** [comment]
@bvssvni hmm I'm not sure what you mean?

I think it might be a bit too expensive to call `Widget::update` multiple times in a loop, as some widgets might have complex `update`s. Then again, I guess it would hardly ever get called more than once as it would be rare to have more than one or two `Input` events between `update`s.

I imagined the `Ui` would store the `Vec<Input>` and each time `Ui::handle_event` is called with an `Input`, it would add the event to the stack. The `Vec<Input>` would be reset between updates.

The widgets would receive a view of this `Vec<Input>` (perhaps via the wrapper type providing helper methods as described in my previous comment) within the `UserInput` type that is given via the `UpdateArgs` when `Widget::update` is called. That way each time a widget's update is called, it just handles the events that happened since its last update.

**Comment by bvssvni** [comment]
The behavior of a widget should not depend on which partition of events it received. For example, if the widget capturing the mouse is determined in `set_widget`, then it can't change in `Widget::update`.

**Comment by mitchmindtree** [comment]
hmm I'm still not following? The widget that's capturing the mouse *is* currently determined within the `Widget::update`, i.e. [here](https://github.com/PistonDevelopers/conrod/blob/master/src/widget/button.rs#L151).

**Comment by bvssvni** [comment]
Ok.

**Comment by bvssvni** [comment]
@mitchmindtree I am trying to get up to speed on the source. Are you on IRC?

**Comment by mitchmindtree** [comment]
@bvssvni sorry I missed you! I've been busy with work as well as a masters proposal :) I'll try and hang about IRC tonight in case you still want to discuss :+1:

**Comment by bvssvni** [comment]
@mitchmindtree Thanks! Of course you should prioritize your master degree...

**Comment by bvssvni** [comment]
@mitchmindtree The thing I want to talk about is the details around the event logic. I understand what is happening but not enough to plan changes.

**Comment by mitchmindtree** [comment]
Closed by #684.
