### ISSUE TITLE
all_widgets example hangs when selecting "Green" or "Blue" in drop down

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#572]
I haven't looked at the code yet.

**Comment by mitchmindtree** [comment]
From #570 

> Note: there is still an issue where the DropDownList doesn't crop properly to its scroll area - it now also eternally captures the mouse if you click one of the buttons outside the proper scroll area. The over-arching bug existed before this however, so it will be addressed in a separate PR.

In the all_widgets example, "Green" and "Blue" are outside the scroll area (which is set to have a `.max_visisble_num_items(3)`) - the DropDownList should be cropping its children to the scrollable area, but for some reason in all_widgets it does not. (In my own synth editor code, the cropping works correctly, so I'm not yet sure why it's not working in all_widgets).

**Comment by bvssvni** [comment]
It is probably because opengl_graphics doesn't support the draw state yet.

**Comment by mitchmindtree** [comment]
oooOOoooooohhhhhhh my gosh. This has been confusing me for ages haha - would not have thought to check that. Good call :)

**Comment by mitchmindtree** [comment]
That would account for the cropping issue, but I guess that would mean there's still another issue with non-displayed, scrolled `Widget`s being triggered. I'll look into it.
