### ISSUE TITLE
Conrod should expose (or at least re-export) everything a user needs to use their own graphics and event backends.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#576]
Right now conrod is already quite generic in it's Graphics and Events dependencies, however it can seem quite confusing and messy to a user as it requires using various different crates from the Piston eco-system.

I think we could solve this issue quite nicely by exposing and re-exporting everything that a user needs to use their own Graphics and Events backends through conrod itself - perhaps via a `backend` module, which re-exports (and inline documents) the `Graphics` and `Event` traits. We should also provide a demonstration of how to implement these manually, perhaps with a basic example of implementing them directly on `glutin` and `glium`.

Really, a user should not need to import any crates besides conrod itself when they desire to use conrod within their own project.

We quite often get feedback critiquing the complexity of the eco-system that surrounds conrod, i.e. just now in IRC:

> OmniMancer - I think having an  interface that doesnt require even indirectly depedning on piston would possibly be helpful

> jpernst - yeah, i evaluated conrod for use on top of my framework but decided against it because it pulls in too much

**Comment by bvssvni** [comment]
This is a good idea. It could help people looking for using Conrod in this way. For example, if you are developing your own framework and want an UI.

**Comment by bvssvni** [comment]
To address the confusion problem, I've written an overview of Piston https://github.com/PistonDevelopers/piston/wiki/Piston-overview.

**Comment by mitchmindtree** [comment]
Nice one, the overview looks great :+1:
