### ISSUE TITLE
Custom OpenGL rendering?

### ISSUE THREAD

**Issue by yggie** [PistonDevelopers/conrod#583]
Are there any plans to allow custom OpenGL renderings on the window? I am struggling to find a good GUI library in Rust to go on top of an OpenGL application…

**Comment by bvssvni** [comment]
You can use the [opengl_graphics](https://github.com/pistondevelopers/opengl_graphics) backend.

**Comment by yggie** [comment]
Would it be safe to use with the widgets in `conrod`? I haven’t looked at it in depth, but I am worried that direct calls to OpenGL might mess things up for `conrod`.

**Comment by bvssvni** [comment]
You need reset the state before calling Conrod.

**Comment by yggie** [comment]
ah of course! silly me :grin:, it became pretty obvious after looking carefully through the examples, thanks for your help!
