### ISSUE TITLE
Make scrollbar in drop down always visible

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#585]
Currently it is hard to see whether there are more items to select from than the ones that are visible. By making the scrollbar always visible, it is easier to see whether there are more items.

**Comment by mitchmindtree** [comment]
Great point :+1: I can probably do this after #577

**Comment by mitchmindtree** [comment]
Closing this as there are now [methods](https://docs.rs/conrod/0.55.0/conrod/widget/drop_down_list/struct.DropDownList.html#method.scrollbar_next_to) for specifying whether the scrollbar should only appear when hovered or if it should always appear next to the list.
