### ISSUE TITLE
Provide a `Ui` method that returns whether or not the mouse is over a `Widget`.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#611]
Perhaps so that it may be used like:

``` rust
if ui.widget_under_mouse().is_none() {
    // Handle other mouse stuff.
}
```

**Comment by Drakulix** [comment]
I have a similar use case for this functionality and #612 .
Both are tagged *easy*, but I have not a lot experience with conrod's code base.

Could you outline the basic steps to implement this?
Then I would craft a PR later.

**Comment by mitchmindtree** [comment]
Hey @Drakulix. you should be able to access this today via
```rust
ui.global_input.current.widget_under_mouse
```
Currently `global_input` is a `pub` field on the `Ui`, however I think we should probably make it private and add a `.global_input()` method that returns a reference to the global input instead to avoid having folks mutate that state.

Anyways, I think this `Ui::widget_under_mouse` method could look something like this:
```rust
pub fn widget_under_mouse(&self) -> Option<widget::Id> {
    self.global_input.current.widget_under_mouse
}
```
