### ISSUE TITLE
Remove the need for `Form` and `Element` by representing graphics fundamentals as `Widget`s and taking advantage of widget layout.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#617]
This seems so obvious in hindsight!

See original idea [here](https://github.com/PistonDevelopers/conrod/issues/616#issuecomment-153973156).

Edit: I think the reason this wasn't obvious before is because conrod's layout only recently became very powerful.

**Comment by bvssvni** [comment]
I think that's a good idea! Hope it isn't too much work...
