### ISSUE TITLE
WidgetMatrix bug in all_widgets.rs

### ISSUE THREAD

**Issue by gkbrk** [PistonDevelopers/conrod#619]
When you click a box in the all_widgets.rs example, only the first block gets toggled. I presume the bug is because of this line [here](https://github.com/PistonDevelopers/conrod/blob/866bd0d1fbd743721c1795ac654fe974f0f891e7/examples/all_widgets.rs#L362), when the closure runs it only changes the last value of col and row instead of the col and row when the closure was created.

**Comment by mitchmindtree** [comment]
Hmmm I can't seem to be able to recreate this issue on my end?

That code snippet looks fine to me also - note that a `Toggle` is created for every element in the `WidgetMatrix`, and `col` and `row` are the column and row numbers for that element.

Sorry if I'm misunderstanding the issue!

**Comment by gkbrk** [comment]
I made a gif of what's happening:

![Conrod Demo GIF](https://i.imgur.com/Fq9X8kP.gif)

**Comment by waynenilsen** [comment]
I'm able to recreate the issue. I can verify that it was not there as of my PR #586

**Comment by mitchmindtree** [comment]
Thanks a lot for the gif! This is super strange! Even as of testing #623 I am still unable to recreate this issue. Perhaps there's some sort of cross-platform behavioural issue going on or something? I'm finding it difficult to imagine what it might be...

@bvssvni if you get a chance at all, could you test the latest version of conrod's all_widgets.rs example?

@gkbrk @waynenilsen what version of rustc and platform are you using?

I'm on osx 10.10.5, running `rustc 1.4.0 (8ab8581f6 2015-10-27)` using click press on my MBP's trackpad.

**Comment by gkbrk** [comment]
Linux Mint KDE, running `rustc 1.4.0 (8ab8581f6 2015-10-27)`.

**Comment by waynenilsen** [comment]
I'm on a vm running Ubuntu XFCE 15.4 inside of windows 10 running rust beta, don't have access to the machine so i can't say what exact version of rustc i'm running. I was clicking left click with the mouse

**Comment by xilec** [comment]
I had gave the same problem after updating to the last version. When I check it 5 days ago, it worked fine.

Windows 8.1
rustc 1.5.0-beta.2 (b0f440163 2015-10-28) 
and
rustc 1.4.0 (8ab8581f6 2015-10-27)

Bug is reproduced olny in debug version. In release version it works correctly.

**Comment by bvssvni** [comment]
I also get this bug on `rustc 1.6.0-nightly (5b4986fa5 2015-11-08)` OSX 10.9.5. Works in release mode.

**Comment by gkbrk** [comment]
I can confirm that it works when compiled on release mode.

**Comment by mitchmindtree** [comment]
Oh wow, I've only been compiling in release mode so it makes sense that I've missed this. Confirmed it happens for me in debug also.

Anyone have any ideas why this might only occur in debug?

**Comment by mitchmindtree** [comment]
Interestingly, if I add some printing to the `Toggle`'s react closure, like so:

```rust
    // A demonstration using widget_matrix to easily draw
    // a matrix of any kind of widget.
    let (cols, rows) = (8, 8);
    WidgetMatrix::new(cols, rows)
        .down(20.0)
        .dimensions(260.0, 260.0) // matrix width and height.
        .each_widget(|n, col: usize, row: usize| { // called for every matrix elem.

            // Color effect for fun.
            let (r, g, b, a) = (
                0.5 + (col as f32 / cols as f32) / 2.0,
                0.75,
                1.0 - (row as f32 / rows as f32) / 2.0,
                1.0
            );

            // Now return the widget we want to set in each element position.
            // You can return any type that implements `Widget`.
            // The returned widget will automatically be positioned and sized to the matrix
            // element's rectangle.
            Toggle::new(demo.bool_matrix[col][row])
                .rgba(r, g, b, a)
                .frame(demo.frame_width)
                .react(|new_val: bool| {
                    println!("n: {:?}, col: {:?}, row: {:?}", n, col, row);
                    demo.bool_matrix[col][row] = new_val
                })
        })
        .set(TOGGLE_MATRIX, ui);

```

It prints a crazy number for `n` in debug when pressing random toggles:
```
n: 140734581765121, col: 0, row: 0
n: 140734581765121, col: 0, row: 0
```

However in release it behaves correctly:
```
n: 41, col: 5, row: 1
n: 0, col: 0, row: 0
n: 2, col: 0, row: 2
```

**Comment by mitchmindtree** [comment]
Moving the matrix, col and row into `Toggle`'s react closure seems to fix this:

```rust

    // A demonstration using widget_matrix to easily draw
    // a matrix of any kind of widget.
    let (cols, rows) = (8, 8);
    WidgetMatrix::new(cols, rows)
        .down(20.0)
        .dimensions(260.0, 260.0) // matrix width and height.
        .each_widget(|_n, col: usize, row: usize| { // called for every matrix elem.

            // Color effect for fun.
            let (r, g, b, a) = (
                0.5 + (col as f32 / cols as f32) / 2.0,
                0.75,
                1.0 - (row as f32 / rows as f32) / 2.0,
                1.0
            );

            // Now return the widget we want to set in each element position.
            // You can return any type that implements `Widget`.
            // The returned widget will automatically be positioned and sized to the matrix
            // element's rectangle.
            let val = demo.bool_matrix[col][row];
            let mat = &mut demo.bool_matrix;
            Toggle::new(val)
                .rgba(r, g, b, a)
                .frame(demo.frame_width)
                .react(move |new_val: bool| mat[col][row] = new_val)
        })
        .set(TOGGLE_MATRIX, ui);
```
