### ISSUE TITLE
TextArea Widget

### ISSUE THREAD

**Issue by indiv0** [PistonDevelopers/conrod#62]
- Allows for creation and editing of text

Would this be in the scope of conrod?

**Comment by gkbrk** [comment]
Any status updates on the TextArea widget?

**Comment by mitchmindtree** [comment]
It should make it in with [this PR](https://github.com/PistonDevelopers/conrod/pull/626), (see [this comment](https://github.com/PistonDevelopers/conrod/pull/626#issuecomment-161161983)) (though I'm not 100% sure i'll have time to get the editing going too).

**Comment by mitchmindtree** [comment]
This has since been added as a general [`TextEdit` widget](https://docs.rs/conrod/0.50.0/conrod/widget/text_edit/struct.TextEdit.html). For a read-only version, see the [`Text` widget](https://docs.rs/conrod/0.50.0/conrod/widget/primitive/text/struct.Text.html).
