### ISSUE TITLE
Travis build badge is showing `failing` despite both builds being successful?

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#621]

**Comment by gkbrk** [comment]
Travis will probably update the image after the next commit and its tests. Or if there is an option, you can try re-running the tests manually.

**Comment by mitchmindtree** [comment]
Seems to still be failing despite the new successful build in #623 being merged

**Comment by mitchmindtree** [comment]
Ahh no, it seems that it's running another build now that #623 has been merged. Shall see what happens afterwards.

**Comment by mitchmindtree** [comment]
Ok, closed by #623.
