### ISSUE TITLE
Change the README's dependency graph picture to only show `dependencies` and not `dev-dependencies`?

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#625]
At the moment the picture makes conrod's dependency eco-system look super complex, when really it's quite small.

**Comment by bvssvni** [comment]
I generated a new graph, which looks even more insanely large.

**Comment by bvssvni** [comment]
![cargo](https://cloud.githubusercontent.com/assets/1743862/11130060/4e7c118a-8983-11e5-960a-10007fc60dd0.png)

Posting it here, just for giggles.

**Comment by bvssvni** [comment]
I reported this earlier https://github.com/maxsnew/cargo-dot/issues/13. The problem is that cargo-dot uses Cargo.lock to extract dependencies, which does not contain any information separating dependencies from dev-dependencies.

**Comment by bvssvni** [comment]
Could use [cargo-graph](https://github.com/kbknapp/cargo-graph) instead. There was a problem with filtering dev-dependencies, https://github.com/kbknapp/cargo-graph/issues/4, but this is now fixed.

**Comment by mitchmindtree** [comment]
This is no longer displayed so going to close this.
