### ISSUE TITLE
Dynamically creating widgets

### ISSUE THREAD

**Issue by maun** [PistonDevelopers/conrod#627]
My application requires that i can dynamically create widgets by pressing buttons. Can this be done with static widget ids?

If not, can I help somehow to make this possible?

**Comment by bvssvni** [comment]
This should be possible.

**Comment by mitchmindtree** [comment]
@maun there are a couple ways you could do this:

**Option 1**. Prepare a bounded range of `WidgetId`s using the `widget_ids!` macro, i.e.
```rust
widget_ids! {
    MY_WIDGET with 100,
}
```
This would allow you to dynamically create up to 100 `MyWidget`s in a `for` loop for example, where you give the ids like this `.set(MY_WIDGET + i, &mut ui)`. This is mainly only useful for widgets that can be dynamically instantiated over some range though.

**Option 2**. Make you're own custom type implementing `Widget` that wraps the process of dynamically instantiating widgets. Custom widgets are able to dynamically generate widgets internally and store them in their associated `Widget::State` type for re-use. I'm currently working on a PR which will change all of conrod's internal widgets to do this (apart from a few primitive widgets) so I should hopefully have some examples for you soon. I think the `DropDownList` currently does this - it dynamically generates a `WidgetId` for each list item, growing the `Vec` if more items appear in the given list.

**Comment by maun** [comment]
Thanks :-) I will try it out when I have time to work on this again
