### ISSUE TITLE
Envelop editor causes crash when all points are removed by right click

### ISSUE THREAD

**Issue by anarendiran** [PistonDevelopers/conrod#628]
Removing all the points in the envelop editor causes the program to crash.

     Running `target/debug/examples/all_widgets`
     thread '<main>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/widget/envelope_editor.rs:633
     Process didn't exit successfully: `target/debug/examples/all_widgets` (exit code: 101)

**Comment by mitchmindtree** [comment]
Thanks for the issue, I'll fix this in #626 if no one gets to it first.
