### ISSUE TITLE
`Texture`/`Image` primitive widget.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#647]
This primitive could perhaps then be used as the basis for an `Image` widget? Will draft this up further soon.

**Comment by mitchmindtree** [comment]
Perhaps it's better to just do this as a primitve `Image` widget from the ground up? This way we can just use the piston graphics Image type directly?

**Comment by daogangtang** [comment]
I think we can do it as `Image` first, and then make the Image widget out.

**Comment by mitchmindtree** [comment]
@daogangtang I just so happen to be working on this right now! Just about finished, will do a PR either within the hour or some time tomorrow :+1:

**Comment by daogangtang** [comment]
nice, focus on this project, i want to use it on mobile phone. 
I have some naive GUI implimentation experience on sdl before, so i think maybe there is something i can do for conrod.

https://github.com/xenyinzen/stk
