### ISSUE TITLE
Change names `Point` -> `Xy` and `Dimensions` -> `Wh`?

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#652]
Both type aliases are quite common throughout conrod and their names as-is can get a little verbose.

I recently started using `xy` and `wh` when naming a `Point` or `Dimensions` binding locally, and i've found it to be nice and ergonomic, perhaps even a little clearer. This lead to the idea of changing type names also.

This would also remove a pain point I come across quite often in my own libs - the conflict between envelope `Point`s and conrod's coordinate `Point`s.

The name `Xy` clarifies that it is a two dimensional *xy* coordinate representation, removing any ambiguity over the number of dimensions. `Wh` is a similar case, specifying not only that we are talking about two dimensions, but that we're specifically talking about the width and height.

**Comment by bvssvni** [comment]
I think using types `Point` and `Dimensions` is OK. Using `xy` and `wh` as names is fine, but it might become a little confusing using them as types.

**Comment by mitchmindtree** [comment]
Ok, will leave them for now.
