### ISSUE TITLE
crates.io not updated to latest version

### ISSUE THREAD

**Issue by sidred** [PistonDevelopers/conrod#661]
Looks like the color definitions have not be updated in the 0.28.0 version of the crate. Getting an undefined error with the following code:

```
extern crate conrod;

fn main() {
    println!("{:?}", conrod::color::BLUE);
}
```

Replacing the crate with the github link  works.

Checking the multirust cargo src shows conrod version at 0.28.0 with the old color definitions. I even tried uninstalling rust and clearing all the cached cargo data.

**Comment by mitchmindtree** [comment]
Yes, the latest changes (changing color functions to const values) haven't been published yet. I'll do this today along with some other breaking changes I have planned as **0.29.0** :)

If you depend on the latest crates.io version of conrod (0.28.0), your above example should work as 
```rust
extern crate conrod;

fn main() {
    println!("{:?}", conrod::color::blue());
}
```

I'll close this when I publish the new version :+1:

**Comment by sidred** [comment]
Thanks. I ran into this issue, trying to modify the canvas example and I wasn't sure if the changes were supposed to be part of the 0.28.0 version.
