### ISSUE TITLE
Rename graph::algo::`visible_area_of_widget` to `cropped_area_of_widget`.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#666]
`visible_area_of_widget` is too general, and could be re-used later for an algo that *actually* finds the total visible area of the widget (i.e. that considers window size, covering, non-blended widgets, etc).

**Comment by BenMcH** [comment]
Should this also change method names such as visible_area_of_widget_maybe_within_depth?

**Comment by mitchmindtree** [comment]
Yep.

**Comment by BenMcH** [comment]
I just used a find and replace and it didnt seem to break, Mitch. Let's see what travis has to say.

**Comment by mitchmindtree** [comment]
Closed by #667.

**Comment by mitchmindtree** [comment]
Hmmm @BenMcH what are your thoughts on this:

I'm now wondering whether or not the function name actually be `uncropped_area_of_widget`?

What the function actually does is return the rectangular area of the widget that is still visible after it has been cropped (at the moment, cropping only occurs when cropping widgets to a scrollable container).

Which do you think makes more sense for this behaviour: `cropped_area_of_widget` or `uncropped_area_of_widget`? Or maybe there's something else that is more suited?

**Comment by BenMcH** [comment]
Hmm, this is an interesting problem @mitchmindtree. I think that for this case, I like cropped_area_of_widget because uncropped_area_of_widget would seem to return the full size of the widget before the crop into a scrollable container.

**Comment by mitchmindtree** [comment]
Oh yes, good point :+1:
