### ISSUE TITLE
Reduce `Style` boilerplate for Widget implementations.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#672]
Possibly the most tedious thing about implementing widgets at the moment is the associated `Style` type. The `Style` struct always contains necessary graphical styling information, i.e. `color`, `label_color`, `label_font_size`, and so on.

Problem
-----------

An example of the boilerplate:

At the moment, if a user would like to opt-in to having their widget be `Colorable` they need to do several things:

- Add an `Option<Color>` field to their style so that a user can either build their widget with a color or fall back to some default.
- Implement the `Colorable` trait (the `color` method), allowing the widget to use all [the provided methods](http://docs.piston.rs/conrod/conrod/color/trait.Colorable.html).
- Implement a `color` method on their widget's `Style` type that retrieves the color if one was given, or falls back to some default. This default is almost always:
    - Check to see if a default color is specified within the theme. If so, use that.
    - Use the fallback `theme.shape_color` field. For other, more unique style fields, some const default would then be used for fallback instead.

In any language with field inheritance, this would be a much simpler process, however it looks like it will be a while yet before rust gets a feature along these lines. There's no harm in thinking of alternative options now.

Possible Solution - `macro_rules!`?
-----------------------------

The boilerplate involved when it comes to `Style` has been annoying me to the point where i'm seriously considering polishing off my `macro_rules!` skillz in order to solve it. We'd first need a really nice, well-thought-out design that works in most cases and is quite readable.

A good way to try and solve this might be to start with a basic example of a current implementation, and try and write a macro_rules! api that could reduce the boilerplate. The following is a small typical example of a widget `Style` implementation with just two style fields, for some hypothetical widget `Foo`.

```rust
struct Foo {
    style: Style,
    ... // plenty of non-style related stuff.
}

struct Style {
    color: Option<Color>,
    unique: Option<Unique>,
}

impl Colorable for Foo {
    fn color(mut self, color: Color) -> Self {
        self.style.color = Some(color);
        self
    }
}

impl Foo {
    fn unique(mut self, unique: Unique) -> Self {
        self.style.unique = Some(unique);
        self
    }
}

impl Style {

    fn new() -> Self {
        Style {
            color: None,
            unique: None,
        }
    }

    /// Method for retrieving the Style's color or some default.
    fn color(&self, theme: &Theme) -> Self {
        self.color.or_else(|| theme.widget_style::<Style>(KIND).and_then(|default| {
            default.style.color
        })).unwrap_or(theme.shape_color)
    }

    /// Method for retrieving the Style's Unique or some default.
    fn unique(&self, theme: &Theme) -> Self {
        const DEFAULT: Unique = 42lfkj25g;
        self.color.or_else(|| theme.widget_style::<Style>(KIND).and_then(|default| {
            default.style.unique
        })).unwrap_or(DEFAULT)
    }

}
```

**Comment by mitchmindtree** [comment]
The macro must cover several things:

- Creation of the `Style` struct, specifying each field and its type.
- Implementation of a builder method on `Foo` for setting each field of `Style`. There must be an option for this method to be via either implementing a trait for a type (i.e. `impl Colorable for Foo` for the `color` method) or straight on the type itself (like `impl Foo` for the `unique` method).
- Implementation of the `Style` retrieval methods, i.e:

>    - Check to see if a default color is specified within the theme. If so, use that.
>    - Use the fallback theme.shape_color field. For other, more unique style fields, some const default would then be used for fallback instead.

**Comment by mitchmindtree** [comment]
How it might look to use:

```rust
widget_style!{
    KIND; // Need the unique `KIND` const to get style from the Theme.

    // Generates the struct with `Option` fields.
    Style {
        color: Color,
        unique: Unique,
    };

    // Generates both the builder and retrieval methods for
    // each `<ident>: <ty> -> <trait/impl> <ident>` in unique impl blocks.
    color: Color -> trait Colorable;
    unique: Unique -> impl Foo;
};
```

**Comment by mitchmindtree** [comment]
I'm working on this now, got the first half done! I think we might even be able to do something like this:

```rust
widget_style!{
    kind KIND; // First need the unique `KIND` const to get style from the Theme.

    // Generates the struct with `Option` fields and the `Style::new` method.
    Style {
        color: Color -> trait Colorable,
        unique: Unique -> impl Foo,
    };
}
```

Where only those "fields" that end with `-> <trait/impl> <ident>` token will have auto-generated builder/retrieval methods.

**Comment by mitchmindtree** [comment]
Oh yeah, we need a way of specifying a fallback/default for those methods on the occasion that the `Style`'s field is `None`. Perhaps something like:

```rust
widget_style!{
    kind KIND;

    Style {
        // <ident>: <ty> built via <trait/type> <ident> with fallback <expr>
        color: Color built via trait Colorable with fallback theme.shape_color,
        unique: Unique built via type Foo with fallback unique_default(),
    };
}
```

Might be getting a bit crazy here, but this would do the job! I'm open to other suggestions on all this ofc :)

**Comment by mitchmindtree** [comment]
I think for the first pass on this, I'm going to ignore generating the builder methods as this can get quite complex (i.e. they might need to be implemented on traits that have other non-style related methods).

So on first pass, we should be able to do something like this:

```rust
widget_style!{
    kind KIND;

    Style {
        // <ident>: <ty> with fallback <expr>
        color: Color with fallback theme.shape_color,
        unique: Unique with fallback unique_default(),
    }
}
```

I'm unsure about the `with fallback` tokens though, perhaps something easier like an arrow would still have pretty obvious behaviour? i.e.

```rust
Style {
    // <ident>: <ty> -> <expr>
    color: Color -> theme.shape_color,
    unique: Unique -> unique_default(),
 }
```

**Comment by mitchmindtree** [comment]
Ok, after a lot of iteration and massaging good ol' `macro_rules!`, this is what the Button's `Style` implementation looks like:

```rust

widget_style!{
    KIND;
    /// Unique styling for the Button.
    style Style {
        /// Color of the Button's pressable area.
        - color: Color { theme.shape_color },
        /// Width of the frame surrounding the button
        - frame: Scalar { theme.frame_width },
        /// The color of the frame.
        - frame_color: Color { theme.frame_color },
        /// The color of the Button's label.
        - label_color: Color { theme.label_color },
        /// The font size of the Button's label.
        - label_font_size: FontSize { theme.font_size_medium },
    }
}
```

Notes:
- the `style` keyword was necessary to differentiate the prior `meta` token (used for the doc attributes) from the following `ident` (in this case, `Style`), as macro_rules is unable to parse without a separating token.
- the `-` that precedes each field is for the same purpose: to help macro_rules parse the optional meta tokens and the first field ident consecutively.
- the part in the curly braces is the fallback aka default expression, which is only evaluated during retrieval of the field if the field is `None` and if there is no default within the `Theme`.

Bonuses:
- Documentation is an optional token
- trailing comma is optional

For an idea of how much coding is saved, here's all the previous style code for the Button that was replaced:

```rust
/// Styling for the Button, necessary for constructing its renderable Element.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct Style {
    /// Color of the Button's pressable area.
    pub maybe_color: Option<Color>,
    /// Width of the frame surrounding the button
    pub maybe_frame: Option<f64>,
    /// The color of the frame.
    pub maybe_frame_color: Option<Color>,
    /// The color of the Button's label.
    pub maybe_label_color: Option<Color>,
    /// The font size of the Button's label.
    pub maybe_label_font_size: Option<u32>,
}


impl Style {

    /// Construct the default Style.
    pub fn new() -> Style {
        Style {
            maybe_color: None,
            maybe_frame: None,
            maybe_frame_color: None,
            maybe_label_color: None,
            maybe_label_font_size: None,
        }
    }

    /// Get the Color for an Element.
    pub fn color(&self, theme: &Theme) -> Color {
        self.maybe_color.or(theme.widget_style::<Self>(KIND).map(|default| {
            default.style.maybe_color.unwrap_or(theme.shape_color)
        })).unwrap_or(theme.shape_color)
    }

    /// Get the frame for an Element.
    pub fn frame(&self, theme: &Theme) -> f64 {
        self.maybe_frame.or(theme.widget_style::<Self>(KIND).map(|default| {
            default.style.maybe_frame.unwrap_or(theme.frame_width)
        })).unwrap_or(theme.frame_width)
    }

    /// Get the frame Color for an Element.
    pub fn frame_color(&self, theme: &Theme) -> Color {
        self.maybe_frame_color.or(theme.widget_style::<Self>(KIND).map(|default| {
            default.style.maybe_frame_color.unwrap_or(theme.frame_color)
        })).unwrap_or(theme.frame_color)
    }

    /// Get the label Color for an Element.
    pub fn label_color(&self, theme: &Theme) -> Color {
        self.maybe_label_color.or(theme.widget_style::<Self>(KIND).map(|default| {
            default.style.maybe_label_color.unwrap_or(theme.label_color)
        })).unwrap_or(theme.label_color)
    }

    /// Get the label font size for an Element.
    pub fn label_font_size(&self, theme: &Theme) -> FontSize {
        self.maybe_label_font_size.or(theme.widget_style::<Self>(KIND).map(|default| {
            default.style.maybe_label_font_size.unwrap_or(theme.font_size_medium)
        })).unwrap_or(theme.font_size_medium)
    }

}
```

I think this is definitely looking like a big win!

**Comment by bvssvni** [comment]
This looks very elegant and handy!

**Comment by mitchmindtree** [comment]
@bvssvni thanks!

I've just about finished implementing this in #673. While working i've noticed that it's also probably about time we wrote a small, generic builder method macro. I imagine it'd be something pretty simple designed for use within an impl block, i.e:

```rust
builder_method!(self.style.color = color: Color);
```

that expands to

```rust
fn color(mut self, color: Color) -> Self {
    self.style.color = Some(color);
    self
}
```

t'would probably save a lot of lines, and is still quite clear behaviour wise.

**Comment by mitchmindtree** [comment]
I've fleshed out the `builder_method!` macro (along with a `builder_methods!` macro) in #674.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/conrod/pull/673 and https://github.com/PistonDevelopers/conrod/pull/674.
