### ISSUE TITLE
Proposal for managing the Noto font

### ISSUE THREAD

**Issue by winding-lines** [PistonDevelopers/conrod#678]
I created the create noto-font crate https://crates.io/crates/noto_font/ to manage the font for me. It will download it under ~/.fonts from the Google repo. This allows me to move the binary to various computers without having to worry about the font files or making an installer.

What do you think?

**Comment by BenMcH** [comment]
This would not work on Windows as we do not have an unzip command. I believe that conrod should stay OS independent. What do you think @mitchmindtree?

**Comment by winding-lines** [comment]
@BenMcH good point, it can be addressed by implementing the unzip on top of flate2. Another way may to embed the font inside the crate, although I have not seen other crates do this and it would increase the size of the executable.

Note that I was not proposing to include this crate in Conrod. I am interested on how other people solve this problem.

**Comment by BenMcH** [comment]
@winding-lines I have not had any issues with fonts. It might be that the font is included with windows (I do not know if this is the case) or if it just works. Conrod has not had any problems for me in displaying text.

**Comment by mitchmindtree** [comment]
Going to close this for now as discussion seems to have ended. Thanks for sharing though @winding-lines, I've personally just been including the font files where-ever I run gui apps that need them, though this does sound like a nice alternative!
