### ISSUE TITLE
Canvas::flow_left flows down instead of left

### ISSUE THREAD

**Issue by P1start** [PistonDevelopers/conrod#687]
Looks like `Canvas::flow_left` [was mistyped](https://github.com/PistonDevelopers/conrod/blob/6734b030d57a55bf49b84bc09965d7dba323947e/src/widget/canvas.rs#L178-L181) to flow down instead of left (`Direction::Y(Backwards)` instead of `Direction::X(Backwards)`), making it act exactly like `Canvas::flow_down`.

**Comment by mitchmindtree** [comment]
Thanks!
