### ISSUE TITLE
Make `Theme` an optional builder method for `Ui` (using `Theme::default` if none is specified`).

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#689]
This will make it one step easier by not having to import or construct a Theme for users who just want to get up and running.

**Comment by lllShamanlll** [comment]
Only optional builder method should be added, or Ui've to be redesigned to be build from something like UiSettings? Should alternative constructors be removed in favor of builder?

**Comment by mitchmindtree** [comment]
@lllShamanlll hmmm I've been thinking about this and I'm a little unsure.

Currently, our optional parameters only include:

- `Theme`
- widget capacity

So at first, the builder constructor as you mention seemed a little like overkill to me. However I think you're right: I think it might still be the best option as it will allow us to add further optional arguments in the future without breaking the API :+1: 

Something like this would be great:

```rust
let ui = conrod::UiBuilder::new()
    .theme(my_theme)
    .widget_capacity(2048)
    .build();
```

**Comment by lllShamanlll** [comment]
The problme here i've got,  we've to pass theme somehow to Ui while building. so it've to be Cloneable, or user've to be pushed to use Rc.
Mb there's other aproach to do that? 
[Patch](https://gist.github.com/lllShamanlll/dcf0329dfb1ed4ad398091a7046e0173)

**Comment by mitchmindtree** [comment]
Closing as this has been implemented for a while.
