### ISSUE TITLE
Widgets that have captured the pressed cursor no longer respond when cursor leaves window

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#69]
I haven't looked to see exactly what part of the game iterator loop stops working to cause this, and i'm not sure how hard or easy it would be to fix this. It's particularly noticable when trying to use the number dialer and your cursor goes off the screen while dialing a number.

**Comment by davekong** [comment]
Was this resolved with the move to glutin_window? I am not currently seeing this issue.

**Comment by bvssvni** [comment]
I think we can close this and keep it in mind in case the issue appears again.
