### ISSUE TITLE
Switch from freetype bindings to the rusttype crate in order to complete the road to pure Rust.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#695]
freetype is the last remaining non-rust library depended upon by conrod. It is also perhaps the source of most of our issues (see #546).

Recently [rusttype](https://github.com/dylanede/rusttype) has arrived to fill this gap, describing itself as a pure-rust alternative to freetype.

Find some discussion on the change [here](https://github.com/PistonDevelopers/truetype/issues/25), [here](https://github.com/PistonDevelopers/gfx_graphics/issues/276) and [here](https://github.com/dylanede/rusttype/issues/6).

This is a tracking issue for conrod's progress towards using rusttype.

Related to the completion of #321.

**Comment by dylanede** [comment]
I'm currently working on a backend-agnostic dynamic GPU glyph cache for RustType that you may find useful in Conrod (it would, for example, allow practically all text to be drawn with one draw call and one texture bound). There's also some slight changes (note that they really are slight - just some renaming and a few other small things) to the API that I'm polishing up. I advise that you wait for these changes to be available, though a preliminary integration won't hurt much, I expect.

**Comment by mitchmindtree** [comment]
Sounds excellent, thanks for the heads up!

**Comment by dylanede** [comment]
RustType 0.2 is now out, with GPU caching as the headline feature. The existing API has a few breaking changes, hence the minor version bump. Hopefully this is good enough now to attempt integration with.

**Comment by bvssvni** [comment]
@dylanede Nice!

**Comment by maun** [comment]
I tried replacing freetype with rusttype in https://github.com/PistonDevelopers/gfx_graphics/pull/288
I just started learning rust so comments are welcome.

**Comment by mitchmindtree** [comment]
By the looks of it, `gfx_graphics` and in turn `piston_window` now use rusttype - now it should hopefully just be a matter of updating to the latest version of the piston crates.

#706 and #707 will hopefully be fixed by this.

**Comment by dlight** [comment]
Is it already live? You may want to remove the section on [Installing Freetype](http://docs.piston.rs/conrod/conrod/guide/chapter_2/index.html#installing-freetype) from the guide (unless Conrod is now compatible with both Freetype and RustType)

**Comment by mitchmindtree** [comment]
Not quite, there are some issues with the latest version of piston_window [not compiling on stable](https://github.com/PistonDevelopers/piston_window/issues/126) which will persist until the next stable rust release comes out (under a week away), so we'll probably wait till then to update. Once we update though, we'll be sure to remember to remove that section and close this issue :+1:

**Comment by dylanede** [comment]
When this issue closes another one should really open for improving the integration. As it stands the integration with RustType could be better and take advantage of more RustType features, like its GPU cache.

**Comment by bvssvni** [comment]
@dylanede Sure. We also might use RustType for the OpenGL and Glium backends.
