### ISSUE TITLE
Building examples fails on windows

### ISSUE THREAD

**Issue by Boscop** [PistonDevelopers/conrod#707]
I'm using rust msvc nightly.
Conrod builds fine, but none of the examples builds. E.g:

```
> cargo run --example canvas
   Compiling libz-sys v1.0.2
   Compiling gl v0.5.2
   Compiling glutin v0.4.9
   Compiling gfx_gl v0.3.0
   Compiling piston-gfx_texture v0.9.0
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libz-sys v1.0.2`
Process didn't exit successfully: `D:\3rdparty\conrod\target\debug\build\libz-sy
s-e7bece249a602d0b\build-script-build` (exit code: 101)
--- stdout
running: "D:\\Program Files\\Microsoft Visual Studio 14.0\\VC/bin\\nmake.exe" "/
nologo" "/f" "D:\\Program Files\\.multirust\\cargo\\registry\\src\\github.com-48
ad6e4054423464\\libz-sys-1.0.2\\src/zlib-1.2.8\\win32/Makefile.msc" "TOP=D:\\Pro
gram Files\\.multirust\\cargo\\registry\\src\\github.com-48ad6e4054423464\\libz-
sys-1.0.2\\src/zlib-1.2.8" "zlib.lib"

--- stderr
NMAKE : fatal error U1073: don't know how to make 'D:\Program'
Stop.
thread '<main>' panicked at 'failed to run successfully: exit code: 2', D:\Progr
am Files\.multirust\cargo\registry\src\github.com-48ad6e4054423464\libz-sys-1.0.
2\build.rs:122
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I think it's because the zlib build script passes `"TOP=<path>"` instead of `TOP="<path>"` which causes problems with spaces in the path. 
What could I do to get the examples to build?
Btw, will it still depend on zlib after piston switches to rusttype?

**Comment by mitchmindtree** [comment]
Hey @Boscop, this will be resolved (along with a lot of other issues) once the graphics backend that the examples use switches to rusttype.

Ahh, I just checked and it looks like it already has. It looks like it should just be a matter of updating conrod's piston dependencies to align with the latest versions of each crate. I'm a bit busy at the moment, but I'd be happy to accept a PR and publish (or help debug if you run into issues) :+1:
