### ISSUE TITLE
examples don't compile - Could not compile `piston_window`.

### ISSUE THREAD

**Issue by 0ax1** [PistonDevelopers/conrod#713]
Hi,

I'm trying to compile the examples:
`cargo run --release --example all_widgets`

But none of them works due to:
`
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:78:9: 78:27 error: unresolved import `piston::window::*`. Could not find `window` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:78 pub use piston::window::*;
                                                                                                     ^~~~~~~~~~~~~~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:78:9: 78:27 help: run `rustc --explain E0432` to see a detailed explanation
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:80:9: 80:31 error: unresolved import `piston::event_loop::*`. Could not find `event_loop` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:80 pub use piston::event_loop::*;
                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:80:9: 80:31 help: run `rustc --explain E0432` to see a detailed explanation
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:79:9: 79:26 error: unresolved import `piston::input::*`. Could not find `input` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:79 pub use piston::input::*;
                                                                                                     ^~~~~~~~~~~~~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:79:9: 79:26 help: run `rustc --explain E0432` to see a detailed explanation
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:198:13: 198:39 error: unresolved import `piston::event_loop::Events`. Could not find `event_loop` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:198         use piston::event_loop::Events;
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:198:13: 198:39 help: run `rustc --explain E0432` to see a detailed explanation
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:199:45: 199:51 error: unresolved import `piston::window::Window`. Could not find `window` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:199         use piston::window::{ OpenGLWindow, Window };
                                                                                                                                          ^~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:199:45: 199:51 help: run `rustc --explain E0432` to see a detailed explanation
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:199:31: 199:43 error: unresolved import `piston::window::OpenGLWindow`. Could not find `window` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:199         use piston::window::{ OpenGLWindow, Window };
                                                                                                                            ^~~~~~~~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:199:31: 199:43 help: run `rustc --explain E0432` to see a detailed explanation
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:278:13: 278:39 error: unresolved import `piston::input::RenderEvent`. Could not find `input` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:278         use piston::input::RenderEvent;
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:278:13: 278:39 help: run `rustc --explain E0432` to see a detailed explanation
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:256:13: 256:39 error: unresolved import `piston::input::RenderEvent`. Could not find `input` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:256         use piston::input::RenderEvent;
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:256:13: 256:39 help: run `rustc --explain E0432` to see a detailed explanation
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:297:13: 297:30 error: unresolved import `piston::input::*`. Could not find `input` in `piston` [E0432]
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:297         use piston::input::*;
                                                                                                          ^~~~~~~~~~~~~~~~~
/Users/lx/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.42.0/src/lib.rs:297:13: 297:30 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to 9 previous errors
Could not compile `piston_window`.

**Comment by mitchmindtree** [comment]
Hey, thanks for the issue! The most recent update to conrod requires the latest stable version of rustc - updating rustc to 1.8.0 should hopefully fix any errors that you're running into.

More discussion on the related piston issue can be found [here](https://github.com/PistonDevelopers/piston/issues/1050), and [here](https://github.com/rust-lang/rust/pull/31362) is the related rustc issue.

Let me know if updating rustc fixes your issue! (you might also have to `cargo clean` and `cargo update` before attempting to build again after updating).

**Comment by 0ax1** [comment]
Hey, that fixed the the issue. Thanks for your help!
