### ISSUE TITLE
Removal of Freetype

### ISSUE THREAD

**Issue by Bluebird45** [PistonDevelopers/conrod#720]
Hi, I hope I'm not off-topic in asking the following here:

A recent commit to the Conrod readme says, "remove all references to the Freetype library, which is no longer necessary." 

Can I ask what other PistonDevelopers packages, if any, still require Freetype? I'm trying to revise a Piston-based arcade game, [Rocket](https://github.com/aochagavia/rocket "Rocket"), so as to no longer require Freetype. All the dependencies are the latest versions, on my re-build. But something is requiring Freetype to be present in the environment, and compile fails with a linker message of "freetype not found."

**Comment by bvssvni** [comment]
The OpenGL backend still uses FreeType.

**Comment by Bluebird45** [comment]
OK, thank you for that information.
