### ISSUE TITLE
Is UTF-8 text supported?

### ISSUE THREAD

**Issue by lucklove** [PistonDevelopers/conrod#722]
I want to show some non-ASCII text(eg. Chinese character) on the screen, how can I reach it?

**Comment by lucklove** [comment]
Got it, sorry for asking too early.

**Comment by mitchmindtree** [comment]
For anyone else reading this:

Our intention is that yes, widgets should support UTF-8, however this hasn't been heavily tested. If you notice any buggy behaviour in text widgets related to UTF-8, we'd appreciate an issue 👍
