### ISSUE TITLE
warning: broken MIR (occurs when compiling any of the examples on rustc stable 1.8)

### ISSUE THREAD

**Issue by mark-summerfield** [PistonDevelopers/conrod#724]
I don't know if this matters, but thought I'd let you know. The all_widgets example seemed to run okay except that I couldn't change the numbers for frame height or width in the GUI: I tried using the mouse wheel, clicking above, below, and on the number, typing a number and none had any effect.

The same warning also occurs with canvas, primitives, and text. Incidentally, the text example is very slow to resize (I'm on a 3+GHz i7).

examples/all_widgets.rs:148:39: 148:44 warning: broken MIR (var2 = conrod::ui::Ui<B>::new(tmp19, tmp21) -> [return: bb44, unwind: bb43]): call dest mismatch (conrod::ui::Ui<(gfx_texture::Texture<gfx_device_gl::Resources>, gfx_graphics::glyph::GlyphCache<gfx_device_gl::Resources, gfx_device_gl::factory::Factory>)> <- conrod::ui::Ui<(<gfx_graphics::back_end::GfxGraphics<'static, gfx_device_gl::Resources, gfx_device_gl::command::CommandBuffer> as graphics::graphics::Graphics>::Texture, gfx_graphics::glyph::GlyphCache<gfx_device_gl::Resources, gfx_device_gl::factory::Factory>)>): Sorts(ExpectedFound { expected: gfx_texture::Texture<gfx_device_gl::Resources>, found: <gfx_graphics::back_end::GfxGraphics<'static, gfx_device_gl::Resources, gfx_device_gl::command::CommandBuffer> as graphics::graphics::Graphics>::Texture })
examples/all_widgets.rs:148         Ui::new(glyph_cache.unwrap(), theme)
                                                                  ^~~~~
     Running `target/release/examples/all_widgets`

**Comment by mitchmindtree** [comment]
Thanks @mark-summerfield, I [reported this a while ago](https://github.com/rust-lang/rust/issues/32983) to the core team and they seem to be aware of it, I'm guessing the warning will go away in one of the upcoming stable rustc releases :+1:

Thanks for the report, I'll leave this open for others to see until the next rustc comes out and the warning goes away.
