### ISSUE TITLE
Integrate RustType directly and separate GlyphCache from font layout logic.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#732]
I've been doing some reading through the rusttype the `gpu_cache` code and the associated example. As someone quite unexperienced with *proper* text handling/rendering I've found it really enlightening. It's causing me to re-think the way the `GlyphCache` works and the way that text is handled in general throughout conrod.

Currently conrod relies on the `CharacterCache` for both glyph dimensions (for positioning logic) and rendering the text, when really the two should be very distinct as they're required at different stages.

In general, RustType provides far more *backend-agnostic* text handling features than the `CharacterCache` API (i.e. pair kerning, something which we've been meaning to add for a while).

**Comment by bvssvni** [comment]
That is interesting! Is there a way we could get rid of `CharacterCache` and just use RustType?

**Comment by mitchmindtree** [comment]
It sure looks like it! RustType supports everything `CharacterCache` was attempting to do, but in a much nicer and more fleshed out way - all backend agnostic without requiring custom traits (that can sometimes leak through downstream APIs).

I'm going to attempt to replace `CharacterCache` and `GlyphCache` in conrod now using RustType - I'll ping you when I have a PR up :+1:

**Comment by mitchmindtree** [comment]
Closed by #734
