### ISSUE TITLE
Widget Event Handling - A possible alternative to the `.react` function

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#741]
The Problem
------------------

The general convention for handling widget events in conrod so far has been to use a `.react` function like so:

```rust
Button::new()
    .react(|event| match event {
        button::Event::Pressed(mouse_button) => /* react to press, may get called multiple times */,
        button::Event::Released(mouse_button) => /* react to release, may get called multiple times */,
        button::Event::Clicked(mouse_button) => /* react to click, may get called multiple times */,
    })
    .set(ID, &mut ui);
```

Originally I thought this was a neat way of allowing a user to handle events amongst the rest of their builder methods in a clean, efficient manner. For many of the smaller, simpler widgets that were quite common for conrod early on, this did seem to be the case.

However, having written at least 50+ widgets now in my own projects (some quite large and complex), I've observed some issues with the `.react` method convention:

- **Ownership issues** - most widgets require that their react function be constrained by `FnMut`. This is because in most cases, multiple events may have been triggered since the widget's last update. For example, a `Button` might have been clicked multiple times during highly laggy gameplay. This can make it difficult, tedious and in some cases impossible to assign data given via events to bindings from the outer scope. In some cases, it also requires threading unique references through the widget instantiation into the arguments of the `react` function in order to be able to have mutable access to some data during the reaction to some event. In one case following a rustc bug fix, the interaction between nested closure scopes required us to change the `all_widgets.rs` example [to use a `mpsc::channel`](https://github.com/PistonDevelopers/conrod/blob/master/examples/all_widgets.rs#L355) just to retrieve and handle events from the `WidgetMatrix`'s `react` function. Not nice.
- **Difficulty with control flow** - a user may want to stop checking for events after a certain event type is received, or return early using the `try!` macro following some error. It can be very tedious to handle this when the user is restricted to the scope of a closure, with no connection between the return type of the closure and the scope within which the widget is instantiated.
- **Awkward builder method for widget designers** - Currently we can't write default `Fn`/`FnMut`/`FnOnce` types for widget `react` functions that propagate through inference without unstable. This means that although we store a `Option<F>` in the widget's builder struct (where `F` is some react function), the user is *always* required to give an explicit `react` function whether or not they plan on handling events for a widget. This is because rustc cannot infer the type for `F` when the `Option<F>` field for building is `None`. It would follow then that there is no point in storing an `Option<F>` and that we should simply store an `F` instead. However, this would then mean that we can no longer pass the react function by a `.react` builder method, and that every widget would require taking it via its intialiser. In turn, we would lose the ergonomics that we use the builder pattern for in the first place.

A Possible Solution - `Widget::Event` return type
--------------------------

I've been pondering the idea of adding an associated `Event` type to the `Widget` trait which could be returned via the `Widget::update` method and in turn the `Widget::set` method.

I.e. Rather than taking some `FnMut` react function, the hypothetical `Button` widget demonstrated above could specify its `Event` type as a `Vec<button::Event>`. Its instantiation might look as follows:

```rust
for event in Button::new().set(ID, &mut ui) {
    match event {
        button::Event::Pressed(mouse_button) => /* react to press */,
        button::Event::Released(mouse_button) => /* react to release */,
        button::Event::Clicked(mouse_button) => {
            if mouse_button.is_left() {
                try!(load_file()); // Using `try!` like this would not have been possible using the `react` convention.
            }
        },
    }
}
```

Longer builder chains might look like this:

```rust
for event in Button::new()
    .label("open file")
    .label_color(conrod::color::WHITE)
    .color("conrod::color::RED")
    .set(ID, &mut ui)
{
    match event {
        ...
    }
}
```

The following thought might occur to some:

> surely it must be significantly more expensive to return a `Vec<Event>` in my update loop for the majority of my widgets like this?

Keep in mind that the `Vec` would be empty for the vast majority of calls as there almost always needs to be some user interaction to trigger events and a user can only interact with one widget per input device at a time. Therefore I predict that the `Vec`s returned by widgets will very rarely even require dynamically allocating memory, as an empty `Vec` does not allocate any memory dynamically until an element is pushed to it.

Also, many widgets won't always need to return multiple events per instantiation, and may opt for return an `Option` instead.

Those widgets that are purely used for viewing data can simply do `type Event = ();` and return nothing at all.

@bvssvni @psFried and anyone else dropping by, I'd love to get your thoughts on this. This would be a significant breaking change, but is exactly the kind of breaking change we need to implement and test before a `1.0.0` if we're to go with it at all.

**Comment by bvssvni** [comment]
An idea: Use `Vec<Widget::Event: GenericEvent>`.

- It would make it possible to change the event type while making it easy to upgrade downstream
- You can define higher level events across widgets
- Both closure and argument conventions that fits different needs
- Possible to wrap in enums without changing code
- Model/View/Controller patterns (View = Widget, Controller = Handler, Model = Data)
- No problem passing events to functions, just use `E: GenericEvent` everywhere

**Comment by bvssvni** [comment]
Another idea: Get all events from the UI at once.

Each widget has an id, so you receive events with an id telling the widget they belong to:

```rust
for (id, e) in ui.events() {
    ...
}
```

This requires some mapping from custom widget events to ui events. One possible way is to use something like Piston-Meta's data structure:

```rust
pub enum MetaData {
    /// Starts node.
    StartNode(Arc<String>),
    /// Ends node.
    EndNode(Arc<String>),
    /// Sets bool property.
    Bool(Arc<String>, bool),
    /// Sets f64 property.
    F64(Arc<String>, f64),
    /// Sets string property.
    String(Arc<String>, Arc<String>),
}
```

This structure works as a universal data container for many different use cases. Events can be handled by pattern matching on the meta events. It doesn't have to be Piston-Meta, but a event/text correspondence would be nice for debugging and JSON it across some network. This would also make it easy to write DSLs for widgets.

However, perhaps this is a detour away from immediate mode design? Just brainstorming a little since it could be a good idea to consider vastly different designs to easier notice trade-offs.

**Comment by mitchmindtree** [comment]
Thanks for the input @bvssvni! Some very interesting ideas. I think you might be right though in that they might be a little orthogonal to conrod's immediate API design. Either way, it's nice to consider them. The `for (id, e) in ui.events()` looks like it'd be great for a more retained style widget API.

I normally reach a similar API in conrod by implementing re-usable groups/collections of widgets as new single widgets. For example, my timeline widget is instantiated something like this:

```rust
        Timeline::new(bars.iter().cloned(), tracks)
            .react(|event| timeline_events.push_back(event))
            .set(TIMELINE, ui);
```
It is made up of many child widgets (`Track`s, `Playhead`, etc), and their events are enumerated and propagated to the surface (currently via `.react` methods, though it'd be nicer if they were simply returned) to be handled like this:
```rust
    while let Some(event) = timeline_events.pop_front() {
        match event {
            Event::PlayheadMoved(_ticks) => (),
            Event::Playhead(playhead_event) => match playhead_event {
                PlayheadEvent::Pressed => println!("Playhead pressed!"),
                PlayheadEvent::DraggedTo(ticks) =>
                    *playhead_secs = time::Ticks(ticks).ms(BPM, core::PPQN) / ONE_SECOND_MS,
                PlayheadEvent::Released => println!("Playhead released!"),
            },
            Event::Track(track_idx, track_event) => match track_event {
                TrackEvent::Automation(automation_event) => match automation_event {

                    // Numeric automation.
                    DynamicAutomationEvent::Numeric(numeric_event) => match numeric_event {
                        NumericAutomationEvent::Interpolate(_number) => (),
                        NumericAutomationEvent::Mutate(mutate) => match track_idx {
                            TEMPO_ENVELOPE => mutate.apply(tempo_envelope),
                            OCTAVE_ENVELOPE => mutate.apply(octave_envelope),
                            _ => panic!("Unhandled envelope or incorrect indices"),
                        },
                    },

                    // Toggle automation.
                    DynamicAutomationEvent::Toggle(toggle_event) => match toggle_event {
                        ToggleAutomationEvent::Interpolate(_toggle) => (),
                        ToggleAutomationEvent::SwitchTo(_toggle) => (),
                        ToggleAutomationEvent::Mutate(mutate) => match track_idx {
                            TOGGLE_ENVELOPE => mutate.apply(toggle_envelope),
                            _ => panic!("Unhandled envelope or incorrect indices"),
                        },
                    },

                    // Bang automation.
                    DynamicAutomationEvent::Bang(bang_event) => match bang_event {
                        BangAutomationEvent::Bang => println!("BANG!"),
                        BangAutomationEvent::Mutate(mutate) => match track_idx {
                            BANG_ENVELOPE => mutate.apply(bang_envelope),
                            _ => panic!("Unhandled envelope or incorrect indices"),
                        },
                    },
                },
                TrackEvent::PianoRoll(piano_roll_event) => match piano_roll_event {
                    PianoRollEvent::NoteOn(_note_idx) => (),
                    PianoRollEvent::NoteOff(_note_idx) => (),
                    PianoRollEvent::NotePlayed(_note_idx) => (),
                },
            },
        }
    }
```

So similar in ways, but no event casting involved and perhaps more suited to the immediate style in that parent widget events can be directly constructed from child events as they're produced.

I might survey the existing widgets tonight and investigate how the possible  `Widget::Event` solution might affect them, and have a go at implementing it if all looks ok.
