### ISSUE TITLE
Rename `Frame` to `Border` throughout crate to reduce ambiguity

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#750]
`Frame` already has a very prevalent meaning in graphics as a discrete moment in time. We should probably change this to `Border` to reduce the possibility for any ambiguity.

If anyone's keen to take this one feel free to leave a comment and go for it :+1:

**Comment by pthariensflame** [comment]
I'll take this.  It needs to get done sometime.  :)
