### ISSUE TITLE
Allow drawing only a part of a widget. (Crop)

### ISSUE THREAD

**Issue by 05storm26** [PistonDevelopers/conrod#755]
I have created a rounded rectangle widget in my own crate which uses conrod. I used simple circles and rectangles. It works, but the problem I have is that since areas of the cirles and the rectangles are overlapping, whenever their color is set to something which is half transparent or has any transparency really then the color on of these overlapping regions are going to be different from the color of the rest of the widget.

This could be solved by using quarters of circles instead of full circles to avoid overlapping regions but I don't think that is possible right now. 

Is there another way to solve this? Is there a way to crop widgets (only draw parts of them)?

**Comment by mitchmindtree** [comment]
@05storm26 I think an easier (and more efficient) solution might be to use a single `Polygon` widget to make this - you could pass it a list of points that travel around each edge and each rounded corner.

It'd be great to see this added to conrod itself if you'd consider contributing it? I've been meaning to make one but haven't got around to it yet!

**Comment by mitchmindtree** [comment]
Oh btw, it is possible for a parent widget to crop its children widgets via the `Widget::crop_kids` method - this will crop the children to the bounding rectangle of the parent, however this is probably more useful for widgets such as scrollable lists, etc.

**Comment by mitchmindtree** [comment]
@05storm26 I'm going to close this for now, but feel free to re-open if you're still having trouble :+1:
