### ISSUE TITLE
Can't access "render" module

### ISSUE THREAD

**Issue by Finnerale** [PistonDevelopers/conrod#756]
I want to write a custom backend for conrod with the new primitives() implementation
but for some reason I can't access this module.
All the other modules are no problem

src/window.rs:7:5: 7:19 error: unresolved import `conrod::render`. Did you mean `self::conrod`? [E0432]
src/window.rs:7 use conrod::render;

src/window.rs:7:5: 7:19 help: run `rustc --explain E0432` to see a detailed explanation
src/window.rs:89:55: 89:86 error: failed to resolve. Could not find `render` in `window::conrod` [E0433]
src/window.rs:89     pub fn primitives<Img>(&mut self, mut primitives: conrod::render::Primitives<Img>) {

Better to read :
http://hastebin.com/yejazenayu.mel

**Comment by mitchmindtree** [comment]
@Finnerale hey! I haven't published the changes with the new render module just yet - should be published within the next couple of hours :+1:

By the way, if you want to format your text so that it is monospaced in github, you can surround it with 3 back ticks, i.e.

    ```
    text
    ```
