### ISSUE TITLE
widget::primitive::line::Cap is private

### ISSUE THREAD

**Issue by Bastacyclop** [PistonDevelopers/conrod#774]
I'm implementing my own conrod backend and can't access [widget::primitive::line::Cap](https://github.com/PistonDevelopers/conrod/blob/381a153d47d3a5460ce238565738b0de8b0d9835/src/widget/primitive/line.rs#L65).
By the way, the line `Pattern` seems to be neither managed by conrod neither passed to the backend ?

**Comment by mitchmindtree** [comment]
Hey, thanks for the issue!

I'll open another issue re handling `line::Pattern`.
