### ISSUE TITLE
Cloning an IndexSlot changes its value

### ISSUE THREAD

**Issue by tmerr** [PistonDevelopers/conrod#780]
```
let a = IndexSlot::new();
let b = a.clone();
println!("{}, {}", a.get(&mut ui).index(), b.get(&mut ui).index());
```
This code prints two consecutive numbers. Is this expected behavior?

**Comment by mitchmindtree** [comment]
@tmerr I think this behaviour might become a little clearer when understanding why and how `IndexSlot` works.

The idea behind `IndexSlot` was to act as a simplified kind of "single index cache" to make it easier for widget's to generate `NodeIndex`s for child widgets and re-use them by storing them within the `State` type. It was included after writing too much code like this:

```rust
// widget state
pub struct State {
    button_idx: Option<NodeIndex>,
}

// in Widget::update
let button_idx = match state.button_idx {
    None => {
        let new_idx = ui.new_unique_node_index();
        state.update(|state| state.button_idx = Some(new_idx));
        new_idx
    },
    Some(idx) => idx,
};
```

after adding `IndexSlot`, this becomes:

```rust
// widget state
pub struct State {
    button_idx: IndexSlot,
}

// in Widget::update
let button_idx = state.button_idx.get(&mut ui);
```

Although better, the behaviour is definitely a little ambiguous and I've been hoping to think of a nicer solution (perhaps using a macro of some sort).

In your example, the `IndexSlot` is empty when you clone it and so when `IndexSlot::get` is called, a new `NodeIndex` is generated for both `a` and `b`. On the other hand, if you were to call `IndexSlot::get` on `a` before cloning it, both `a` and `b` would have the same `NodeIndex`.

Does this clarify the behaviour? I agree that it is not optimal, but I haven't had the time to investigate a better solution for `IndexSlot` just yet. Perhaps in the meantime it would be best for us to remove the `Clone` implementation for `IndexSlot` to remove any chance of ambiguity?

**Comment by tmerr** [comment]
Oh okay thanks for the explanation. I'm content just knowing how it works, but maybe either a mention of it in the docs or removing `Clone` for now would be a good idea. I'll try to look into this more later to get a better understanding, I don't have any strong opinions on it yet :)

**Comment by tmerr** [comment]
Closing because as of #810 NodeIndex is superseded by widget::Id which doesn't have this problem
