### ISSUE TITLE
Add support for right click and double click to button widget (and other widgets?)

### ISSUE THREAD

**Issue by pierrechevalier83** [PistonDevelopers/conrod#801]
As it currently stands, the button widget's update method only keeps track of the number of left clicks in and returns it in a TimesClicked struct.

Is there any design reason why we are not returning a more generic event that could for instance expose the number of clicks, right clicks and double clicks?

Also, is there a way such an event could be reused in different places instead of having a struct per widget?

I guess the question is about the philosophy behind the current design as much as it's a feature request. I'm willing to give a hand if the idea seems OK.

**Comment by mitchmindtree** [comment]
@pierrechevalier83 I'm happy to see us add a more detailed `Event` type for the `Button` :+1: there's no particular reason that only left clicks are considered other than that it is probably the common case.

As a side note, I just thought I'd mention that it's pretty easy to target any type of widget event when necessary using the `Ui::widget_input` method, i.e.
```rust
for click in ui.widget_input(button_idx).clicks().right() {
    // do stuff with right clicks
}
```
But I do agree it'd be nice if the `Button`'s `Event` type was a little more detailed.

**Comment by mitchmindtree** [comment]
Going to close this as I think my suggestion above should suffice for now.
