### ISSUE TITLE
Conrod uses 100% cpu in the examples

### ISSUE THREAD

**Issue by jappeace** [PistonDevelopers/conrod#814]
The main cause seems to be the set_widgets function, when I remove this function from the main event loop it won't have 100% cpu. 
It'll reset the widgets, causing the ui to be hanged which again causes the ui to be drawn (I think I haven't tested that).
The work around is to match on an input event and only set the widgedts whenever an input is received. The widgets can only change anyway with received input. My main drawing loop looks something like this now:

```
    match event.clone() {
        Idle (_ ) => std::thread::yield_now(),
        Render(_ ) => window.draw_2d(&event, |c, g| {
                if let Some(primitives) = ui.draw_if_changed() {
                    fn texture_from_image<T>(img: &T) -> &T { img };
                    conrod::backend::piston_window::draw(c, g, primitives,
                                                         &mut text_texture_cache,
                                                         &image_map,
                                                         texture_from_image);
                }
            }).unwrap(),
        AfterRender(_ ) => continue,
        Update(_ ) => if !handledInput {set_widgets(ui.set_widgets(), ids); handledInput = true },
        Input(I) => handledInput = false,
    };
```

So what I'd like to see is either fixing the examples in above manner, or figure out why set_widgets in the examples eats so much cpu time.

**Comment by mitchmindtree** [comment]
Thanks for the issue! This is most likely related to #802. I've been meaning to get around to this for a little while.

I don't think it's a problem with set_widgets or conrod, it's just that the examples are pretty much a hot loop at the moment so it hogs the CPU. For some reason I originally assumed that piston_window automatically yielded when idle, however it makes sense that this control should be given to the user. I'll update the examples asap

**Comment by jappeace** [comment]
I found *a* reason why I had 100% cpu problems,
In a case I used to generate every update a new ID for a solarsystem simulater. This worked all fine until I wanted to be able to click the planets. So I replaced the circles with buttons, and they didn't work.

After some tinker I suddenly realised it was because I kept creating new id's and so the events were never matched to the right element. This also meant the scene graph kept on growing which caused eventually cpu buidlup since the graph got bigger and bigger.

So to prevent this kind off issue happening to other users you should probably print a warning or something if the graph gets to an unreasonably large size (say more than 100 000 unique ID's). 100 000 is hard to reach for hand crafted GUI's but almost trivial for a loop based approach I did in my ignorance.

Now the code I'm using looks nothing like the original example and I'm still preventing conrod from updating more than 60 times per second, but now I at least get the 60fps. rather than 10. (not that I need it for my application but I imagines others do so).

**Comment by mitchmindtree** [comment]
Going to close this as most examples now idle at 0% CPU on my machine, and OPs issue seemed to also be related to generating too many IDs. @jappeace feel free to open a new issue if you'd like to see some heuristic implemented for warning users about generating too many IDs by mistake :+1:
