### ISSUE TITLE
Use `piston::input::Input` as the `Raw` event type rather than `piston::input::Event`

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#820]
Conrod only needs to know about the `Input` events, the other of the `piston::input::Event` variants (Render, AfterRender, Update, Idle) are not used.

I think the `Render` variant is currently used to get the initial window dimensions, however this is a little hacky and I think we'd be better off requiring that conrod is constructed with some initial window size and then monitors the `Input::Resize` event for changes to window size.

**Comment by bvssvni** [comment]
Notice that resize events doesn't work in Glutin for some platforms: https://github.com/tomaka/glutin/issues/445 (OSX) and https://github.com/tomaka/glutin/issues/799 (Win).

One way to work around this is to extract the size directly from the window and check whether it has changed.

**Comment by mitchmindtree** [comment]
@bvssvni yeah thanks for the heads up! I've run into this a couple times before and spent some time trying to get it working as an Event in glutin a while back with no luck, so it's fresh in my mind 😜
