### ISSUE TITLE
Examples panic when closing window by clicking [X]

### ISSUE THREAD

**Issue by Boscop** [PistonDevelopers/conrod#825]
When closing the conrod window by clicking [X] on the title bar, the program panics with error: 
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 6, message: "The handle is invalid." } })', ../src/libcore\result.rs:783`

So the only way to close the window right now is by pressing ESC.
Most professional GUI apps don't close when you press ESC but close when you click [X], (but most GUI libs still allow intercepting that close event to e.g. show a "save? yes/no/cancel" dialog).

**Comment by mitchmindtree** [comment]
Yeah I think this is an issue with the glutin crate. I fixed this a while ago upstream but the bug seems to have re-appeared recently... Haven't had time to investigate just yet. But yeah, I think the best place for an issue would be at the tomaka/glutin crate if there is not already one.

**Comment by mitchmindtree** [comment]
Going to close this as this issue probably belongs at [tomaka/winit](https://github.com/tomaka/winit) if it is still a problem.
