### ISSUE TITLE
Generating arbitrary number of widget ids.

### ISSUE THREAD

**Issue by Proksima** [PistonDevelopers/conrod#826]
I am working on a candlesticks chart library and I have a problem since I upgraded to version >0.43. I used to generate my own Ids from usizes as depending on the size of the window or the user inputs the number of widgets displayed on the graph vary. For example, I can never know in advance how many ticks/division I will put on the axis of the graph.

However since the mentioned version, conrod does not seem happy about me generating my own ids. Is this intended or a bug? Is there a workaround for my problem?

**Comment by Boscop** [comment]
I'm just figuring this out myself right now:
[Step 1: Instead of putting `name` in Ids, use `name[]`.](https://github.com/PistonDevelopers/conrod/blob/master/src/widget/envelope_editor.rs#L71)
[Step 2: Use widget_id_generator() to assign as many ids as you need](https://github.com/PistonDevelopers/conrod/blob/master/src/widget/envelope_editor.rs#L489)

**Comment by mitchmindtree** [comment]
Hey @Proksima, thanks for the issue :)

The way widget identifiers work in conrod was simplified a lot recently, primarily within #810 which describes the reasoning behind the change in the comments and commits.

The `widget_ids!` macro works slightly differently now - I'd recommend checking out the examples or widget implementations to get a quick view of how they work.

Re generating a dynamic number of `widget::Id`s: This can be done using the `ui.widget_id_generator()` as shown by boscop. The `widget_ids!` macro now supports a `foo[]` syntax which generates a `widget::id::List`, a type designed to make it easier to maintain a dynamic number of identifiers, easy to use alongside the `widget::id::Generator` (returned by `ui.widget_id_generator()`).

Hopefully this helps, let us know if anything is still unclear :+1:

**Comment by Proksima** [comment]
Thanks for the quick answer! I was able to refactor my code and I prefer by far the result with the new widget_id_generator(). Thank you for your hard work!
