### ISSUE TITLE
Rotated text

### ISSUE THREAD

**Issue by Geemili** [PistonDevelopers/conrod#836]
Hello! I am working on a crate for a [graphing widget](https://github.com/Geemili/conrod_graph), and just added labeling axis' to it. I realized that it would be (very) nice if I could rotate the text. Is there currently a way to rotate text?

**Comment by mitchmindtree** [comment]
Not yet unfortunately, this is definitely something I'd like to add! I've opened #837 as a more general version of this issue - closing this in favour of it.
