### ISSUE TITLE
Window resizing bug in piston backend

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#854]
Seems to have been introduced in #850.

Looks like this:

![screen shot 2016-11-12 at 6 40 36 pm](https://cloud.githubusercontent.com/assets/4587373/20236378/8b9ab996-a907-11e6-9fb9-70a8a2ed5d0b.png)

![screen shot 2016-11-12 at 6 40 45 pm](https://cloud.githubusercontent.com/assets/4587373/20236379/8f1b74c0-a907-11e6-97f0-839250385abc.png)

**Comment by christolliday** [comment]
oh whoops, good catch, I actually saw this and assumed it was caused by some other change.
It looks like it's caused by not calling the correct `next` method for the window, I'm looking into a fix right now.

**Comment by mitchmindtree** [comment]
Closed by #856
