### ISSUE TITLE
Image Button Alternate Image

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#862]
When a button is pressed/hover, it would be good to specify a different image.

The colour select is ok, but doesn't work that well for images.

**Comment by tl8roy** [comment]
@mitchmindtree So I think I see see where you are going with the "Proper" solution for the Flat button colours. A generic ```Interaction``` emun sounds like a good way to me. Were you thinking of a Hashmap or something similar for storing them all in one place?

**Comment by mitchmindtree** [comment]
Going to close this as this particular issue has been addressed in #927. Would be happy to discuss custom colours per interaction in another issue though :+1:
