### ISSUE TITLE
Scrollable TextEdit

### ISSUE THREAD

**Issue by Jascha-N** [PistonDevelopers/conrod#866]
Is it somehow possible to make a `TextEdit` scrollable?

**Comment by mitchmindtree** [comment]
@Jascha-N yep this should be possible by calling one of the `.scroll_kids` methods on the widget that is the parent of your `TextEdit` widget.

For example, something along these lines:

```rust
// Specify a `Rectangle` to use as the scrollable "parent"/"container" widget.
widget::Rectangle::fill(text_area_dimensions)
    .color(conrod::color::TRANSPARENT) // If you don't want the scrollable area to be coloured
    .scroll_kids_vertically()
    .set(SCROLLABLE_AREA, ui);

widget::TextEdit::new(&my_string)
    .mid_top_of(SCROLLABLE_AREA)
    .parent(SCROLLABLE_AREA, ui) // This might not be necessary, and should be inferred via the `.mid_top_of` method
    .set(TEXT_EDIT, ui);

// If you want a scrollbar for scrolling the text by hand, it's something along these lines. 
widget::Scrollbar::y_axis(SCROLLABLE_AREA).auto_hide(true).set(SCROLLBAR);
```

I haven't tested this and there's likely bugs, but hopefully it gives you an idea to get started! Let me know if you run into any more issues.

**Comment by Jascha-N** [comment]
Before I posted here I tried exactly that, but with a `Canvas` instead of a `Rectangle`. I also tried with and without `restrict_to_height` but to no avail. If I set the `Scrollbar::auto_hide` to `false`, it will be visible but always greyed out, even when the text exceeds the size of the `Canvas` or `Rectangle`. Mouse-wheel scrolling or page up/down doesn't work either.

**Comment by mitchmindtree** [comment]
@Jascha-N ahhh I think I might know what's going on. It sounds like the `TextEdit`'s height is not being automatically inferred properly. This is important for when the scrollable parent must calculate the bounding box for all its children.

Upon checking, it's not being inferred at all! I'll look into fixing this now...

**Comment by Jascha-N** [comment]
Thanks, very much appreciated!
