### ISSUE TITLE
Reusing a texture in an image map

### ISSUE THREAD

**Issue by TimBednarzyk** [PistonDevelopers/conrod#895]
I'm trying to use one texture for multiple images. My texture consists of all of a bunch of icons packed together in order to save on the number of textures. However, with the glutin/glium backend, I can't seem to have an image map of references to `glium::texture::Texture2d`s like so:
```
let image_map = image_map! {
    (ids.image1, &icons),
    (ids.image2, &icons)
};
```
The error I get when I use references is this:
```
error[E0271]: type mismatch resolving `<&conrod::glium::Texture2d as std::ops::Deref>::Target == conrod::glium::texture::TextureAny`
   --> src/main.rs:150:16
    |
150 |       renderer.fill(&display, primitives, &image_map);
    |                ^^^^ expected struct `conrod::glium::Texture2d`, found struct `conrod::glium::texture::TextureAny`
    |
    = note: expected type `conrod::glium::Texture2d`
    = note:    found type `conrod::glium::texture::TextureAny`
    = note: required because of the requirements on the impl of `conrod::backend::glium::TextureDimensions` for `&conrod::glium::Texture2d`

error[E0277]: the trait bound `for<'a> conrod::glium::uniforms::Sampler<'a, &conrod::glium::Texture2d>: conrod::glium::uniforms::AsUniformValue` is not satisfied
   --> src/main.rs:154:16
    |
154 |       renderer.draw(&display, &mut target, &image_map).unwrap();
    |                ^^^^
    |
    = help: the following implementations were found:
    = help:   <conrod::glium::uniforms::Sampler<'a, conrod::glium::texture::Texture1d> as conrod::glium::uniforms::AsUniformValue>
    = help:   <conrod::glium::uniforms::Sampler<'a, conrod::glium::texture::CompressedTexture1d> as conrod::glium::uniforms::AsUniformValue>
    = help:   <conrod::glium::uniforms::Sampler<'a, conrod::glium::texture::SrgbTexture1d> as conrod::glium::uniforms::AsUniformValue>
    = help:   <conrod::glium::uniforms::Sampler<'a, conrod::glium::texture::CompressedSrgbTexture1d> as conrod::glium::uniforms::AsUniformValue>
    = help: and 55 others

```
Is there any way I can use one texture for multiple images?

**Comment by tl8roy** [comment]
If I was going to hazard a guess, 
http://docs.piston.rs/conrod/conrod/widget/primitive/image/struct.Image.html#method.source_rectangle is probably the method to use.

**Comment by mitchmindtree** [comment]
Yeah @tl8roy's suggestion should be correct, however `Image::source_rectangle` has still not been properly tested with the new glium backend and could easily have bugs.

I just did a quick test and it seems like hidpi is not yet handled correctly. The docs are also not yet clear on the source `Rect`'s origin. I'm uncertain what the exact behaviour should be here. Currently (0, 0) seems to be the bottom left of the image, however I'm tempted to have the origin of the source rectangle (0, 0) be the middle of the image as this is how `Rect` behaves throughout the rest of conrod. Thoughts?

**Comment by TimBednarzyk** [comment]
`Image::source_rectangle` is perfect for displaying part of a texture, however the issue is with sharing that texture between 2 or more images. An image map requires taking ownership of a texture, and therefore that texture can only be used for one image id.

**Comment by tl8roy** [comment]
@mitchmindtree Bottom Left or Top Left would match most other sprite implementations. Top Left is probably the best (Would match CSS) but BL would also work.

**Comment by mitchmindtree** [comment]
@TimBednarzyk agh of course! I was forgetting that we can only instantiate the `Image` once per update as we can not re-use its `widget::Id` multiple times :man_facepalming: 

Perhaps we can come up with a better design for `image::Map`? I originally thought that mapping `Image`s to `widget::Id`s might simplify the API, however I think your use-case is a good example for why it is probably not a good idea.

Perhaps we should use a unique `image::Id` type for distinguishing between images then and require them to be passed to the `Image::new` constructor? This way a user could re-use an image between multiple `Image` widget instances. A unique `image::Id` could be returned for each image when inserting them into the `image::Map`. We could provide an `image_ids!` macro that behaves similarly to the `widget_ids!` macro but instead generates a struct with `image::Id` fields? I'm curious to hear both your thoughts on how we should handle this!

**Comment by tl8roy** [comment]
That sounds logical to me.

Based on how I think it works, I think this is a fairly simple change in my current code structure as I had already split the images from the other components.

While I haven't done extensive low level UI stuff in a while, I did think it was a bit odd that the image to use wasn't specified in the new function. So I think the change would actually be easier to grasp.

**Comment by TimBednarzyk** [comment]
I agree that having a unique `image::Id` would be a good idea, along with the `image_ids!` macro. I also think this will make the API more consistent, as right now constructing a `widget::Button` with an image has you using two `widget::Id`s: one for the image (which gets passed to the `widget::Button::image` constructor) and one for the button itself, which seemed strange as it's only one widget. Having you pass image ids to the `widget::Button::image` and `Image::new` constructors seems logical to me.

**Comment by christolliday** [comment]
I'd also like to see a unique id for images. I think it should be possible to use the same approach used for fonts. Actually, `font::Map` could be turned into a generic resource map, ie. `resource::Map<Font>` and `resource::Map<Image>` which could probably be used for other resource types eventually.

**Comment by tl8roy** [comment]
Getting back into the grove and another thing to think about is loading all images into the image map at the same time.
At the moment, I think we have to load all images at the same time using the ```image_ids!``` macro. In some cases it might be desired to add an image conditionally (EG only if it is present).

Would it be possible to refactor and/or add an example showing images loaded after the main ```image_ids!``` macro has been run. If a breaking change is required, well now is a good time.

**Comment by TimBednarzyk** [comment]
You don't _have_ to load them with the `image_ids!` macro, the current `image::Map` allows adding/updating/removing individual images. `image_ids!` is merely for convenience.

**Comment by tl8roy** [comment]
@mitchmindtree Do you have an estimate of when you expect to start looking at this?

**Comment by mitchmindtree** [comment]
@tl8roy I can't give any specific time but it's still on my radar as one of the next priorities for when I get a chance to get back to conrod, which will hopefully be soon! I'd be happy to review a PR if anyone else wanted to make a start on this though.
