### ISSUE TITLE
Not all columns of NumberDialer are selectable

### ISSUE THREAD

**Issue by TimBednarzyk** [PistonDevelopers/conrod#896]
I've created a `widget::NumberDialer`, but only the first column is selectable, as shown in the following images:
![tol_1](https://cloud.githubusercontent.com/assets/8797125/21423192/98606fce-c809-11e6-9843-4ebaf97946dc.png)
![tol_2](https://cloud.githubusercontent.com/assets/8797125/21423194/99c88388-c809-11e6-83f5-268fc6c76abc.png)

One thing to note is that bumping up the precision increases the number of functional columns, but I've not seen all of them work.

**Comment by TimBednarzyk** [comment]
Another thing I've just found out is that the background is also wrong (the lighter blue):
![image](https://cloud.githubusercontent.com/assets/8797125/21424368/74995888-c810-11e6-98de-f8acb5ed3306.png)
It almost looks like it's not taking account for the "Tolerance" label

**Comment by mitchmindtree** [comment]
Hmmm I haven't seen this behaviour before and I've used `widget::NumberDialer` in quite a few projects. Would you mind posting the code snippet used where you instantiate the NumberDialer? Do the dialers in **examples/old_demo.rs** also behave like this for you?

**Comment by mitchmindtree** [comment]
I'm going to have to close this as I can't seem to recreate this behaviour. If you can post some example code that demonstrates this, I'd be happy to re-open :+1:
