### ISSUE TITLE
Button label_x_align()

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#901]
It would be good to add label_x_align() to the Button builder method.

I am finding it a bit clunky to break out of the builder to set the alignment and then resume.

**Comment by mitchmindtree** [comment]
@tl8roy are you looking for the [Button::align_label_left](http://docs.piston.rs/conrod/conrod/widget/button/struct.Button.html#method.align_label_left), etc methods?

**Comment by tl8roy** [comment]
Yes, why couldn't I see them before.
