### ISSUE TITLE
Distinguish between general widget alignment and typographic alignment by referring to text alignment as justification.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#922]
At the moment, both kinds of alignment are referred to using the word `align` in method names. This can get particularly tricky, especially when positioning labels or text. E.g:

```rust
widget::Text::new(text).align_left().align_text_right()
```

This line aligns the bounds of the `Text` widget to the left of the previous widget and right justifies the text itself so that the right margin is flush.

I propose that we make the following method name changes for `align`ment that refers to typographic alignment:

- `Text::align_text_left` -> `Text::left_justify`
- `Text::align_text_middle` -> `Text::centre`
- `Text::align_text_right` -> `Text::right_justify`

This avoids conflicting with the following methods (implemented for all `Widget`s):

- `Positionable::align_left`
- `Positionable::align_middle`
- `Positionable::align_right`

This also leaves room for adding a `justify` method in the future which makes both edges of the text flush with the margins.

**Comment by tl8roy** [comment]
I would make it ```centre_justify``` just so it is consistent.

Other than that, I think it is a good idea.
