### ISSUE TITLE
Minimal “hello world” example

### ISSUE THREAD

**Issue by suhr** [PistonDevelopers/conrod#932]
Without things like `mod support` (btw, shouldn't EventLoop be a part of conrod itself?).

**Comment by mitchmindtree** [comment]
Most of the examples only use `mod support` to provide the `EventLoop`. The reason conrod does not provide the `EventLoop` as part of the library is that there are so many different ways an event loop might be implemented, and which is better depends on the unique requirements of the user. Event loops also depend greatly upon the window backend used, and I don't think it should be conrod's responsibility to write and maintain a unique event loop for each supported backend feature, as this is a lot of time on writing and maintenance and as I said before, there are many different ways they could be written. The `EventLoop` that we provide in the `examples/support` module is a very small amount of code and is mainly used to simplify the examples where possible (note that [tomaka/glium also does this](https://github.com/tomaka/glium/blob/master/examples/support/mod.rs#L18)). Hopefully it is easy enough for users to copy/adapt this loop to suit their needs if they wish.
