### ISSUE TITLE
Touchscreen doesn't appear to registor clicks on buttons

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#936]
At the moment it appears that a touchscreen doesn't work.

This could be a thing with the touchscreen driver or the method that is used to detect clicks doesn't work for touchscreens.

FYI, the mouse moves so that the hover command works, but not the click itself.

**Comment by tl8roy** [comment]
So looking at the ```evtest``` log, there is a subtle difference:

Touchscreen:
```
Event: time 1485991818.413401, -------------- EV_SYN ------------
Event: time 1485991818.525410, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 97
Event: time 1485991818.525410, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 1549
Event: time 1485991818.525410, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 2032
Event: time 1485991818.525410, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1
Event: time 1485991818.525410, type 3 (EV_ABS), code 0 (ABS_X), value 1549
Event: time 1485991818.525410, type 3 (EV_ABS), code 1 (ABS_Y), value 2032
Event: time 1485991818.525410, -------------- EV_SYN ------------
Event: time 1485991818.632377, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value -1
Event: time 1485991818.632377, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
```


Mouse:
```
Event: time 1485991829.820835, -------------- EV_SYN ------------
Event: time 1485991829.836845, type 2 (EV_REL), code 0 (REL_X), value -1
Event: time 1485991829.836845, type 2 (EV_REL), code 1 (REL_Y), value 1
Event: time 1485991829.836845, -------------- EV_SYN ------------
Event: time 1485991831.069004, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1485991831.069004, type 1 (EV_KEY), code 272 (BTN_LEFT), value 1
```

If ```BTN_TOUCH``` is included in the click test, then I think it will work.

**Comment by tl8roy** [comment]
I added a debug statement in the button widget to see if that was the spot that was causing the problem and it looks like it isn't. This suggests the problem is deep is the bowels of the input device stack.

**Comment by mitchmindtree** [comment]
If you place the following code somewhere within your `set_widgets` scope, does it print any touch events?

```rust
for event in ui.global_input().events() {
    println!("{:?}", &event);
}
```

If so, we probably just have to actually handle the touch events in `Button` - I don't think we're handling touch in any widgets yet, but it should be pretty easy to add.

**Comment by mitchmindtree** [comment]
Btw, input handling when using the `winit` feature happens in `winit`, so if you need to test any lower level events the [winit](https://github.com/tomaka/winit) crate examples might be the easiest place to do some tests.

**Comment by tl8roy** [comment]
So that code produces:
Mouse:
```
Raw(Move(MouseCursor(-124, -317)))
Ui(Move(Some(NodeIndex(21)), Move { motion: MouseCursor(-124, -317), modifiers:  }))
Raw(Press(Mouse(Left)))
Ui(Press(Some(NodeIndex(21)), Press { button: Mouse(Left, [-124, -317]), modifiers:  }))
Ui(WidgetCapturesKeyboard(NodeIndex(21)))
Raw(Release(Mouse(Left)))
Ui(Release(Some(NodeIndex(21)), Release { button: Mouse(Left, [-124, -317]), modifiers:  }))
Ui(Click(Some(NodeIndex(21)), Click { button: Left, xy: [-124, -317], modifiers:  }))
```

Touch:
```
Raw(Move(MouseCursor(-150, -320)))
Ui(Move(Some(NodeIndex(21)), Move { motion: MouseCursor(-150, -320), modifiers:  }))
Ui(WidgetUncapturesMouse(NodeIndex(21)))
Ui(WidgetCapturesMouse(NodeIndex(20)))
```

To me, that seems to indicate that it is a ```winit``` issue.

xorg is doing the conversion from Touch to Mouse, but doesn't trigger a Mouse Button Click.
I'll keep playing around as there are a few things I want to try.

**Comment by tl8roy** [comment]
Adding ```.with_multitouch()``` to the winit builder changes the event to something useful:

```
Raw(Move(Touch(TouchArgs { device: 0, id: 13, x: -145.25558471679688, y: -320.6142578125, z: 0, px: 0, py: 0, pz: 1, is_3d: false, touch: Start })))
Ui(Move(Some(NodeIndex(21)), Move { motion: Touch(TouchArgs { device: 0, id: 13, x: -145.25558471679688, y: -320.6142578125, z: 0, px: 0, py: 0, pz: 1, is_3d: false, touch: Start }), modifiers:  }))
Raw(Move(Touch(TouchArgs { device: 0, id: 13, x: -145.25558471679688, y: -320.6142578125, z: 0, px: 0, py: 0, pz: 1, is_3d: false, touch: End })))
Ui(Move(Some(NodeIndex(21)), Move { motion: Touch(TouchArgs { device: 0, id: 13, x: -145.25558471679688, y: -320.6142578125, z: 0, px: 0, py: 0, pz: 1, is_3d: false, touch: End }), modifiers:  }))
```

**Comment by tl8roy** [comment]
In processing touch events, a Touch Start event should be treated as Mouse Btn Down and the Touch End event should look like a Mouse Btn Click

**Comment by mitchmindtree** [comment]
> In processing touch events, a Touch Start event should be treated as Mouse Btn Down and the Touch End event should look like a Mouse Btn Click

Originally I was thinking we'd have a separate `Tap` event for taps on a touch pad (along with ways of interpreting other touch gestures), but perhaps it's OK to interpret taps as `Click`s? If we are going to add `Click`s this way, we should change [the `button` field](http://docs.piston.rs/conrod/conrod/event/struct.Click.html) to let the user distinguish between whether the source was a mouse button or touch pad. I'm still not sure whether it's a good idea to mix the two into one event though.

**Comment by tl8roy** [comment]
As a start implementing a ```Touch Start``` and ```Touch End``` in ```conrod::event``` sounds logical to me. This can then be used as a base for mapping to other events.

The next thing I would think of doing is adding a ```Touch``` to ```conrod::input::state::mouse::Button```. That way you can keep the structs the same and still pick up what actually happened in single touch.

The problems start when multi touch is in play (My application doesn't need that). I'm not really sure how to deal with that but maybe that needs to have a separate event type.

**Comment by mitchmindtree** [comment]
> As a start implementing a Touch Start and Touch End in conrod::event sounds logical to me. This can then be used as a base for mapping to other events.

This should already be working via the `Input::Move` variant, which holds a `Motion` enum with a `Touch` variant. This `Touch` variant provides the following info: [TouchArgs](http://docs.piston.rs/conrod/conrod/input/struct.TouchArgs.html). I don't really like how `Touch` is a part of the `Motion` variant though, it should probably be a variant of the `Input` enum instead.

> The next thing I would think of doing is adding a Touch to conrod::input::state::mouse::Button. That way you can keep the structs the same and still pick up what actually happened in single touch.

I'd prefer not to mix touch code into the mouse module, but we probably will end up defining our own `Touch` type, as the `Touch` enum provided by pistoncore-input has stuff we don't need like 3D touch and also states that coords are normalised which they probably won't in our case.

> The problems start when multi touch is in play

What kind of issues are you worried about wrt to multi-touch? I think the current API should be fine where a unique ID is provided for each touch source (i.e. each finger).

> I'm not really sure how to deal with that but maybe that needs to have a separate event type.

Yeah, I think I would prefer to have a separate `Tap` event variant for registering taps on a touch devices. Then we could provide helper methods which still make it easy for widgets to respond to either taps or clicks. I.e. [this part](http://docs.piston.rs/conrod/src/conrod/widget/button.rs.html#372) of the `Button` widget's update method

```rust
let times_clicked = input.clicks().left().count() as u16;
```

could be done like this:

```rust
let times_triggered = (input.clicks().left().count() + input.taps().count()) as u16;
```

Will keep giving this some thought!

**Comment by tl8roy** [comment]
@mitchmindtree I think I might defer to your judgement as it sounds like you have been thinking about this for a while.

The ```times_triggered``` method looks like a sensible way of doing it.

**Comment by mitchmindtree** [comment]
Hey @tl8roy, just letting you know I should get some time to look at this tonight and tomorrow night. Will keep you in the loop here :+1:
