### ISSUE TITLE
Running the Conrod Examples

### ISSUE THREAD

**Issue by CedricTschentscher** [PistonDevelopers/conrod#950]
Hey,

I cannot run: "cargo run --release --example all_widgets" in my PowerShell,   because there is no "all_widgets". 
It also causes an error when i try to run 
cargo run --release --example canvas
cargo run --release --example primitives
cargo run --release --example text
---> "This example requires the `winit` and `glium` features."

Can anyone help me?

**Comment by mitchmindtree** [comment]
Ah thanks a lot for the issue, the guide is a bit dated at the moment!

> ---> "This example requires the winit and glium features."

By this, the example is referring to [cargo features](http://doc.crates.io/manifest.html#the-features-section). You can compile a target with a specific set of features like so:
```
cargo run --release --features "winit glium" --example canvas
```

Hope this helps!
