### ISSUE TITLE
Fullscreen support in UiBuilder

### ISSUE THREAD

**Issue by Boscop** [PistonDevelopers/conrod#965]
Is there a way to make the conrod GUI fullscreen with the winit backend?
If not, it should probably be an option in UiBuilder..

**Comment by mitchmindtree** [comment]
@Boscop conrod does not have any control over the window or backend, it just renders for the window dimensions it is given. You should be able to make your window fullscreen when building the winit `Window` with [`with_fullscreen`](https://docs.rs/winit/0.6.3/winit/struct.WindowBuilder.html#method.with_fullscreen).
