### ISSUE TITLE
Question: Is Text rendering special?

### ISSUE THREAD

**Issue by bugabinga** [PistonDevelopers/conrod#973]
Hello,
I am curious how text rendering is handled in conrod from an overview perspective. I have browsed the source a little but the `text.rs` file seems too simple to be able to answer this ;). I guess it is very dependend on the backend used?

I know from experience and from other devs, that (protable) font rendering seems to always be a special beast with unique challenges. Do you share this experience? How is conrod tackling this architectually?

Best regards, Oliver.

**Comment by daboross** [comment]
I can't speak to the actual rendering in the backend, but conrod's backend-agnostic code does definitely handle text separately.

All widget code outputs rendering primitives, which each have one of 5 different [PrimitiveKind](https://github.com/PistonDevelopers/conrod/blob/master/src/render.rs#L94)s - Rectangle, Polygon, Lines, Image and Text. These primitives are then what the backend consumes to render.
