### ISSUE TITLE
Request For Office Hours/Online co working

### ISSUE THREAD

**Issue by karan-ta** [PistonDevelopers/conrod#976]
Hi

Thanks a ton for making conrod and making it possible to make a fast gui app and also cross platform.

I am a happy user of conrod.
I have limited exposure to graphics programming before conrod.

I would love to use conrod in long run to make cool gui apps.
It would be great if there can be online meetings to discuss the core code, issues, future work.
It would help newbie devs like me to contribute and participate more deeply as compared to just being a user of the awesome conrod library.

We can follow below links 
https://en.wikipedia.org/wiki/Pair_programming 
https://en.wikipedia.org/wiki/Mob_programming. 
http://legacycoderocks.libsyn.com/mob-programming-with-woody-zuill.

So Far - i have not had any issues. 
Gaps in rust practice, knowledge have been supported by irc rust channel.

It would also be really awesome to have irc channel for conrod.

What do fellow users think :) 

cheers,
Karan

**Comment by karan-ta** [comment]
Thanks a bunch for making conrod and making it possible to make fast gui apps.

**Comment by beatgammit** [comment]
Seeing as Conrod specifically and Piston in general are designed for game development, I think the general purpose IRC channel #rust-gamedev is the best place for this type of discussion. This way you can get help from anyone in the Rust gamedev community instead of just the Piston developers.

**Comment by karan-ta** [comment]
For a newbie like me - there are many unknowns and a clear learning path is hard to see.

So a few office hours would be great.
we can divide the issues and guide incolved programmers.

This will be quite awesome. We can update the conrod guide as well.

**Comment by daboross** [comment]
I'd be interested in teaming up on stuff, but I don't think I have any consistent enough hours to be worth posting - my schedule is all over.

Right now I've mostly been talking about conrod via github issues and the [#rust-gamedev](http://chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-gamedev) IRC - this has worked relatively well at least for talking about design and stuff. The IRC is nice for intermittent chatting when you happen to be online at the same time as someone else, but if you leave it open while you're online you can also just ask a question and let anyone who has anything to say respond to you when they come online.
