### ISSUE TITLE
[Question] How to detect keyboard event CTRL + P throughout the application.

### ISSUE THREAD

**Issue by karan-ta** [PistonDevelopers/conrod#978]
Hi 

i am making an application with conrod.
I want to display a canvas/window when ctrl +P is pressed.

So far i can only detect a keypress for 'P' 
i cannot detect CTRL + 'P'

```
`while let Some(event) = window.next_event(&mut events) {
        // Convert the piston event to a conrod event.
        if let Some(e) = piston::window::convert_event(event.clone(), &window) {
            let p_press_input = Input::Press(input::Button::Keyboard(Key::P))    ;
            let b_press_input = Input::Press(input::Button::Keyboard(Key::B))    ;
            let home_press_input = Input::Press(input::Button::Keyboard(Key::Escape))    ;
            if e == p_press_input{`
```

Please guide.

cheers,
Karan

**Comment by karan-ta** [comment]
fixed. just added a variable outside the event loop to track if ctrl was pressed.
if is_ctrl_pressed{

}
is_ctrl_pressed should be outside the event loop.

**Comment by mitchmindtree** [comment]
As a side-note, this should be easier to do using `glutin` directly, as it provides a `WindowEvent::KeyboardInput` event variant that provides the state of all modifiers during each key state change.
