### ISSUE TITLE
Question: Glium alternative?

### ISSUE THREAD

**Issue by Geobert** [PistonDevelopers/conrod#989]
Hello,
I'm new to Rust and I'm trying to code a time tracker app and I'd like to use conrod for its UI.

However, I've seen that all the examples uses glium but this one is abandoned.
So I'm wondering what are the alternatives? Is there more examples for them?

Thank you!

**Comment by daboross** [comment]
Hi,

There's an alternative `piston-graphics` back end used in some of the examples - but I'd just recommend using glium if it works for you.

The author is no longer doing feature updates to glium, but it is stable and will be supported with bug fixes for the foreseeable future. It's fairly fast, and does work.

**Comment by mitchmindtree** [comment]
@Geobert just to clarify, glium itself is only abandoned in the sense that the original author no longer actively develops it. It is still one of (if not the) most accessible, thorough and safe set of idiomatic bindings to OpenGL that currently exist for Rust. It is still being maintained by the community (including myself) and the original author continues to merge PRs. There's also discussion of moving the repo into [its own organisation](https://github.com/tomaka/glium/issues/532).

**Comment by Geobert** [comment]
Ok, thank you all for your answers :)
