### ISSUE TITLE
Update daggy version to allow conrod to build

### ISSUE THREAD

**Issue by azriel91** [PistonDevelopers/conrod#998]
Here's a dependency chain:

`conrod -> daggy -> petgraph -> rust std`.

The recent change to Rust std broke `petgraph`, but was fixed in `petgraph 0.4.5` (see https://github.com/bluss/petgraph/issues/153).

https://github.com/mitchmindtree/daggy/issues/12 is `daggy`'s ticket to pick up the latest `petgraph`. When that's released, we need to update `conrod` to pick up the latest `daggy` to allow it to build.

**Comment by vilunov** [comment]
The daggy is fixed now and conrod is fully compatible with daggy v0.5.0. Anyone up for updating conrod?

**Comment by mitchmindtree** [comment]
If someone could submit a PR for this I'd be happy to merge and publish it :+1: Otherwise I'll get around to it next time I'm working on conrod (I'm currently a bit busy addressing some upstream issues in winit, glutin and glium).

**Comment by mitchmindtree** [comment]
Closed by #1000.
